// 問題データ（Q1-10は記事版 id3691 と同期・Q11-20はアプリ限定ドリル）
const PROBLEMS = [
  {"id":1,"title":"map：税込み価格に変換","questionHtml":"商品リスト <code>products</code> の価格を、すべて税込み（10%）に変換した新しい配列を作成してください。","starter":"const products = [\n  { name: 'Tシャツ', price: 2000 },\n  { name: 'パーカー', price: 5000 },\n  { name: 'キャップ', price: 1500 },\n  { name: 'スニーカー', price: 8000 }\n];\n","answer":"const taxIncluded = products.map(item => ({\n  ...item,\n  price: item.price * 1.1\n}));\nconsole.log(taxIncluded);"},
  {"id":2,"title":"filter：条件で絞り込み","questionHtml":"ユーザーリスト <code>users</code> から、20歳以上かつアクティブなユーザーだけを抽出してください。","starter":"const users = [\n  { name: '田中', age: 25, active: true },\n  { name: '佐藤', age: 17, active: true },\n  { name: '鈴木', age: 30, active: false },\n  { name: '高橋', age: 22, active: true },\n  { name: '伊藤', age: 19, active: true }\n];\n","answer":"const activeAdults = users.filter(user => user.age >= 20 && user.active);\nconsole.log(activeAdults);"},
  {"id":3,"title":"find / findIndex：最初の一致を探す","questionHtml":"注文リスト <code>orders</code> から、ステータスが「pending」の最初の注文とそのインデックス番号を取得してください。","starter":"const orders = [\n  { id: 101, status: 'completed', total: 3000 },\n  { id: 102, status: 'completed', total: 1500 },\n  { id: 103, status: 'pending', total: 4200 },\n  { id: 104, status: 'pending', total: 800 },\n  { id: 105, status: 'cancelled', total: 2000 }\n];\n","answer":"const pendingOrder = orders.find(order => order.status === 'pending');\nconst pendingIndex = orders.findIndex(order => order.status === 'pending');\nconsole.log(pendingOrder);\nconsole.log(pendingIndex);"},
  {"id":4,"title":"reduce：合計金額を集計","questionHtml":"カートの商品リスト <code>cart</code> から、合計金額を計算してください。","starter":"const cart = [\n  { name: 'ノートPC', price: 120000, quantity: 1 },\n  { name: 'マウス', price: 3000, quantity: 2 },\n  { name: 'キーボード', price: 8000, quantity: 1 },\n  { name: 'モニター', price: 35000, quantity: 2 }\n];\n","answer":"const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);\nconsole.log(total);"},
  {"id":5,"title":"some / every：条件判定","questionHtml":"パスワードリスト <code>passwords</code> に対して、8文字以上のパスワードが1つでもあるか、すべてのパスワードが8文字以上か、を判定してください。","starter":"const passwords = ['abc', 'password123', 'hello', 'securePass!', '12345678'];\n","answer":"const hasLong = passwords.some(pw => pw.length >= 8);\nconst allLong = passwords.every(pw => pw.length >= 8);\nconsole.log(hasLong, allLong);"},
  {"id":6,"title":"sort：日付の並び替え","questionHtml":"記事リスト <code>articles</code> を、公開日が新しい順に並べ替えてください（元の配列は変更しないこと）。","starter":"const articles = [\n  { title: 'CSS Grid入門', publishedAt: '2025-01-15' },\n  { title: 'React Hooks解説', publishedAt: '2025-03-20' },\n  { title: 'JavaScript基礎', publishedAt: '2024-12-01' },\n  { title: 'TypeScript実践', publishedAt: '2025-02-10' }\n];\n","answer":"const sorted = [...articles].sort((a, b) =>\n  b.publishedAt.localeCompare(a.publishedAt)\n);\nsorted.forEach(a => console.log(a.title));"},
  {"id":7,"title":"map + filter：合格者の名前を抽出","questionHtml":"生徒リスト <code>students</code> から、合格者（スコア60以上）の名前だけを抽出した配列を作成してください。","starter":"const students = [\n  { name: '山田', score: 85 },\n  { name: '中村', score: 42 },\n  { name: '小林', score: 73 },\n  { name: '加藤', score: 58 },\n  { name: '吉田', score: 91 }\n];\n","answer":"const passedNames = students\n  .filter(s => s.score >= 60)\n  .map(s => s.name);\nconsole.log(passedNames);"},
  {"id":8,"title":"reduce：カテゴリごとにグループ化","questionHtml":"商品リスト <code>items</code> を、カテゴリごとにグループ化したオブジェクトに変換してください。","starter":"const items = [\n  { name: 'りんご', category: 'fruit' },\n  { name: 'キャベツ', category: 'vegetable' },\n  { name: 'バナナ', category: 'fruit' },\n  { name: 'にんじん', category: 'vegetable' },\n  { name: 'ぶどう', category: 'fruit' }\n];\n","answer":"const grouped = items.reduce((acc, item) => ({\n  ...acc,\n  [item.category]: [...(acc[item.category] || []), item.name]\n}), {});\nconsole.log(grouped);"},
  {"id":9,"title":"flatMap：スキルを重複なしで集約","questionHtml":"ユーザーリスト <code>developers</code> から、全ユーザーのスキルを重複なしで1つの配列にまとめてください。","starter":"const developers = [\n  { name: '田中', skills: ['HTML', 'CSS', 'JavaScript'] },\n  { name: '佐藤', skills: ['JavaScript', 'React', 'TypeScript'] },\n  { name: '鈴木', skills: ['CSS', 'React', 'Vue'] }\n];\n","answer":"const allSkills = [...new Set(developers.flatMap(dev => dev.skills))];\nconsole.log(allSkills);"},
  {"id":10,"title":"総合：売上データの集計","questionHtml":"売上データ <code>sales</code> から、カテゴリごとの売上合計、売上トップ3の商品名、全商品の平均単価を求めてください。","starter":"const sales = [\n  { product: 'ノートPC', category: 'electronics', price: 120000, sold: 15 },\n  { product: 'マウス', category: 'electronics', price: 3000, sold: 200 },\n  { product: 'デスク', category: 'furniture', price: 45000, sold: 30 },\n  { product: 'チェア', category: 'furniture', price: 35000, sold: 50 },\n  { product: 'モニター', category: 'electronics', price: 40000, sold: 80 },\n  { product: 'ライト', category: 'furniture', price: 8000, sold: 100 }\n];\n","answer":"const salesByCategory = sales.reduce((acc, item) => ({\n  ...acc,\n  [item.category]: (acc[item.category] || 0) + item.price * item.sold\n}), {});\n\nconst top3 = [...sales]\n  .sort((a, b) => (b.price * b.sold) - (a.price * a.sold))\n  .slice(0, 3)\n  .map(item => item.product);\n\nconst avgPrice = sales.reduce((sum, item) => sum + item.price, 0) / sales.length;\n\nconsole.log(salesByCategory, top3, avgPrice);"},
  {"id":11,"title":"includes / indexOf：在庫チェック","questionHtml":"配列 <code>stock</code> に「banana」が含まれるか（true / false）と、「orange」が何番目（インデックス）にあるかを表示してください。","starter":"const stock = ['apple', 'banana', 'orange', 'grape'];\n","answer":"console.log(stock.includes('banana'));\nconsole.log(stock.indexOf('orange'));"},
  {"id":12,"title":"slice：ページネーション","questionHtml":"記事リスト <code>posts</code> から、2ページ目（1ページ3件）の記事だけを取り出して表示してください（元の配列は変更しないこと）。","starter":"const posts = ['記事1', '記事2', '記事3', '記事4', '記事5', '記事6', '記事7'];\nconst page = 2;\nconst perPage = 3;\n","answer":"const pageItems = posts.slice((page - 1) * perPage, page * perPage);\nconsole.log(pageItems);"},
  {"id":13,"title":"splice：破壊的な削除と非破壊の削除","questionHtml":"配列 <code>members</code> からインデックス1の要素を除いた配列を、①元の配列を変更しない方法（filterなど）②<code>splice</code> の2通りで作ってください。spliceを使った場合に元の配列がどうなるかも表示して確認しましょう。","starter":"const members = ['田中', '佐藤', '鈴木', '高橋'];\n","answer":"const removed = members.filter((_, i) => i !== 1);\nconsole.log(removed);\n\nconst copy = [...members];\ncopy.splice(1, 1);\nconsole.log(copy);\nconsole.log(members); // 元の配列は変わっていない（spliceはcopyに対して実行）"},
  {"id":14,"title":"join / split：CSV変換","questionHtml":"配列 <code>tags</code> をカンマ区切りの1つの文字列に、文字列 <code>csv</code> を配列に、それぞれ変換して表示してください。","starter":"const tags = ['JavaScript', '配列', '練習問題'];\nconst csv = 'HTML,CSS,JavaScript';\n","answer":"console.log(tags.join(','));\nconsole.log(csv.split(','));"},
  {"id":15,"title":"Array.from：連番の生成","questionHtml":"<code>Array.from</code> を使って1〜10の連番の配列を生成して表示してください。さらに、その配列から3の倍数だけを取り出して表示してください。","starter":"","answer":"const nums = Array.from({ length: 10 }, (_, i) => i + 1);\nconsole.log(nums);\nconsole.log(nums.filter(n => n % 3 === 0));"},
  {"id":16,"title":"at / findLast：末尾からのアクセス","questionHtml":"ログリスト <code>logs</code> の最後の要素を <code>at()</code> で、最後に発生した level が「error」のログを <code>findLast()</code> で取得して表示してください。","starter":"const logs = [\n  { time: '09:00', level: 'info' },\n  { time: '10:30', level: 'error' },\n  { time: '11:15', level: 'info' },\n  { time: '12:40', level: 'error' },\n  { time: '13:05', level: 'info' }\n];\n","answer":"console.log(logs.at(-1));\nconsole.log(logs.findLast(log => log.level === 'error'));"},
  {"id":17,"title":"concat / スプレッド構文：配列の結合","questionHtml":"2つの配列 <code>frontend</code> と <code>backend</code> を結合した新しい配列を、<code>concat</code> とスプレッド構文の2通りで作成して表示してください。","starter":"const frontend = ['HTML', 'CSS'];\nconst backend = ['Node.js', 'SQL'];\n","answer":"console.log(frontend.concat(backend));\nconsole.log([...frontend, ...backend]);"},
  {"id":18,"title":"sortの落とし穴：数値の昇順","questionHtml":"配列 <code>scores</code> を <code>sort()</code> だけで並べ替えるとどうなるかを表示して確認し、そのうえで正しく数値の昇順に並べ替えた新しい配列を作成してください。","starter":"const scores = [40, 100, 1, 5, 25, 10];\n","answer":"console.log([...scores].sort()); // 文字列として比較され [1, 10, 100, 25, 40, 5] になる\n\nconst sorted = [...scores].sort((a, b) => a - b);\nconsole.log(sorted);"},
  {"id":19,"title":"reduce応用：出現回数のカウント","questionHtml":"投票結果 <code>votes</code> から、それぞれの得票数を集計したオブジェクト（例: <code>{犬: 3, ...}</code>）を作成してください。","starter":"const votes = ['犬', '猫', '犬', '鳥', '猫', '犬'];\n","answer":"const count = votes.reduce((acc, v) => ({\n  ...acc,\n  [v]: (acc[v] || 0) + 1\n}), {});\nconsole.log(count);"},
  {"id":20,"title":"総仕上げ：メソッドチェーン","questionHtml":"社員リスト <code>employees</code> から、開発部（dept が「dev」）の社員の平均給与を <code>filter → map → reduce</code> のチェーンで計算して表示してください。","starter":"const employees = [\n  { name: '田中', dept: 'dev', salary: 400000 },\n  { name: '佐藤', dept: 'sales', salary: 350000 },\n  { name: '鈴木', dept: 'dev', salary: 500000 },\n  { name: '高橋', dept: 'hr', salary: 300000 },\n  { name: '伊藤', dept: 'dev', salary: 450000 }\n];\n","answer":"const devSalaries = employees\n  .filter(e => e.dept === 'dev')\n  .map(e => e.salary);\nconst avg = devSalaries.reduce((sum, s) => sum + s, 0) / devSalaries.length;\nconsole.log(avg);"}
];

const LEVELS = [
  { key: 'all', label: 'すべて (20問)', range: [1, 20] },
  { key: 'basic', label: '基本 1-6', range: [1, 6] },
  { key: 'combo', label: '組み合わせ・総合 7-10', range: [7, 10] },
  { key: 'extra', label: 'アプリ限定 11-20', range: [11, 20] }
];
