// 問題データ（Q1-10は記事版 id1334 と同期・Q11-20はアプリ限定ドリル）
// stageHtml: プレビューiframeに描画するHTML。answerはiframe内で実行される
const PROBLEMS = [
  {"id":1,"title":"テキストの変更","questionHtml":"ボタンをクリックすると、<code>#text1</code> のテキストを「こんにちはJavaScript！」に変更してください。","stageHtml":"<p id=\"text1\">こんにちは！</p>\n<button id=\"btn1\">テキスト変更</button>","answer":"document.getElementById('btn1').addEventListener('click', () => {\n  document.getElementById('text1').textContent = 'こんにちはJavaScript！';\n});"},
  {"id":2,"title":"要素の非表示","questionHtml":"ボタンをクリックすると、ボックス <code>#box2</code> を非表示にしてください（<code>style.display</code> を操作します）。","stageHtml":"<div id=\"box2\" style=\"background: #eee; padding: 1rem;\">このボックスを非表示</div>\n<button id=\"btn2\">非表示にする</button>","answer":"document.getElementById('btn2').addEventListener('click', () => {\n  document.getElementById('box2').style.display = 'none';\n});"},
  {"id":3,"title":"入力値の表示","questionHtml":"入力欄 <code>#input3</code> に入力した値を、ボタンクリックで <code>#output3</code> に表示してください。","stageHtml":"<input type=\"text\" id=\"input3\" placeholder=\"入力してください\">\n<button id=\"btn3\">表示する</button>\n<p id=\"output3\"></p>","answer":"document.getElementById('btn3').addEventListener('click', () => {\n  const inputValue = document.getElementById('input3').value;\n  document.getElementById('output3').textContent = inputValue;\n});"},
  {"id":4,"title":"リストに項目を追加","questionHtml":"ボタンをクリックするたびに、リスト <code>#list4</code> へ「新しい項目」を追加してください（<code>createElement</code>＋<code>appendChild</code>）。","stageHtml":"<ul id=\"list4\">\n  <li>既存の項目</li>\n</ul>\n<button id=\"btn4\">追加する</button>","answer":"document.getElementById('btn4').addEventListener('click', () => {\n  const li = document.createElement('li');\n  li.textContent = '新しい項目';\n  document.getElementById('list4').appendChild(li);\n});"},
  {"id":5,"title":"最後の項目を削除","questionHtml":"ボタンをクリックすると、リスト <code>#list5</code> の最後の項目を削除してください。","stageHtml":"<ul id=\"list5\">\n  <li>1つ目</li>\n  <li>2つ目</li>\n  <li>3つ目</li>\n</ul>\n<button id=\"btn5\">最後を削除</button>","answer":"document.getElementById('btn5').addEventListener('click', () => {\n  const list = document.getElementById('list5');\n  if (list.lastElementChild) {\n    list.removeChild(list.lastElementChild);\n  }\n});"},
  {"id":6,"title":"クラスのトグル","questionHtml":"ボタンをクリックするたびに、<code>#toggleBox</code> へ <code>.active</code> クラスをトグルで付け外しして背景色を切り替えてください。","stageHtml":"<div id=\"toggleBox\" class=\"box\">クラスをトグル</div>\n<button id=\"btn6\">トグル</button>\n\n<style>\n  .box {\n    padding: 1rem;\n    background-color: lightgray;\n  }\n\n  .active {\n    background-color: lightgreen;\n  }\n</style>","answer":"document.getElementById('btn6').addEventListener('click', () => {\n  document.getElementById('toggleBox').classList.toggle('active');\n});"},
  {"id":7,"title":"画像のsrc変更","questionHtml":"ボタンをクリックするたびに、画像 <code>#image7</code> の <code>src</code> 属性をランダムなURLに変更してください。","stageHtml":"<img id=\"image7\" src=\"https://picsum.photos/200?random=1\" alt=\"ランダム画像\" width=\"120\" height=\"120\">\n<button id=\"btn7\">画像を変更</button>","answer":"document.getElementById('btn7').addEventListener('click', () => {\n  document.getElementById('image7').src = 'https://picsum.photos/200?random=' + Math.floor(Math.random() * 100);\n});"},
  {"id":8,"title":"タブUI","questionHtml":"タブボタンをクリックすると、対応するコンテンツだけが表示されるタブUIを作成してください（<code>data-tab</code> 属性でひも付けます）。","stageHtml":"<div class=\"tabs\">\n  <button class=\"tab\" data-tab=\"tab1\">タブ1</button>\n  <button class=\"tab\" data-tab=\"tab2\">タブ2</button>\n</div>\n<div id=\"tab1\" class=\"tab-content\">タブ1の内容</div>\n<div id=\"tab2\" class=\"tab-content hidden\">タブ2の内容</div>\n\n<style>\n  .hidden {\n    display: none;\n  }\n</style>","answer":"const tabs = document.querySelectorAll('.tab');\nconst contents = document.querySelectorAll('.tab-content');\ntabs.forEach(tab => {\n  tab.addEventListener('click', () => {\n    const target = tab.dataset.tab;\n    contents.forEach(content => content.classList.add('hidden'));\n    document.getElementById(target).classList.remove('hidden');\n  });\n});"},
  {"id":9,"title":"モーダルの開閉","questionHtml":"モーダルを開くボタンと閉じるボタンを実装し、背景クリックでも閉じるようにしてください。","stageHtml":"<button id=\"openModal\">モーダルを開く</button>\n\n<div id=\"modal\" class=\"modal hidden\">\n  <div class=\"modal-content\">\n    <p>これはモーダルです</p>\n    <button id=\"closeModal\">閉じる</button>\n  </div>\n</div>\n\n<style>\n  .modal {\n    position: fixed;\n    inset: 0;\n    background: rgba(0,0,0,0.6);\n    display: flex;\n    justify-content: center;\n    align-items: center;\n  }\n\n  .modal-content {\n    background: white;\n    padding: 2rem;\n    border-radius: 8px;\n  }\n\n  .hidden {\n    display: none;\n  }\n</style>","answer":"const modal = document.getElementById('modal');\ndocument.getElementById('openModal').addEventListener('click', () => {\n  modal.classList.remove('hidden');\n});\ndocument.getElementById('closeModal').addEventListener('click', () => {\n  modal.classList.add('hidden');\n});\nmodal.addEventListener('click', (e) => {\n  if (e.target === modal) {\n    modal.classList.add('hidden');\n  }\n});"},
  {"id":10,"title":"アコーディオン","questionHtml":"質問をクリックすると答えが開き、もう一度クリックすると閉じるアコーディオンを実装してください。","stageHtml":"<div class=\"accordion\">\n  <button class=\"accordion-btn\">質問1</button>\n  <div class=\"accordion-content hidden\">答え1：JavaScriptとは？</div>\n</div>\n\n<style>\n  .accordion-content {\n    margin-top: 0.5rem;\n    padding: 1rem;\n    background: #eee;\n  }\n\n  .hidden {\n    display: none;\n  }\n</style>","answer":"const accBtn = document.querySelector('.accordion-btn');\nconst accContent = document.querySelector('.accordion-content');\naccBtn.addEventListener('click', () => {\n  accContent.classList.toggle('hidden');\n});"},
  {"id":11,"title":"querySelectorAllで一括操作","questionHtml":"ボタンをクリックすると、リスト <code>#fruits</code> のすべての項目の先頭に「✓ 」を付けてください（<code>querySelectorAll</code>＋<code>forEach</code>）。","stageHtml":"<ul id=\"fruits\">\n  <li>りんご</li>\n  <li>バナナ</li>\n  <li>ぶどう</li>\n</ul>\n<button id=\"btnAll\">全部に✓を付ける</button>","answer":"document.getElementById('btnAll').addEventListener('click', () => {\n  document.querySelectorAll('#fruits li').forEach(li => {\n    li.textContent = '✓ ' + li.textContent;\n  });\n});"},
  {"id":12,"title":"イベントデリゲーション","questionHtml":"リスト <code>#menu</code> に<strong>1つだけ</strong>リスナーを付け、クリックされた項目の <code>data-page</code> を <code>#picked</code> に表示してください（<code>e.target.closest</code>）。","stageHtml":"<ul id=\"menu\">\n  <li data-page=\"home\">ホーム</li>\n  <li data-page=\"about\">アバウト</li>\n  <li data-page=\"contact\">お問い合わせ</li>\n</ul>\n<p id=\"picked\"></p>","answer":"document.getElementById('menu').addEventListener('click', (e) => {\n  const li = e.target.closest('li');\n  if (!li) return;\n  document.getElementById('picked').textContent = '選択: ' + li.dataset.page;\n});"},
  {"id":13,"title":"inputイベントで文字数カウンター","questionHtml":"テキストエリア <code>#tweet</code> に入力するたび、<code>#count</code> の文字数表示をリアルタイムに更新してください（<code>input</code> イベント）。","stageHtml":"<textarea id=\"tweet\" rows=\"3\" cols=\"30\" placeholder=\"いまどうしてる？\"></textarea>\n<p id=\"count\">0 / 140</p>","answer":"const tweet = document.getElementById('tweet');\nconst count = document.getElementById('count');\ntweet.addEventListener('input', () => {\n  count.textContent = tweet.value.length + ' / 140';\n});"},
  {"id":14,"title":"data属性（dataset）の読み取り","questionHtml":"商品ボタンをクリックすると、その <code>data-item</code> と <code>data-price</code> を読み取って <code>#cartMsg</code> に表示してください。","stageHtml":"<button class=\"buy\" data-item=\"コーヒー\" data-price=\"480\">コーヒー 480円</button>\n<button class=\"buy\" data-item=\"紅茶\" data-price=\"420\">紅茶 420円</button>\n<p id=\"cartMsg\"></p>","answer":"document.querySelectorAll('.buy').forEach(btn => {\n  btn.addEventListener('click', () => {\n    document.getElementById('cartMsg').textContent =\n      btn.dataset.item + 'をカートに追加（' + btn.dataset.price + '円）';\n  });\n});"},
  {"id":15,"title":"insertAdjacentHTMLで位置指定挿入","questionHtml":"ボタンをクリックすると、<code>#timeline</code> の<strong>先頭</strong>に新しい投稿を挿入してください（<code>insertAdjacentHTML('afterbegin', ...)</code>）。","stageHtml":"<div id=\"timeline\">\n  <p>2つ目の投稿</p>\n</div>\n<button id=\"btnBefore\">先頭に投稿を追加</button>","answer":"document.getElementById('btnBefore').addEventListener('click', () => {\n  document.getElementById('timeline').insertAdjacentHTML('afterbegin', '<p><strong>新しい投稿</strong></p>');\n});"},
  {"id":16,"title":"cloneNodeで要素を複製","questionHtml":"ボタンをクリックするたびに、カード <code>#cardTpl</code> を複製して末尾に追加してください（複製側の <code>id</code> は削除します）。","stageHtml":"<div id=\"cardTpl\" class=\"mini-card\">テンプレートカード</div>\n<button id=\"btnClone\">複製する</button>\n\n<style>\n  .mini-card {\n    padding: 0.5rem 1rem;\n    margin: 0.25rem 0;\n    background: #eef;\n    border-radius: 6px;\n  }\n</style>","answer":"document.getElementById('btnClone').addEventListener('click', () => {\n  const copy = document.getElementById('cardTpl').cloneNode(true);\n  copy.removeAttribute('id');\n  document.body.appendChild(copy);\n});"},
  {"id":17,"title":"フォームバリデーション","questionHtml":"フォーム送信時に <code>preventDefault</code> し、空なら「入力してください」、<code>@</code> がなければ「形式が正しくありません」、OKなら「送信OK！」を <code>#error17</code> に表示してください。","stageHtml":"<form id=\"form17\">\n  <input type=\"text\" id=\"email17\" placeholder=\"メールアドレス\">\n  <button type=\"submit\">登録</button>\n</form>\n<p id=\"error17\" style=\"color: #c00;\"></p>","answer":"document.getElementById('form17').addEventListener('submit', (e) => {\n  e.preventDefault();\n  const value = document.getElementById('email17').value.trim();\n  const error = document.getElementById('error17');\n  if (value === '') {\n    error.textContent = 'メールアドレスを入力してください';\n  } else if (!value.includes('@')) {\n    error.textContent = '形式が正しくありません';\n  } else {\n    error.textContent = '送信OK！';\n  }\n});"},
  {"id":18,"title":"キーボードイベント（Enterで追加）","questionHtml":"入力欄 <code>#task18</code> で <code>Enter</code> キーを押すと、入力値をリスト <code>#list18</code> に追加して入力欄を空にしてください（<code>keydown</code> の <code>e.key</code>）。","stageHtml":"<input type=\"text\" id=\"task18\" placeholder=\"Enterで追加\">\n<ul id=\"list18\"></ul>","answer":"const task = document.getElementById('task18');\ntask.addEventListener('keydown', (e) => {\n  if (e.key !== 'Enter' || task.value.trim() === '') return;\n  const li = document.createElement('li');\n  li.textContent = task.value;\n  document.getElementById('list18').appendChild(li);\n  task.value = '';\n});"},
  {"id":19,"title":"ダークモード切替","questionHtml":"ボタンをクリックするたびに、<code>body</code> へ <code>.dark</code> クラスをトグルしてテーマを切り替えてください。","stageHtml":"<button id=\"btnTheme\">ダークモード切替</button>\n<p>テーマが切り替わります</p>\n\n<style>\n  body {\n    transition: background 0.3s, color 0.3s;\n  }\n\n  body.dark {\n    background: #1a1a1a;\n    color: #eee;\n  }\n</style>","answer":"document.getElementById('btnTheme').addEventListener('click', () => {\n  document.body.classList.toggle('dark');\n});"},
  {"id":20,"title":"総仕上げ：リストUI","questionHtml":"「追加」で入力値を <code>#list20</code> に追加（各項目に削除ボタン付き）、追加・削除のたびに <code>#count20</code> の件数を更新してください。","stageHtml":"<input type=\"text\" id=\"item20\" placeholder=\"項目を入力\">\n<button id=\"btnAdd20\">追加</button>\n<ul id=\"list20\"></ul>\n<p id=\"count20\">0 件</p>","answer":"const input = document.getElementById('item20');\nconst list = document.getElementById('list20');\nconst count = document.getElementById('count20');\n\nfunction updateCount() {\n  count.textContent = list.children.length + ' 件';\n}\n\ndocument.getElementById('btnAdd20').addEventListener('click', () => {\n  if (input.value.trim() === '') return;\n  const li = document.createElement('li');\n  li.textContent = input.value + ' ';\n  const del = document.createElement('button');\n  del.textContent = '削除';\n  del.addEventListener('click', () => {\n    li.remove();\n    updateCount();\n  });\n  li.appendChild(del);\n  list.appendChild(li);\n  input.value = '';\n  updateCount();\n});"}
];

const LEVELS = [
  { key: 'all', label: 'すべて (20問)', range: [1, 20] },
  { key: 'basic', label: '基本操作 1-5', range: [1, 5] },
  { key: 'ui', label: 'UI部品 6-10', range: [6, 10] },
  { key: 'extra', label: 'アプリ限定 11-20', range: [11, 20] }
];
