// ドロワー系の開閉パターン（8種）
// 画面の端からメニューが滑り込むタイプ。ボタンは position: fixed で右上に固定する
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

import { panelHtml, btnCss, linkCss, A11Y_HIDE_NOTE } from "./shared.js?v=20260725b";

export const DRAWER_PANELS = [
  {
    key: "hbp-left",
    mode: "panel",
    cat: "drawer",
    label: { ja: "左からドロワー", en: "Drawer from the left" },
    html: panelHtml("hbp-left"),
    css: [
      // メニューは左に出るのでボタンは白背景の上に残る＝開いた時も濃色のままにする
      ...btnCss("hbp-left", "#1e293b"),
      ".hbp-left__nav {",
      "  position: fixed; top: 0; bottom: 0; left: 0; z-index: 20;",
      "  width: min(280px, 78%); padding: 60px 24px 20px;",
      "  display: flex; flex-direction: column; gap: 14px;",
      "  background: #6366f1;",
      "  transform: translateX(-100%);",
      A11Y_HIDE_NOTE,
      "  visibility: hidden;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.4s;",
      "}",
      ...linkCss("hbp-left", "#fff"),
      '.hbp-left__btn[aria-expanded="true"] ~ .hbp-left__nav {',
      "  transform: translateX(0); visibility: visible;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-right",
    mode: "panel",
    cat: "drawer",
    label: { ja: "右からドロワー", en: "Drawer from the right" },
    html: panelHtml("hbp-right"),
    css: [
      ...btnCss("hbp-right", "#fff"),
      ".hbp-right__nav {",
      "  position: fixed; top: 0; bottom: 0; right: 0; z-index: 20;",
      "  width: min(280px, 78%); padding: 60px 24px 20px;",
      "  display: flex; flex-direction: column; gap: 14px;",
      "  background: #6366f1;",
      "  transform: translateX(100%);",
      A11Y_HIDE_NOTE,
      "  visibility: hidden;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.4s;",
      "}",
      ...linkCss("hbp-right", "#fff"),
      '.hbp-right__btn[aria-expanded="true"] ~ .hbp-right__nav {',
      "  transform: translateX(0); visibility: visible;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-top",
    mode: "panel",
    cat: "drawer",
    label: { ja: "上から降りてくる", en: "Slides down from the top" },
    html: panelHtml("hbp-top"),
    css: [
      ...btnCss("hbp-top", "#fff"),
      ".hbp-top__nav {",
      "  position: fixed; top: 0; left: 0; right: 0; z-index: 20;",
      "  padding: 60px 24px 24px;",
      "  display: flex; flex-direction: column; gap: 12px;",
      "  background: #6366f1;",
      "  transform: translateY(-100%);",
      A11Y_HIDE_NOTE,
      "  visibility: hidden;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.4s;",
      "}",
      ...linkCss("hbp-top", "#fff"),
      '.hbp-top__btn[aria-expanded="true"] ~ .hbp-top__nav {',
      "  transform: translateY(0); visibility: visible;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-bottom",
    mode: "panel",
    cat: "drawer",
    label: { ja: "下からせり上がる", en: "Rises from the bottom" },
    html: panelHtml("hbp-bottom"),
    css: [
      // メニューは下に出るのでボタンは白背景の上に残る＝開いた時も濃色のままにする
      ...btnCss("hbp-bottom", "#1e293b"),
      ".hbp-bottom__nav {",
      "  position: fixed; bottom: 0; left: 0; right: 0; z-index: 20;",
      "  padding: 24px; border-radius: 20px 20px 0 0;",
      "  display: flex; flex-direction: column; gap: 12px;",
      "  background: #6366f1;",
      "  transform: translateY(100%);",
      A11Y_HIDE_NOTE,
      "  visibility: hidden;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.4s;",
      "}",
      ...linkCss("hbp-bottom", "#fff"),
      '.hbp-bottom__btn[aria-expanded="true"] ~ .hbp-bottom__nav {',
      "  transform: translateY(0); visibility: visible;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-overlay",
    mode: "panel",
    cat: "drawer",
    label: { ja: "背景を暗転させるドロワー", en: "Drawer with dimmed backdrop" },
    html: panelHtml("hbp-overlay", '<div class="hbp-overlay__back"></div>'),
    css: [
      ...btnCss("hbp-overlay", "#fff"),
      "/* 暗幕。開いている間だけクリックを受け取る */",
      ".hbp-overlay__back {",
      "  position: fixed; inset: 0; z-index: 10;",
      "  background: rgba(15, 23, 42, 0.55);",
      "  opacity: 0; pointer-events: none;",
      "  transition: opacity 0.35s ease;",
      "}",
      ".hbp-overlay__nav {",
      "  position: fixed; top: 0; bottom: 0; right: 0; z-index: 20;",
      "  width: min(280px, 78%); padding: 60px 24px 20px;",
      "  display: flex; flex-direction: column; gap: 14px;",
      "  background: #6366f1;",
      "  transform: translateX(100%);",
      A11Y_HIDE_NOTE,
      "  visibility: hidden;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.4s;",
      "}",
      ...linkCss("hbp-overlay", "#fff"),
      '.hbp-overlay__btn[aria-expanded="true"] ~ .hbp-overlay__back { opacity: 1; pointer-events: auto; }',
      '.hbp-overlay__btn[aria-expanded="true"] ~ .hbp-overlay__nav {',
      "  transform: translateX(0); visibility: visible;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-push",
    mode: "panel",
    cat: "drawer",
    label: { ja: "本文ごと押される", en: "Pushes the page aside" },
    html:
      '<div class="hbp-push">' +
      '<button class="hbp-push__btn" aria-label="メニュー" aria-expanded="false"><span></span><span></span><span></span></button>' +
      '<nav class="hbp-push__nav"><a href="#">Home</a><a href="#">About</a><a href="#">Works</a><a href="#">Contact</a></nav>' +
      '<main class="hbp-push__page"><h2>Push menu</h2><p>ここがページ本文です。</p></main>' +
      "</div>",
    css: [
      ...btnCss("hbp-push", "#1e293b"),
      ".hbp-push__nav {",
      "  position: fixed; top: 0; bottom: 0; left: 0; z-index: 10;",
      "  width: 220px; padding: 60px 20px 20px;",
      "  display: flex; flex-direction: column; gap: 14px;",
      "  background: #6366f1;",
      A11Y_HIDE_NOTE,
      "  /* このパターンは本文がメニューを覆い隠すだけなので、隠す指定がないと常にタブで到達できてしまう */",
      "  visibility: hidden;",
      "  transition: visibility 0s linear 0.4s;",
      "}",
      ...linkCss("hbp-push", "#fff"),
      '.hbp-push__btn[aria-expanded="true"] ~ .hbp-push__nav { visibility: visible; transition: visibility 0s; }',
      "/* .hbp-push__page があなたのページ本文。メニュー幅ぶん右へずらす */",
      ".hbp-push__page {",
      "  position: relative; z-index: 20; min-height: 100%; padding: 20px;",
      "  background: #fff;",
      "  transition: transform 0.4s cubic-bezier(0.65, 0, 0.35, 1);",
      "}",
      ".hbp-push__page h2 { font-size: 1.15rem; margin: 0 0 6px; color: #1e293b; }",
      ".hbp-push__page p { margin: 0; color: #64748b; font-size: 1rem; }",
      '.hbp-push__btn[aria-expanded="true"] ~ .hbp-push__page { transform: translateX(220px); }',
    ],
  },
  {
    key: "hbp-rotate3d",
    mode: "panel",
    cat: "drawer",
    label: { ja: "3D回転して開く", en: "Swings open in 3D" },
    html: panelHtml("hbp-rotate3d"),
    css: [
      // メニューは左に出るのでボタンは白背景の上に残る＝開いた時も濃色のままにする
      ...btnCss("hbp-rotate3d", "#1e293b"),
      ".hbp-rotate3d__nav {",
      "  position: fixed; top: 0; bottom: 0; left: 0; z-index: 20;",
      "  width: min(280px, 78%); padding: 60px 24px 20px;",
      "  display: flex; flex-direction: column; gap: 14px;",
      "  background: #6366f1;",
      "  transform-origin: left center; transform: perspective(900px) rotateY(-100deg);",
      "  opacity: 0;",
      A11Y_HIDE_NOTE,
      "  visibility: hidden;",
      "  transition: transform 0.5s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.3s ease, visibility 0s linear 0.5s;",
      "}",
      ...linkCss("hbp-rotate3d", "#fff"),
      '.hbp-rotate3d__btn[aria-expanded="true"] ~ .hbp-rotate3d__nav {',
      "  transform: perspective(900px) rotateY(0deg); opacity: 1; visibility: visible;",
      "  transition: transform 0.5s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.3s ease, visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-glassdrawer",
    mode: "panel",
    cat: "drawer",
    label: { ja: "ガラス（すりガラス）ドロワー", en: "Frosted glass drawer" },
    html: panelHtml("hbp-glassdrawer"),
    css: [
      ...btnCss("hbp-glassdrawer", "#1e293b"),
      "/* backdrop-filter で背景をぼかす。写真や色の上に重ねると効果が出る */",
      ".hbp-glassdrawer__nav {",
      "  position: fixed; top: 0; bottom: 0; right: 0; z-index: 20;",
      "  width: min(280px, 78%); padding: 60px 24px 20px;",
      "  display: flex; flex-direction: column; gap: 14px;",
      "  background: rgba(99, 102, 241, 0.22);",
      "  backdrop-filter: blur(14px); -webkit-backdrop-filter: blur(14px);",
      "  border-left: 1px solid rgba(255, 255, 255, 0.4);",
      "  transform: translateX(100%);",
      A11Y_HIDE_NOTE,
      "  visibility: hidden;",
      "  transition: transform 0.45s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.45s;",
      "}",
      ...linkCss("hbp-glassdrawer", "#1e293b"),
      '.hbp-glassdrawer__btn[aria-expanded="true"] ~ .hbp-glassdrawer__nav {',
      "  transform: translateX(0); visibility: visible;",
      "  transition: transform 0.45s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
    ],
  },
];
