// フルスクリーン系の開閉パターン（8種）
// 画面全体をメニューで覆うタイプ。閉じている間は visibility: hidden にしてフォーカスも当たらないようにする
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

import { panelHtml, btnCss, linkCss, NAV_LINKS } from "./shared.js?v=20260725a";

// フルスクリーンnavの土台（中央寄せ・閉じている間は非表示）
function fullBase(ns) {
  return [
    "." + ns + "__nav {",
    "  position: fixed; inset: 0; z-index: 20;",
    "  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;",
    "  visibility: hidden;",
    "}",
  ];
}

export const FULLSCREEN_PANELS = [
  {
    key: "hbp-fade",
    mode: "panel",
    cat: "fullscreen",
    label: { ja: "フルスクリーン フェード", en: "Fullscreen fade" },
    html: panelHtml("hbp-fade"),
    css: [
      ...btnCss("hbp-fade", "#fff"),
      ".hbp-fade__nav {",
      "  position: fixed; inset: 0; z-index: 20;",
      "  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;",
      "  background: #6366f1;",
      "  opacity: 0; visibility: hidden;",
      "  transition: opacity 0.35s ease, visibility 0s linear 0.35s;",
      "}",
      ...linkCss("hbp-fade", "#fff"),
      '.hbp-fade__btn[aria-expanded="true"] ~ .hbp-fade__nav {',
      "  opacity: 1; visibility: visible;",
      "  transition: opacity 0.35s ease, visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-down",
    mode: "panel",
    cat: "fullscreen",
    label: { ja: "全画面が上から降りる", en: "Fullscreen drops down" },
    html: panelHtml("hbp-down"),
    css: [
      ...btnCss("hbp-down", "#fff"),
      ".hbp-down__nav {",
      "  position: fixed; inset: 0; z-index: 20;",
      "  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;",
      "  background: #6366f1;",
      "  transform: translateY(-100%); visibility: hidden;",
      "  transition: transform 0.45s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.45s;",
      "}",
      ...linkCss("hbp-down", "#fff"),
      '.hbp-down__btn[aria-expanded="true"] ~ .hbp-down__nav {',
      "  transform: translateY(0); visibility: visible;",
      "  transition: transform 0.45s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-up",
    mode: "panel",
    cat: "fullscreen",
    label: { ja: "全画面が下から上がる", en: "Fullscreen rises up" },
    html: panelHtml("hbp-up"),
    css: [
      ...btnCss("hbp-up", "#fff"),
      ".hbp-up__nav {",
      "  position: fixed; inset: 0; z-index: 20;",
      "  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;",
      "  background: #6366f1;",
      "  transform: translateY(100%); visibility: hidden;",
      "  transition: transform 0.45s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.45s;",
      "}",
      ...linkCss("hbp-up", "#fff"),
      '.hbp-up__btn[aria-expanded="true"] ~ .hbp-up__nav {',
      "  transform: translateY(0); visibility: visible;",
      "  transition: transform 0.45s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-curtainx",
    mode: "panel",
    cat: "fullscreen",
    label: { ja: "左右からカーテンが閉じる", en: "Curtains close from both sides" },
    html: panelHtml("hbp-curtainx"),
    css: [
      ...btnCss("hbp-curtainx", "#fff"),
      ...fullBase("hbp-curtainx"),
      ".hbp-curtainx__nav { transition: visibility 0s linear 0.45s; }",
      "/* 2枚のカーテンは擬似要素。z-index: -1 でリンクの背面に置く */",
      ".hbp-curtainx__nav::before,",
      ".hbp-curtainx__nav::after {",
      '  content: ""; position: absolute; top: 0; bottom: 0; width: 50%; z-index: -1;',
      "  background: #6366f1;",
      "  transition: transform 0.45s cubic-bezier(0.65, 0, 0.35, 1);",
      "}",
      ".hbp-curtainx__nav::before { left: 0; transform: translateX(-100%); }",
      ".hbp-curtainx__nav::after { right: 0; transform: translateX(100%); }",
      ...linkCss("hbp-curtainx", "#fff"),
      ".hbp-curtainx__nav a { opacity: 0; transition: opacity 0.3s ease; }",
      '.hbp-curtainx__btn[aria-expanded="true"] ~ .hbp-curtainx__nav { visibility: visible; transition: visibility 0s; }',
      '.hbp-curtainx__btn[aria-expanded="true"] ~ .hbp-curtainx__nav::before,',
      '.hbp-curtainx__btn[aria-expanded="true"] ~ .hbp-curtainx__nav::after { transform: translateX(0); }',
      '.hbp-curtainx__btn[aria-expanded="true"] ~ .hbp-curtainx__nav a { opacity: 0.9; transition-delay: 0.35s; }',
    ],
  },
  {
    key: "hbp-curtainy",
    mode: "panel",
    cat: "fullscreen",
    label: { ja: "上下からカーテンが閉じる", en: "Curtains close top and bottom" },
    html: panelHtml("hbp-curtainy"),
    css: [
      ...btnCss("hbp-curtainy", "#fff"),
      ...fullBase("hbp-curtainy"),
      ".hbp-curtainy__nav { transition: visibility 0s linear 0.45s; }",
      ".hbp-curtainy__nav::before,",
      ".hbp-curtainy__nav::after {",
      '  content: ""; position: absolute; left: 0; right: 0; height: 50%; z-index: -1;',
      "  background: #6366f1;",
      "  transition: transform 0.45s cubic-bezier(0.65, 0, 0.35, 1);",
      "}",
      ".hbp-curtainy__nav::before { top: 0; transform: translateY(-100%); }",
      ".hbp-curtainy__nav::after { bottom: 0; transform: translateY(100%); }",
      ...linkCss("hbp-curtainy", "#fff"),
      ".hbp-curtainy__nav a { opacity: 0; transition: opacity 0.3s ease; }",
      '.hbp-curtainy__btn[aria-expanded="true"] ~ .hbp-curtainy__nav { visibility: visible; transition: visibility 0s; }',
      '.hbp-curtainy__btn[aria-expanded="true"] ~ .hbp-curtainy__nav::before,',
      '.hbp-curtainy__btn[aria-expanded="true"] ~ .hbp-curtainy__nav::after { transform: translateY(0); }',
      '.hbp-curtainy__btn[aria-expanded="true"] ~ .hbp-curtainy__nav a { opacity: 0.9; transition-delay: 0.35s; }',
    ],
  },
  {
    key: "hbp-skewpanel",
    mode: "panel",
    cat: "fullscreen",
    label: { ja: "斜めに傾いて滑り込む", en: "Slides in at an angle" },
    html: panelHtml("hbp-skewpanel"),
    css: [
      ...btnCss("hbp-skewpanel", "#fff"),
      ".hbp-skewpanel__nav {",
      "  position: fixed; inset: -20% -10%; z-index: 20;",
      "  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;",
      "  background: #6366f1;",
      "  transform: translateY(-120%) skewY(-8deg); visibility: hidden;",
      "  transition: transform 0.5s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.5s;",
      "}",
      ...linkCss("hbp-skewpanel", "#fff"),
      ".hbp-skewpanel__nav a { transform: skewY(8deg); }",
      '.hbp-skewpanel__btn[aria-expanded="true"] ~ .hbp-skewpanel__nav {',
      "  transform: translateY(0) skewY(0deg); visibility: visible;",
      "  transition: transform 0.5s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
      '.hbp-skewpanel__btn[aria-expanded="true"] ~ .hbp-skewpanel__nav a { transform: skewY(0deg); transition: transform 0.5s ease; }',
    ],
  },
  {
    key: "hbp-circle",
    mode: "panel",
    cat: "fullscreen",
    label: { ja: "ボタンから円形に広がる", en: "Circle reveal from the button" },
    html: panelHtml("hbp-circle"),
    css: [
      ...btnCss("hbp-circle", "#fff"),
      "/* clip-path の円をボタン位置（右上）を中心に広げる */",
      ".hbp-circle__nav {",
      "  position: fixed; inset: 0; z-index: 20;",
      "  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;",
      "  background: #6366f1;",
      "  clip-path: circle(0% at calc(100% - 36px) 36px); visibility: hidden;",
      "  transition: clip-path 0.55s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s linear 0.55s;",
      "}",
      ...linkCss("hbp-circle", "#fff"),
      '.hbp-circle__btn[aria-expanded="true"] ~ .hbp-circle__nav {',
      "  clip-path: circle(150% at calc(100% - 36px) 36px); visibility: visible;",
      "  transition: clip-path 0.55s cubic-bezier(0.65, 0, 0.35, 1), visibility 0s;",
      "}",
    ],
  },
  {
    key: "hbp-blinds",
    mode: "panel",
    cat: "fullscreen",
    label: { ja: "ブラインドが順に降りる", en: "Blinds drop one by one" },
    html:
      '<div class="hbp-blinds">' +
      '<button class="hbp-blinds__btn" aria-label="メニュー" aria-expanded="false"><span></span><span></span><span></span></button>' +
      '<div class="hbp-blinds__sheets"><i></i><i></i><i></i><i></i><i></i></div>' +
      '<nav class="hbp-blinds__nav">' +
      NAV_LINKS +
      "</nav>" +
      "</div>",
    css: [
      ...btnCss("hbp-blinds", "#fff"),
      "/* 5枚の帯を時間差で下ろしてブラインドに見せる */",
      ".hbp-blinds__sheets { position: fixed; inset: 0; z-index: 15; display: flex; pointer-events: none; }",
      ".hbp-blinds__sheets i {",
      "  flex: 1; background: #6366f1; transform: scaleY(0); transform-origin: top;",
      "  transition: transform 0.35s ease;",
      "}",
      ".hbp-blinds__nav {",
      "  position: fixed; inset: 0; z-index: 20;",
      "  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 16px;",
      "  opacity: 0; visibility: hidden;",
      "  transition: opacity 0.3s ease, visibility 0s linear 0.3s;",
      "}",
      ...linkCss("hbp-blinds", "#fff"),
      '.hbp-blinds__btn[aria-expanded="true"] ~ .hbp-blinds__sheets i { transform: scaleY(1); }',
      '.hbp-blinds__btn[aria-expanded="true"] ~ .hbp-blinds__sheets i:nth-child(2) { transition-delay: 0.07s; }',
      '.hbp-blinds__btn[aria-expanded="true"] ~ .hbp-blinds__sheets i:nth-child(3) { transition-delay: 0.14s; }',
      '.hbp-blinds__btn[aria-expanded="true"] ~ .hbp-blinds__sheets i:nth-child(4) { transition-delay: 0.21s; }',
      '.hbp-blinds__btn[aria-expanded="true"] ~ .hbp-blinds__sheets i:nth-child(5) { transition-delay: 0.28s; }',
      '.hbp-blinds__btn[aria-expanded="true"] ~ .hbp-blinds__nav {',
      "  opacity: 1; visibility: visible;",
      "  transition: opacity 0.3s ease 0.4s, visibility 0s;",
      "}",
    ],
  },
];
