// 変わり種の開閉パターン（4種）
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

import { panelHtml, btnCss, A11Y_HIDE_NOTE } from "./shared.js?v=20260725a";

export const SPECIAL_PANELS = [
  {
    key: "hbp-radial",
    mode: "panel",
    cat: "special",
    label: { ja: "円形に飛び出す放射メニュー", en: "Radial menu fans out" },
    html: panelHtml("hbp-radial"),
    css: [
      ...btnCss("hbp-radial", "#1e293b"),
      "/* nav はボタン中心の「点」。リンクをそこから弧を描くように飛ばす */",
      ".hbp-radial__nav { position: fixed; top: 36px; right: 36px; z-index: 20; width: 0; height: 0; }",
      "/* 半径124px・直径64pxなら、4つを30度おきに置いても円同士が重ならない */",
      ".hbp-radial__nav a {",
      "  position: absolute; left: 0; top: 0; width: 64px; height: 64px; margin: -32px 0 0 -32px;",
      "  display: flex; align-items: center; justify-content: center; border-radius: 50%;",
      "  background: #6366f1; color: #fff; font-size: 16px; font-weight: 700; letter-spacing: -0.01em;",
      "  text-decoration: none;",
      "  opacity: 0; transform: translate(0, 0) scale(0.3);",
      A11Y_HIDE_NOTE,
      "  visibility: hidden;",
      "  transition: transform 0.45s cubic-bezier(0.34, 1.3, 0.64, 1), opacity 0.3s ease, visibility 0s linear 0.45s;",
      "}",
      '.hbp-radial__btn[aria-expanded="true"] ~ .hbp-radial__nav a {',
      "  opacity: 1; visibility: visible;",
      "  transition: transform 0.45s cubic-bezier(0.34, 1.3, 0.64, 1), opacity 0.3s ease, visibility 0s;",
      "}",
      '.hbp-radial__btn[aria-expanded="true"] ~ .hbp-radial__nav a:nth-child(1) { transform: translate(-124px, 0) scale(1); transition-delay: 0.02s; }',
      '.hbp-radial__btn[aria-expanded="true"] ~ .hbp-radial__nav a:nth-child(2) { transform: translate(-107px, 62px) scale(1); transition-delay: 0.07s; }',
      '.hbp-radial__btn[aria-expanded="true"] ~ .hbp-radial__nav a:nth-child(3) { transform: translate(-62px, 107px) scale(1); transition-delay: 0.12s; }',
      '.hbp-radial__btn[aria-expanded="true"] ~ .hbp-radial__nav a:nth-child(4) { transform: translate(0, 124px) scale(1); transition-delay: 0.17s; }',
    ],
  },
  {
    key: "hbp-morph",
    mode: "panel",
    cat: "special",
    label: { ja: "ボタンがカードに膨らむ", en: "Button morphs into a card" },
    html: panelHtml("hbp-morph"),
    css: [
      ...btnCss("hbp-morph", "#fff"),
      "/* ボタンと同じ位置・同じ大きさの円から、カードへ広げる */",
      ".hbp-morph__nav {",
      "  position: fixed; top: 14px; right: 14px; z-index: 20;",
      "  width: 44px; height: 44px; padding: 0; border-radius: 50%; overflow: hidden;",
      "  display: flex; flex-direction: column; justify-content: center;",
      "  background: #6366f1; opacity: 0; visibility: hidden;",
      "  transition: width 0.4s cubic-bezier(0.65, 0, 0.35, 1), height 0.4s cubic-bezier(0.65, 0, 0.35, 1),",
      "    border-radius 0.4s ease, padding 0.4s ease, opacity 0.25s ease, visibility 0s linear 0.4s;",
      "}",
      ".hbp-morph__nav a {",
      "  padding: 7px 10px; white-space: nowrap;",
      "  color: #fff; font-size: 1rem; font-weight: 700; text-decoration: none;",
      "  opacity: 0; transition: opacity 0.25s ease;",
      "}",
      '.hbp-morph__btn[aria-expanded="true"] ~ .hbp-morph__nav {',
      "  width: 190px; height: 200px; padding: 52px 12px 14px; border-radius: 16px;",
      "  opacity: 1; visibility: visible;",
      "  transition: width 0.4s cubic-bezier(0.65, 0, 0.35, 1), height 0.4s cubic-bezier(0.65, 0, 0.35, 1),",
      "    border-radius 0.4s ease, padding 0.4s ease, opacity 0.25s ease, visibility 0s;",
      "}",
      '.hbp-morph__btn[aria-expanded="true"] ~ .hbp-morph__nav a { opacity: 0.92; transition-delay: 0.28s; }',
    ],
  },
  {
    key: "hbp-rail",
    mode: "panel",
    cat: "special",
    label: { ja: "細いレールが横に広がる", en: "Slim rail expands sideways" },
    html: panelHtml("hbp-rail"),
    css: [
      ...btnCss("hbp-rail", "#1e293b"),
      "/* 閉じている間も細い帯として残るタイプ。幅だけを動かす */",
      ".hbp-rail__nav {",
      "  position: fixed; top: 0; bottom: 0; left: 0; z-index: 20;",
      "  width: 54px; padding: 58px 0 16px; overflow: hidden;",
      "  display: flex; flex-direction: column; gap: 6px;",
      "  background: #6366f1;",
      "  transition: width 0.4s cubic-bezier(0.65, 0, 0.35, 1);",
      "}",
      "/* 閉じている間は文字が途中で切れるので隠す */",
      A11Y_HIDE_NOTE,
      ".hbp-rail__nav a {",
      "  padding: 8px 18px; white-space: nowrap;",
      "  color: #fff; font-size: 1rem; font-weight: 700; text-decoration: none;",
      "  opacity: 0; visibility: hidden;",
      "  transition: opacity 0.25s ease, visibility 0s linear 0.25s, background 0.2s ease;",
      "}",
      ".hbp-rail__nav a:hover { background: rgba(255, 255, 255, 0.15); }",
      '.hbp-rail__btn[aria-expanded="true"] ~ .hbp-rail__nav { width: 190px; }',
      '.hbp-rail__btn[aria-expanded="true"] ~ .hbp-rail__nav a {',
      "  opacity: 0.9; visibility: visible;",
      "  transition: opacity 0.25s ease 0.2s, visibility 0s, background 0.2s ease;",
      "}",
    ],
  },
  {
    key: "hbp-tiles",
    mode: "panel",
    cat: "special",
    label: { ja: "タイルが順に並ぶ", en: "Tiles pop in one by one" },
    html: panelHtml("hbp-tiles"),
    css: [
      ...btnCss("hbp-tiles", "#fff"),
      ".hbp-tiles__nav {",
      "  position: fixed; inset: 0; z-index: 20; padding: 16px;",
      "  display: grid; grid-template-columns: 1fr 1fr; grid-auto-rows: 1fr; gap: 10px;",
      "  background: #1e293b; opacity: 0; visibility: hidden;",
      "  transition: opacity 0.25s ease, visibility 0s linear 0.25s;",
      "}",
      ".hbp-tiles__nav a {",
      "  display: flex; align-items: center; justify-content: center; border-radius: 12px;",
      "  background: #6366f1; color: #fff; font-size: 1rem; font-weight: 700; text-decoration: none;",
      "  opacity: 0; transform: scale(0.55);",
      "  transition: transform 0.4s cubic-bezier(0.34, 1.4, 0.64, 1), opacity 0.3s ease, background 0.2s ease;",
      "}",
      ".hbp-tiles__nav a:nth-child(2) { background: #ec4899; }",
      ".hbp-tiles__nav a:nth-child(3) { background: #ec4899; }",
      '.hbp-tiles__btn[aria-expanded="true"] ~ .hbp-tiles__nav { opacity: 1; visibility: visible; transition: opacity 0.25s ease, visibility 0s; }',
      '.hbp-tiles__btn[aria-expanded="true"] ~ .hbp-tiles__nav a { opacity: 1; transform: scale(1); }',
      '.hbp-tiles__btn[aria-expanded="true"] ~ .hbp-tiles__nav a:nth-child(1) { transition-delay: 0.08s; }',
      '.hbp-tiles__btn[aria-expanded="true"] ~ .hbp-tiles__nav a:nth-child(2) { transition-delay: 0.15s; }',
      '.hbp-tiles__btn[aria-expanded="true"] ~ .hbp-tiles__nav a:nth-child(3) { transition-delay: 0.22s; }',
      '.hbp-tiles__btn[aria-expanded="true"] ~ .hbp-tiles__nav a:nth-child(4) { transition-delay: 0.29s; }',
    ],
  },
];
