// 現在の設定から、コピペで動く自己完結の WebGL スニペットを生成する。
// プレビューと同じシェーダー文字列を埋め込むため、見た目がズレない。
import { VERTEX_SHADER, FRAGMENT_SHADER } from './glass.js?v=20260615'
import { hexToRgb } from './utils.js?v=20260615'

// params: { halfW, halfH, radius, edge, refraction, blur, specular, aberration, tint, tintOpacity, bgUrl }
export function generateSnippet(params) {
  const tint = hexToRgb(params.tint)
  const u = (n) => Number(n.toFixed(3))

  // 出力コード内コメントの言語切り替え（ページ言語に追従）
  const en = params.lang === 'en'
  const C = en
    ? {
        href: '<!-- ▼ Replace href with your link URL. To open in a new tab, add target="_blank" rel="noopener" -->',
        saveJs: '<!-- Save the JS below as liquid-glass.js; adjust the path to where you place it -->',
        imageUrl: '// ▼ Replace with your own image URL',
      }
    : {
        href: '<!-- ▼ href をリンク先URLに差し替えてください。別タブで開くなら target="_blank" rel="noopener" を追加 -->',
        saveJs: '<!-- 下のJSを liquid-glass.js として保存。パスは設置場所に合わせて調整 -->',
        imageUrl: '// ▼ ご自身の画像URLに差し替えてください',
      }

  // シェーダー内の日本語コメントは英語出力に混ざるため、出力時は除去して言語非依存にする
  const stripGlsl = (s) => s.trim().replace(/[ \t]*\/\/[^\n]*/g, '')

  // ボタン内テキスト（DOMオーバーレイ）
  const escaped = String(params.text || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  // リンク先URL。空ならプレースホルダにして差し替えを促す
  const rawUrl = String(params.linkUrl || '').trim()
  const hrefAttr = (rawUrl || '#').replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const urlHint = rawUrl ? '' : `${C.href}\n  `
  // クリック範囲＝ガラスの形だけ。ガラスと同じ寸法・角丸の <a> を中央に重ねる（resize で幅に追従）
  const buttonHtml = (escaped || rawUrl)
    ? `\n  ${urlHint}<a id="liquid-glass-button" href="${hrefAttr}" style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:${u(params.halfW * 2)}px;height:${u(params.halfH * 2)}px;border-radius:${u(params.radius)}px;clip-path:inset(0 round ${u(params.radius)}px);display:flex;align-items:center;justify-content:center;color:${params.textColor};font:600 ${u(params.fontSize)}px/1 system-ui,-apple-system,sans-serif;letter-spacing:-0.01em;text-decoration:none;cursor:pointer;white-space:nowrap">${escaped}</a>`
    : ''

  // HTML（設置したい場所に貼る）と JS（liquid-glass.js として保存）を分けて返す。
  // HTML 側は外部 JS を読み込む <script type="module" src> を同梱する。
  const html = `<!-- Liquid Glass — generated by codequest.work/generator/liquid-glass-generator -->
<div style="position:relative;width:100%;max-width:560px;aspect-ratio:560/360">
  <canvas id="liquid-glass" width="560" height="360" style="width:100%;height:100%;display:block;border-radius:16px"></canvas>${buttonHtml}
</div>
${C.saveJs}
<script type="module" src="liquid-glass.js"></script>`

  const js = `import { Renderer, Triangle, Program, Mesh, Texture } from 'https://cdn.jsdelivr.net/npm/ogl@1.0.11/+esm'

${C.imageUrl}
const BACKGROUND_URL = ${JSON.stringify(params.bgUrl)}

const DESIGN_WIDTH = 560
const LABEL_FONT = ${u(params.fontSize)}

const GLASS = {
  halfW: ${u(params.halfW)}, halfH: ${u(params.halfH)}, radius: ${u(params.radius)}, edge: ${u(params.edge)},
  refraction: ${u(params.refraction)}, blur: ${u(params.blur)}, specular: ${u(params.specular)},
  aberration: ${u(params.aberration)}, tint: [${u(tint[0])}, ${u(tint[1])}, ${u(tint[2])}], tintOpacity: ${u(params.tintOpacity)},
}

const vertex = \`${stripGlsl(VERTEX_SHADER)}\`
const fragment = \`${stripGlsl(FRAGMENT_SHADER)}\`

const canvas = document.getElementById('liquid-glass')
const renderer = new Renderer({ canvas, dpr: Math.min(window.devicePixelRatio, 2), alpha: false, preserveDrawingBuffer: true })
const gl = renderer.gl
const geometry = new Triangle(gl)
const texture = new Texture(gl, { generateMipmaps: false })
const program = new Program(gl, {
  vertex, fragment,
  uniforms: {
    uTexture: { value: texture },
    uResolution: { value: [1, 1] },
    uImageResolution: { value: [1, 1] },
    uGlassCenter: { value: [0, 0] },
    uGlassHalf: { value: [0, 0] },
    uRadius: { value: 0 },
    uEdge: { value: 0 },
    uRefraction: { value: GLASS.refraction },
    uBlur: { value: 0 },
    uSpecular: { value: GLASS.specular },
    uAberration: { value: GLASS.aberration },
    uTint: { value: GLASS.tint },
    uTintOpacity: { value: GLASS.tintOpacity },
  },
})
const mesh = new Mesh(gl, { geometry, program })
const button = document.getElementById('liquid-glass-button')
const wrap = canvas.parentElement

function resize() {
  const w = wrap.clientWidth, h = wrap.clientHeight
  renderer.setSize(w, h)
  const dpr = renderer.dpr
  const s = w / DESIGN_WIDTH
  const U = program.uniforms
  U.uResolution.value = [w * dpr, h * dpr]
  U.uGlassCenter.value = [w * dpr / 2, h * dpr / 2]
  U.uGlassHalf.value = [GLASS.halfW * s * dpr, GLASS.halfH * s * dpr]
  U.uRadius.value = GLASS.radius * s * dpr
  U.uEdge.value = GLASS.edge * s * dpr
  U.uBlur.value = GLASS.blur * s * dpr
  if (button) {
    button.style.width = (GLASS.halfW * 2 * s) + 'px'
    button.style.height = (GLASS.halfH * 2 * s) + 'px'
    button.style.borderRadius = (GLASS.radius * s) + 'px'
    button.style.clipPath = 'inset(0 round ' + (GLASS.radius * s) + 'px)'
    button.style.fontSize = (LABEL_FONT * s) + 'px'
  }
  renderer.render({ scene: mesh })
}

const img = new Image()
img.crossOrigin = 'anonymous'
img.onload = () => {
  texture.image = img
  program.uniforms.uImageResolution.value = [img.naturalWidth, img.naturalHeight]
  resize()
}
img.src = BACKGROUND_URL
window.addEventListener('resize', resize)`

  return { html, js }
}
