// 現在の設定から、コピペで動く自己完結の WebGL スニペットを生成する。
// プレビューと同じシェーダー文字列を埋め込むため、見た目がズレない。
import { VERTEX_SHADER, FRAGMENT_SHADER } from './glass.js?v=20260615'
import { hexToRgb } from './utils.js?v=20260615'

// params: { halfW, halfH, radius, edge, refraction, blur, specular, aberration, tint, tintOpacity, bgUrl }
export function generateSnippet(params) {
  const tint = hexToRgb(params.tint)
  const u = (n) => Number(n.toFixed(3))

  // ボタン内テキスト（DOMオーバーレイ。空なら出力しない）
  const escaped = String(params.text || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const labelHtml = escaped
    ? `\n  <div style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);color:${params.textColor};font:600 ${u(params.fontSize)}px/1 system-ui,-apple-system,sans-serif;letter-spacing:-0.01em;pointer-events:none;white-space:nowrap">${escaped}</div>`
    : ''

  return `<!-- Liquid Glass — generated by codequest.work/generator/liquid-glass-generator -->
<div style="position:relative;display:inline-block;width:100%;max-width:560px">
  <canvas id="liquid-glass" style="width:100%;height:360px;display:block;border-radius:16px"></canvas>${labelHtml}
</div>
<script type="module">
import { Renderer, Triangle, Program, Mesh, Texture } from 'https://cdn.jsdelivr.net/npm/ogl@1.0.11/+esm'

// ▼ ご自身の画像URLに差し替えてください
const BACKGROUND_URL = ${JSON.stringify(params.bgUrl)}

// ガラスの形状・質感（CSSピクセル基準）
const GLASS = {
  halfW: ${u(params.halfW)}, halfH: ${u(params.halfH)}, radius: ${u(params.radius)}, edge: ${u(params.edge)},
  refraction: ${u(params.refraction)}, blur: ${u(params.blur)}, specular: ${u(params.specular)},
  aberration: ${u(params.aberration)}, tint: [${u(tint[0])}, ${u(tint[1])}, ${u(tint[2])}], tintOpacity: ${u(params.tintOpacity)},
}

const vertex = \`${VERTEX_SHADER.trim()}\`
const fragment = \`${FRAGMENT_SHADER.trim()}\`

const canvas = document.getElementById('liquid-glass')
const renderer = new Renderer({ canvas, dpr: Math.min(window.devicePixelRatio, 2), alpha: false, preserveDrawingBuffer: true })
const gl = renderer.gl
const geometry = new Triangle(gl)
const texture = new Texture(gl, { generateMipmaps: false })
const program = new Program(gl, {
  vertex, fragment,
  uniforms: {
    uTexture: { value: texture },
    uResolution: { value: [1, 1] },
    uImageResolution: { value: [1, 1] },
    uGlassCenter: { value: [0, 0] },
    uGlassHalf: { value: [0, 0] },
    uRadius: { value: 0 },
    uEdge: { value: 0 },
    uRefraction: { value: GLASS.refraction },
    uBlur: { value: 0 },
    uSpecular: { value: GLASS.specular },
    uAberration: { value: GLASS.aberration },
    uTint: { value: GLASS.tint },
    uTintOpacity: { value: GLASS.tintOpacity },
  },
})
const mesh = new Mesh(gl, { geometry, program })

function resize() {
  const w = canvas.clientWidth, h = canvas.clientHeight
  renderer.setSize(w, h)
  const dpr = renderer.dpr
  const U = program.uniforms
  U.uResolution.value = [w * dpr, h * dpr]
  U.uGlassCenter.value = [w * dpr / 2, h * dpr / 2]
  U.uGlassHalf.value = [GLASS.halfW * dpr, GLASS.halfH * dpr]
  U.uRadius.value = GLASS.radius * dpr
  U.uEdge.value = GLASS.edge * dpr
  U.uBlur.value = GLASS.blur * dpr
  renderer.render({ scene: mesh })
}

const img = new Image()
img.crossOrigin = 'anonymous'
img.onload = () => {
  texture.image = img
  program.uniforms.uImageResolution.value = [img.naturalWidth, img.naturalHeight]
  resize()
}
img.src = BACKGROUND_URL
window.addEventListener('resize', resize)
</script>`
}
