// Illustrator templates (English). Labels must match illustrator.en.js exactly.

export const TEMPLATES = [
  {
    id: "staples",
    name: "Essentials",
    desc: "Used in every workflow",
    items: [
      { cat: "tools", label: "Selection tool" },
      { cat: "tools", label: "Direct selection tool" },
      { cat: "edit", label: "Undo" },
      { cat: "object", label: "Group" },
      { cat: "object", label: "Transform again" },
      { cat: "object", label: "Lock" },
      { cat: "object", label: "Make clipping mask" },
      { cat: "tools", label: "Pen tool" },
      { cat: "tools", label: "Type tool" },
      { cat: "object", label: "Bring forward" },
      { cat: "view", label: "Toggle Preview / Outline" },
      { cat: "file", label: "Save" },
    ],
  },
  {
    id: "logo",
    name: "Logo / icon design",
    desc: "Paths & Pathfinder",
    items: [
      { cat: "tools", label: "Pen tool" },
      { cat: "tools", label: "Shape Builder tool" },
      { cat: "object", label: "Make compound path" },
      { cat: "type", label: "Create outlines" },
      { cat: "tools", label: "Scale tool" },
      { cat: "tools", label: "Rotate tool" },
      { cat: "tools", label: "Reflect tool" },
      { cat: "object", label: "Make clipping mask" },
      { cat: "panel", label: "Pathfinder panel" },
      { cat: "object", label: "Group" },
    ],
  },
  {
    id: "layout",
    name: "Type & layout",
    desc: "Type, guides, align",
    items: [
      { cat: "tools", label: "Type tool" },
      { cat: "type", label: "Create outlines" },
      { cat: "type", label: "Align center" },
      { cat: "type", label: "Increase font size" },
      { cat: "view", label: "Show / hide guides" },
      { cat: "view", label: "Make guides" },
      { cat: "view", label: "Show / hide rulers" },
      { cat: "object", label: "Bring forward" },
    ],
  },
  {
    id: "paint",
    name: "Illustration / paint",
    desc: "Brushes & Live Paint",
    items: [
      { cat: "tools", label: "Pencil tool" },
      { cat: "tools", label: "Paintbrush tool" },
      { cat: "tools", label: "Blob brush tool" },
      { cat: "tools", label: "Live Paint Bucket tool" },
      { cat: "tools", label: "Gradient tool" },
      { cat: "tools", label: "Toggle fill / stroke" },
      { cat: "tools", label: "Swap fill and stroke" },
      { cat: "object", label: "Group" },
      { cat: "edit", label: "Undo" },
    ],
  },
];
