// デザイナーテンプレート定義
// 各項目は { cat: カテゴリID, label: data.js のラベル完全一致 } で指定し、
// ランタイムで複合キー（catId:idx）へ解決する（インデックス直書きを避ける）。

export const TEMPLATES = [
  {
    id: "staples",
    name: "定番セット",
    desc: "どの作業でも使う基本",
    items: [
      { cat: "tools", label: "移動ツール" },
      { cat: "edit", label: "取り消し" },
      { cat: "edit", label: "やり直し" },
      { cat: "edit", label: "自由変形" },
      { cat: "layer", label: "レイヤーを複製／選択範囲をコピーしてレイヤー化" },
      { cat: "layer", label: "レイヤーをグループ化" },
      { cat: "layer", label: "新規レイヤー（ダイアログ表示）" },
      { cat: "tools", label: "ブラシ／鉛筆／色の置き換え／混合ブラシ" },
      { cat: "paint", label: "ブラシサイズを大きく" },
      { cat: "paint", label: "ブラシサイズを小さく" },
      { cat: "selection", label: "選択を解除" },
      { cat: "selection", label: "選択範囲を反転" },
      { cat: "view", label: "画面サイズに合わせる" },
      { cat: "tools", label: "描画色と背景色を入れ替え" },
      { cat: "file", label: "保存" },
    ],
  },
  {
    id: "retouch",
    name: "写真レタッチ",
    desc: "修復・色調補正中心",
    items: [
      { cat: "tools", label: "スポット修復／修復ブラシ／パッチ／赤目" },
      { cat: "tools", label: "コピースタンプ／パターンスタンプ" },
      { cat: "tools", label: "覆い焼き／焼き込み／スポンジ" },
      { cat: "tools", label: "切り抜き／遠近法の切り抜き／スライス" },
      { cat: "image", label: "レベル補正" },
      { cat: "image", label: "トーンカーブ" },
      { cat: "image", label: "色相・彩度" },
      { cat: "image", label: "彩度を下げる" },
      { cat: "image", label: "白黒" },
      { cat: "image", label: "画像解像度" },
      { cat: "layer", label: "レイヤーを複製／選択範囲をコピーしてレイヤー化" },
    ],
  },
  {
    id: "webui",
    name: "Webデザイン・UI",
    desc: "シェイプ・文字・整列中心",
    items: [
      { cat: "tools", label: "移動ツール" },
      { cat: "tools", label: "長方形／楕円形／多角形／ライン／カスタムシェイプ" },
      { cat: "tools", label: "横書き／縦書き文字ツール" },
      { cat: "layer", label: "レイヤーをグループ化" },
      { cat: "layer", label: "クリッピングマスクを作成／解除" },
      { cat: "layer", label: "レイヤーを複製／選択範囲をコピーしてレイヤー化" },
      { cat: "view", label: "ガイドの表示／非表示" },
      { cat: "view", label: "定規の表示／非表示" },
      { cat: "view", label: "ガイドにスナップ" },
      { cat: "edit", label: "自由変形" },
      { cat: "file", label: "別名で保存" },
    ],
  },
  {
    id: "paint",
    name: "イラスト・ペイント",
    desc: "ブラシ・レイヤー中心",
    items: [
      { cat: "tools", label: "ブラシ／鉛筆／色の置き換え／混合ブラシ" },
      { cat: "tools", label: "消しゴム／背景消しゴム／マジック消しゴム" },
      { cat: "paint", label: "ブラシサイズを大きく" },
      { cat: "paint", label: "ブラシサイズを小さく" },
      { cat: "paint", label: "ブラシの硬さを下げる" },
      { cat: "paint", label: "ブラシの硬さを上げる" },
      { cat: "tools", label: "描画色と背景色を入れ替え" },
      { cat: "tools", label: "描画色・背景色を初期化（白黒）" },
      { cat: "tools", label: "グラデーション／塗りつぶし" },
      { cat: "layer", label: "新規レイヤー（ダイアログ表示）" },
      { cat: "layer", label: "クリッピングマスクを作成／解除" },
      { cat: "edit", label: "取り消し" },
      { cat: "edit", label: "1 段階戻る（ヒストリー）" },
    ],
  },
];
