// Photoshop templates (English). Labels must match photoshop.en.js exactly.

export const TEMPLATES = [
  {
    id: "staples",
    name: "Essentials",
    desc: "Used in every workflow",
    items: [
      { cat: "tools", label: "Move tool" },
      { cat: "edit", label: "Undo" },
      { cat: "edit", label: "Redo" },
      { cat: "edit", label: "Free transform" },
      { cat: "layer", label: "New layer via copy / duplicate layer" },
      { cat: "layer", label: "Group layers" },
      { cat: "layer", label: "New layer (dialog)" },
      { cat: "tools", label: "Brush / Pencil / Color replacement / Mixer brush" },
      { cat: "paint", label: "Increase brush size" },
      { cat: "paint", label: "Decrease brush size" },
      { cat: "selection", label: "Deselect" },
      { cat: "selection", label: "Inverse selection" },
      { cat: "view", label: "Fit on screen" },
      { cat: "tools", label: "Swap fore/background colors" },
      { cat: "file", label: "Save" },
    ],
  },
  {
    id: "retouch",
    name: "Photo retouching",
    desc: "Healing & adjustments",
    items: [
      { cat: "tools", label: "Spot healing / Healing brush / Patch / Red eye" },
      { cat: "tools", label: "Clone stamp / Pattern stamp" },
      { cat: "tools", label: "Dodge / Burn / Sponge" },
      { cat: "tools", label: "Crop / Perspective crop / Slice" },
      { cat: "image", label: "Levels" },
      { cat: "image", label: "Curves" },
      { cat: "image", label: "Hue / Saturation" },
      { cat: "image", label: "Desaturate" },
      { cat: "image", label: "Black & white" },
      { cat: "image", label: "Image size" },
      { cat: "layer", label: "New layer via copy / duplicate layer" },
    ],
  },
  {
    id: "webui",
    name: "Web design / UI",
    desc: "Shapes, type, layout",
    items: [
      { cat: "tools", label: "Move tool" },
      { cat: "tools", label: "Rectangle / Ellipse / Polygon / Line / Custom shape" },
      { cat: "tools", label: "Horizontal / Vertical type" },
      { cat: "layer", label: "Group layers" },
      { cat: "layer", label: "Create / release clipping mask" },
      { cat: "layer", label: "New layer via copy / duplicate layer" },
      { cat: "view", label: "Show / hide guides" },
      { cat: "view", label: "Show / hide rulers" },
      { cat: "view", label: "Snap to guides" },
      { cat: "edit", label: "Free transform" },
      { cat: "file", label: "Save as" },
    ],
  },
  {
    id: "paint",
    name: "Illustration / Painting",
    desc: "Brushes & layers",
    items: [
      { cat: "tools", label: "Brush / Pencil / Color replacement / Mixer brush" },
      { cat: "tools", label: "Eraser / Background eraser / Magic eraser" },
      { cat: "paint", label: "Increase brush size" },
      { cat: "paint", label: "Decrease brush size" },
      { cat: "paint", label: "Decrease brush hardness" },
      { cat: "paint", label: "Increase brush hardness" },
      { cat: "tools", label: "Swap fore/background colors" },
      { cat: "tools", label: "Default fore/background colors (black & white)" },
      { cat: "tools", label: "Gradient / Paint bucket" },
      { cat: "layer", label: "New layer (dialog)" },
      { cat: "layer", label: "Create / release clipping mask" },
      { cat: "edit", label: "Undo" },
      { cat: "edit", label: "Step backward (history)" },
    ],
  },
];
