// 問題データ（読み解き型＝PHPコードを読んで出力を4択で当てる）
// Q1-6は記事版と同期・Q7-20はアプリ限定ドリル。出力はすべて PHP 8.x の実行結果で検証済み
const PROBLEMS = [
  {"id":1,"title":"echo と文字列の連結","questionHtml":"<code>.</code>（ドット）で文字列をつなぎます。このコードの出力はどれでしょう？",
   "code":"<?php\n$name = \"Taro\";\necho \"Hello, \" . $name . \"!\";",
   "choices":["Hello, Taro!","Hello, $name!","Hello, . Taro . !","エラーになる"],"answer":0,
   "explainHtml":"PHPの文字列連結は <code>+</code> ではなく <code>.</code> です。JavaScriptの感覚で <code>+</code> を書くと数値の足し算として扱われます。"},
  {"id":2,"title":"シングルクォートとダブルクォート","questionHtml":"同じ変数を2種類のクォートで囲んでいます。出力はどれでしょう？",
   "code":"<?php\n$item = \"りんご\";\necho '好物は$itemです';\necho \"\\n\";\necho \"好物は{$item}です\";",
   "choices":["好物はりんごです\n好物はりんごです","好物は$itemです\n好物はりんごです","好物は$itemです\n好物は{$item}です","好物はりんごです\n好物は$itemです"],"answer":1,
   "explainHtml":"変数が展開されるのは<strong>ダブルクォートの中だけ</strong>です。シングルクォートは書いた文字がそのまま出ます。<code>{$item}</code> の波かっこは、変数名の境目をはっきりさせる書き方です。"},
  {"id":3,"title":"割り算と余り","questionHtml":"3種類の割り算を並べています。出力はどれでしょう？",
   "code":"<?php\necho 7 / 2;\necho \"\\n\";\necho intdiv(7, 2);\necho \"\\n\";\necho 7 % 2;",
   "choices":["3\n3\n1","3.5\n3.5\n1","3.5\n3\n1","3.5\n4\n1"],"answer":2,
   "explainHtml":"<code>/</code> は割り切れなければ小数（3.5）を返します。整数の商がほしいときは <code>intdiv()</code>（切り捨てで3）、余りは <code>%</code>（1）です。"},
  {"id":4,"title":"if / elseif / else","questionHtml":"<code>$score</code> は 75 です。出力はどれでしょう？",
   "code":"<?php\n$score = 75;\nif ($score >= 80) {\n    echo \"A\";\n} elseif ($score >= 70) {\n    echo \"B\";\n} else {\n    echo \"C\";\n}",
   "choices":["A","BC","C","B"],"answer":3,
   "explainHtml":"上から順に条件を調べ、最初に当てはまった1つだけが実行されます。75は80未満・70以上なので <code>B</code> です。PHPでは <code>elseif</code>（1語）と <code>else if</code>（2語）のどちらも使えます。"},
  {"id":5,"title":"for 文","questionHtml":"繰り返しのたびに数字とカンマを出しています。出力はどれでしょう？",
   "code":"<?php\nfor ($i = 1; $i <= 3; $i++) {\n    echo $i . \",\";\n}",
   "choices":["1,2,3","1,2,3,","0,1,2,","1,2,"],"answer":1,
   "explainHtml":"<code>$i <= 3</code> なので3も含みます。カンマは毎回付けているので、最後の3の後ろにも残ります。末尾のカンマを消したいときは、配列に入れて <code>implode()</code> を使うのが定番です（Q13）。"},
  {"id":6,"title":"配列への追加と取り出し","questionHtml":"<code>[]</code> で末尾に追加してから、要素数と2番目の要素を出しています。出力はどれでしょう？",
   "code":"<?php\n$fruits = [\"apple\", \"banana\", \"grape\"];\n$fruits[] = \"melon\";\necho count($fruits) . \" \" . $fruits[1];",
   "choices":["3 apple","4 apple","4 banana","3 banana"],"answer":2,
   "explainHtml":"<code>$fruits[] = …</code> は末尾への追加（<code>array_push()</code> と同じ）です。要素数は <code>count()</code> で4。インデックスは0から数えるので <code>[1]</code> は2番目の banana です。"},

  {"id":7,"title":"日本語の文字数","questionHtml":"日本語5文字の文字数を2つの関数で数えています（文字コードはUTF-8）。出力はどれでしょう？",
   "code":"<?php\n$text = \"こんにちは\";\necho strlen($text) . \" / \" . mb_strlen($text);",
   "choices":["5 / 5","15 / 5","10 / 5","5 / 15"],"answer":1,
   "explainHtml":"<code>strlen()</code> は<strong>バイト数</strong>を返します。UTF-8の日本語は1文字3バイトなので15です。文字数を数えるなら <code>mb_strlen()</code>。抜粋の文字数制限などで取り違えやすい箇所です。"},
  {"id":8,"title":"== と ===","questionHtml":"文字列の \"10\" と数値の 10 を比べています。出力はどれでしょう？",
   "code":"<?php\nvar_dump(\"10\" == 10);\nvar_dump(\"10\" === 10);",
   "choices":["bool(true)\nbool(true)","bool(false)\nbool(false)","bool(false)\nbool(true)","bool(true)\nbool(false)"],"answer":3,
   "explainHtml":"<code>==</code> は型を合わせてから比べるので true、<code>===</code> は型まで一致しないと false です。フォームやURLから来る値はすべて文字列なので、比較には <code>===</code> を使うのが安全です。"},
  {"id":9,"title":"null合体演算子 ??","questionHtml":"存在するキーと存在しないキーを <code>??</code> で読んでいます。出力はどれでしょう？",
   "code":"<?php\n$user = [\"name\" => \"花子\"];\necho $user[\"name\"] ?? \"ゲスト\";\necho \" / \";\necho $user[\"email\"] ?? \"未登録\";",
   "choices":["花子 / 未登録","ゲスト / 未登録","花子 / ","エラーになる"],"answer":0,
   "explainHtml":"<code>??</code> は左側が<strong>存在しないか null のとき</strong>だけ右側を使います。存在しないキーを読んでも警告が出ないため、<code>$_GET</code> や設定値の読み出しでよく使います。"},
  {"id":10,"title":"switch と break","questionHtml":"<code>case \"sat\"</code> の中に <code>break</code> がありません。出力はどれでしょう？",
   "code":"<?php\n$day = \"sat\";\nswitch ($day) {\n    case \"sat\":\n        echo \"土\";\n    case \"sun\":\n        echo \"日\";\n        break;\n    default:\n        echo \"平日\";\n}",
   "choices":["土","土日","土日平日","平日"],"answer":1,
   "explainHtml":"<code>break</code> がないと、次の <code>case</code> の処理まで続けて実行されます（フォールスルー）。<code>sun</code> の <code>break</code> で止まるので「土日」です。"},
  {"id":11,"title":"match 式","questionHtml":"PHP 8 で入った <code>match</code> で分岐しています。出力はどれでしょう？",
   "code":"<?php\n$status = \"draft\";\necho match ($status) {\n    \"publish\" => \"公開中\",\n    \"draft\", \"pending\" => \"下書き\",\n    default => \"不明\",\n};",
   "choices":["公開中","不明","下書き","下書き不明"],"answer":2,
   "explainHtml":"<code>match</code> は当てはまった1つの値を返す式で、<code>switch</code> と違ってフォールスルーしません。カンマで複数の条件をまとめられ、比較は <code>===</code>（型も一致）で行われます。"},

  {"id":12,"title":"連想配列を foreach で回す","questionHtml":"キーと値を両方受け取るループです。出力はどれでしょう？",
   "code":"<?php\n$prices = [\"コーヒー\" => 400, \"紅茶\" => 350];\nforeach ($prices as $name => $price) {\n    echo \"{$name}:{$price}円\\n\";\n}",
   "choices":["400:コーヒー円\n350:紅茶円","0:400円\n1:350円","コーヒー:400円\n紅茶:350円","コーヒー:400円"],"answer":2,
   "explainHtml":"<code>foreach ($配列 as $キー => $値)</code> の形で、キーと値を同時に受け取れます。値だけでよければ <code>foreach ($prices as $price)</code> と書きます。"},
  {"id":13,"title":"explode と implode","questionHtml":"カンマ区切りの文字列を配列にして、別の区切りで戻しています。出力はどれでしょう？",
   "code":"<?php\n$tags = explode(\",\", \"html,css,php\");\necho count($tags) . \"\\n\";\necho implode(\" / \", $tags);",
   "choices":["1\nhtml,css,php","3\nhtml / css / php","3\nhtml,css,php","3\n / html / css / php"],"answer":1,
   "explainHtml":"<code>explode()</code> は区切り文字で分割して配列にし、<code>implode()</code> は配列を区切り文字でつないで文字列に戻します。JavaScriptの <code>split()</code> と <code>join()</code> に当たります。"},
  {"id":14,"title":"array_filter はキーを残す","questionHtml":"偶数だけを取り出して <code>print_r()</code> で中身を表示しています。出力はどれでしょう？",
   "code":"<?php\n$nums = [1, 2, 3, 4, 5];\n$evens = array_filter($nums, fn($n) => $n % 2 === 0);\nprint_r($evens);",
   "choices":["Array\n(\n    [0] => 2\n    [1] => 4\n)","Array\n(\n    [0] => 1\n    [1] => 3\n    [2] => 5\n)","Array\n(\n    [1] => 2\n    [3] => 4\n)","Array\n(\n    [2] => 2\n    [4] => 4\n)"],"answer":2,
   "explainHtml":"<code>array_filter()</code> は<strong>元のキーをそのまま残します</strong>。2と4は元の配列の [1] と [3] にあったので、キーも1と3です。0から振り直したいときは <code>array_values()</code> で包みます。"},
  {"id":15,"title":"sort() の戻り値","questionHtml":"並び替えた結果を変数に入れたつもりのコードです。出力はどれでしょう？",
   "code":"<?php\n$nums = [3, 1, 2];\n$result = sort($nums);\nvar_dump($result);\necho implode(\",\", $nums);",
   "choices":["bool(true)\n1,2,3","bool(true)\n3,1,2","array(3)\n1,2,3","NULL\n1,2,3"],"answer":0,
   "explainHtml":"<code>sort()</code> は<strong>元の配列そのものを並び替え</strong>、戻り値は成功したかどうか（true）です。並び替えた配列が返ってくるわけではありません。JavaScriptの <code>sort()</code> とはここが違います。"},
  {"id":16,"title":"isset と array_key_exists","questionHtml":"値が null のキーを2つの方法で調べています。出力はどれでしょう？",
   "code":"<?php\n$post = [\"title\" => \"お知らせ\", \"thumbnail\" => null];\nvar_dump(isset($post[\"thumbnail\"]));\nvar_dump(array_key_exists(\"thumbnail\", $post));",
   "choices":["bool(true)\nbool(true)","bool(false)\nbool(true)","bool(true)\nbool(false)","bool(false)\nbool(false)"],"answer":1,
   "explainHtml":"<code>isset()</code> は値が null だと false を返します。キーがあるかどうかだけを知りたいときは <code>array_key_exists()</code> を使います。「未設定」と「空で設定済み」を区別したい場面で効いてきます。"},

  {"id":17,"title":"関数の引数の初期値","questionHtml":"2つ目の引数に初期値を持つ関数を2回呼んでいます。出力はどれでしょう？",
   "code":"<?php\nfunction greet($name, $greeting = \"こんにちは\") {\n    return \"{$greeting}、{$name}さん\";\n}\necho greet(\"佐藤\") . \"\\n\";\necho greet(\"鈴木\", \"おはよう\");",
   "choices":["こんにちは、佐藤さん\nこんにちは、鈴木さん","こんにちは、佐藤さん\nおはよう、鈴木さん","、佐藤さん\nおはよう、鈴木さん","エラーになる"],"answer":1,
   "explainHtml":"引数に <code>= 値</code> を書くと、省略したときにその値が使われます。渡したときは渡した値が優先されます。WordPressの関数（<code>get_the_title()</code> など）も、ほとんどの引数に初期値があるので省略して呼べます。"},
  {"id":18,"title":"値渡しと参照渡し","questionHtml":"<code>&</code> の有無だけが違う2つの関数に、同じ変数を渡しています。出力はどれでしょう？",
   "code":"<?php\nfunction addOne($n) {\n    $n++;\n    return $n;\n}\nfunction addOneRef(&$n) {\n    $n++;\n}\n$a = 1;\naddOne($a);\naddOneRef($a);\necho $a;",
   "choices":["1","2","3","4"],"answer":1,
   "explainHtml":"通常の引数は<strong>コピー</strong>が渡されるので、<code>addOne()</code> の中で増やしても <code>$a</code> は変わりません（戻り値も捨てています）。<code>&</code> を付けた <code>addOneRef()</code> だけが元の変数を書き換えるので、結果は2です。"},
  {"id":19,"title":"htmlspecialchars でエスケープ","questionHtml":"ユーザーの入力をエスケープして出力しています。ブラウザに送られる<strong>HTMLソース</strong>はどれでしょう？",
   "code":"<?php\n$input = '<b>太字</b>';\necho htmlspecialchars($input);",
   "choices":["<b>太字</b>","太字","&lt;b&gt;太字&lt;/b&gt;","&amp;lt;b&amp;gt;太字&amp;lt;/b&amp;gt;"],"answer":2,
   "explainHtml":"<code>&lt;</code> <code>&gt;</code> などが文字参照に置き換わるので、ブラウザではタグにならず「&lt;b&gt;太字&lt;/b&gt;」という文字のまま表示されます。WordPressの <code>esc_html()</code> も同じ役割で、XSS対策の基本です。"},
  {"id":20,"title":"総合：テンプレートの読み解き","questionHtml":"WordPressのテーマでよく見る、HTMLとPHPが混ざった書き方です。出力されるHTMLはどれでしょう？",
   "code":"<?php $posts = [\n    [\"title\" => \"新商品のお知らせ\", \"cat\" => \"news\"],\n    [\"title\" => \"臨時休業\", \"cat\" => \"info\"],\n    [\"title\" => \"セール開催\", \"cat\" => \"news\"],\n]; ?>\n<ul>\n<?php foreach ($posts as $post): ?>\n<?php if ($post[\"cat\"] !== \"news\") continue; ?>\n  <li><?= $post[\"title\"] ?></li>\n<?php endforeach; ?>\n</ul>",
   "choices":["<ul>\n  <li>新商品のお知らせ</li>\n  <li>臨時休業</li>\n  <li>セール開催</li>\n</ul>","<ul>\n  <li>臨時休業</li>\n</ul>","<ul>\n  <li>新商品のお知らせ</li>\n</ul>","<ul>\n  <li>新商品のお知らせ</li>\n  <li>セール開催</li>\n</ul>"],"answer":3,
   "explainHtml":"<code>foreach (…):</code> 〜 <code>endforeach;</code> は波かっこの代わりに使う書き方で、HTMLに埋め込むときに読みやすくなります。<code>continue</code> で news 以外を飛ばし、<code>&lt;?= … ?&gt;</code> は <code>&lt;?php echo … ?&gt;</code> の短縮形です。"}
];

const LEVELS = [
  { key: 'all', label: 'すべて (20問)', range: [1, 20] },
  { key: 'basic', label: '基礎 1-6', range: [1, 6] },
  { key: 'mid', label: '文字列・比較 7-11', range: [7, 11] },
  { key: 'data', label: '配列 12-16', range: [12, 16] },
  { key: 'adv', label: '関数・テンプレート 17-20', range: [17, 20] },
];
