// 問題データ（Q1-5は記事版 id751 と同期・Q6-24はアプリ限定ドリル）
// stageHtml: プレビューに描画する固定HTML／starter・answer: エディタに書くCSS
// preferSp: 既定でSP幅（375px）プレビューにする問題（メディアクエリ等）
const PROBLEMS = [
  {"id": 1, "title": "テキストの色を変える", "questionHtml": "<code>.text</code> の文字色を<strong>青</strong>にしてください。色は色名・16進数（<code>#0000ff</code>）・<code>rgb()</code> のどれでも指定できます。", "stageHtml": "<div class=\"text\">CSSで色を変えてみよう！</div>", "starter": ".text {\n  \n}\n", "answer": ".text {\n  color: blue;\n}\n"},
  {"id": 2, "title": "背景色と大きさ", "questionHtml": "<code>.box</code> の背景色を<strong>薄いグレー（#f0f0f0）</strong>にし、幅と高さをそれぞれ <strong>100px</strong> にしてください。", "stageHtml": "<div class=\"box\">ボックスのスタイルを変更しよう！</div>", "starter": ".box {\n  \n}\n", "answer": ".box {\n  background-color: #f0f0f0;\n  width: 100px;\n  height: 100px;\n}\n"},
  {"id": 3, "title": "テキストを縦横中央に置く", "questionHtml": "<code>.center-box</code> の中のテキストを<strong>縦にも横にも中央</strong>へ置いてください。<code>display: flex</code> と <code>align-items</code>・<code>justify-content</code> を組み合わせます。", "stageHtml": "<div class=\"center-box\">中央揃え</div>", "starter": ".center-box {\n  width: 200px;\n  height: 200px;\n  border: 1px solid #000;\n  \n}\n", "answer": ".center-box {\n  width: 200px;\n  height: 200px;\n  border: 1px solid #000;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}\n"},
  {"id": 4, "title": "メディアクエリで切り替える", "questionHtml": "画面幅が <strong>768px以下</strong> のとき、<code>.responsive</code> の背景色を<strong>薄い青（#e0f7fa）</strong>に変えてください。<strong>プレビューの幅を「SP」に切り替える</strong>と効き目を確認できます。", "stageHtml": "<div class=\"responsive\">ウィンドウを縮小して確認しよう！</div>", "starter": ".responsive {\n  padding: 24px;\n  background-color: #eeeeee;\n}\n", "answer": ".responsive {\n  padding: 24px;\n  background-color: #eeeeee;\n}\n\n@media (max-width: 768px) {\n  .responsive {\n    background-color: #e0f7fa;\n  }\n}\n", "preferSp": true},
  {"id": 5, "title": "枠線とボックスの間隔", "questionHtml": "3つのボックスに<strong>赤・2pxの実線</strong>の枠線を付け、ボックスとボックスの<strong>間を10px</strong>空けてください。", "stageHtml": "<div class=\"box-list\">\n  <div class=\"box-item\">1</div>\n  <div class=\"box-item\">2</div>\n  <div class=\"box-item\">3</div>\n</div>", "starter": ".box-list {\n  display: flex;\n  \n}\n\n.box-item {\n  width: 50px;\n  height: 50px;\n  text-align: center;\n  line-height: 50px;\n  \n}\n", "answer": ".box-list {\n  display: flex;\n  gap: 10px;\n}\n\n.box-item {\n  width: 50px;\n  height: 50px;\n  text-align: center;\n  line-height: 50px;\n  border: 2px solid red;\n}\n"},
  {"id": 6, "title": "文字の大きさ・太さ・行間", "questionHtml": "見出しを <strong>24px・太字</strong>に、本文を <strong>16px・行間1.8</strong>にしてください（<code>font-size</code> / <code>font-weight</code> / <code>line-height</code>）。", "stageHtml": "<h2 class=\"ttl\">CSSの基礎</h2>\n<p class=\"body\">行間が詰まっていると読みにくくなります。適切な行間をとると、文章はぐっと読みやすくなります。</p>", "starter": ".ttl {\n  \n}\n\n.body {\n  \n}\n", "answer": ".ttl {\n  font-size: 24px;\n  font-weight: bold;\n}\n\n.body {\n  font-size: 16px;\n  line-height: 1.8;\n}\n"},
  {"id": 7, "title": "padding と margin の違い", "questionHtml": "<code>.card</code> の<strong>内側に20px</strong>の余白（<code>padding</code>）を、<strong>外側に32px</strong>の余白（<code>margin</code>）を付けてください。背景色が付いている範囲がどう変わるかを見比べます。", "stageHtml": "<div class=\"card\">内と外、どちらの余白が広がる？</div>", "starter": ".card {\n  background-color: #ffe9c7;\n  \n}\n", "answer": ".card {\n  background-color: #ffe9c7;\n  padding: 20px;\n  margin: 32px;\n}\n"},
  {"id": 8, "title": "box-sizing で幅の数え方を変える", "questionHtml": "2つのボックスはどちらも <code>width: 200px</code> ですが、padding と border の分だけ実際は広がっています。<code>.after</code> だけに <strong><code>box-sizing: border-box</code></strong> を付けて、<strong>見た目の幅をちょうど200px</strong>にしてください。", "stageHtml": "<div class=\"before\">border-box なし</div>\n<div class=\"after\">border-box あり</div>", "starter": ".before,\n.after {\n  width: 200px;\n  padding: 20px;\n  border: 5px solid #333;\n  background-color: #d8ecff;\n  margin-bottom: 12px;\n}\n\n.after {\n  \n}\n", "answer": ".before,\n.after {\n  width: 200px;\n  padding: 20px;\n  border: 5px solid #333;\n  background-color: #d8ecff;\n  margin-bottom: 12px;\n}\n\n.after {\n  box-sizing: border-box;\n}\n"},
  {"id": 9, "title": "角丸と影を付ける", "questionHtml": "<code>.panel</code> に<strong>12pxの角丸</strong>と、<strong>下方向へ少しだけ落ちる影</strong>を付けてカードらしくしてください（<code>border-radius</code> / <code>box-shadow</code>）。", "stageHtml": "<div class=\"panel\">カード風のパネル</div>", "starter": ".panel {\n  width: 240px;\n  padding: 24px;\n  background-color: #ffffff;\n  \n}\n", "answer": ".panel {\n  width: 240px;\n  padding: 24px;\n  background-color: #ffffff;\n  border-radius: 12px;\n  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\n}\n"},
  {"id": 10, "title": "リンクの見た目を整える", "questionHtml": "リンクの<strong>下線を消し</strong>、色を <strong>#0b6bcb</strong> にしてください。さらに<strong>マウスを乗せたときだけ</strong>下線を出します（<code>:hover</code>）。", "stageHtml": "<p>詳しくは<a class=\"link\" href=\"#\">こちらのページ</a>をご覧ください。</p>", "starter": ".link {\n  \n}\n", "answer": ".link {\n  color: #0b6bcb;\n  text-decoration: none;\n}\n\n.link:hover {\n  text-decoration: underline;\n}\n"},
  {"id": 11, "title": "背景画像を敷く", "questionHtml": "<code>.hero</code> の背景に画像を敷いてください。<strong>全体を覆い（cover）・中央寄せ・繰り返さない</strong>の3点を指定します。画像URLは <code>https://picsum.photos/id/1015/800/400</code> を使います。", "stageHtml": "<div class=\"hero\"><span>Hero Area</span></div>", "starter": ".hero {\n  height: 200px;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  color: #ffffff;\n  font-size: 24px;\n  \n}\n", "answer": ".hero {\n  height: 200px;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  color: #ffffff;\n  font-size: 24px;\n  background-image: url(\"https://picsum.photos/id/1015/800/400\");\n  background-size: cover;\n  background-position: center;\n  background-repeat: no-repeat;\n}\n"},
  {"id": 12, "title": "セレクタを使い分ける", "questionHtml": "3種類のセレクタを1つずつ使ってください。①<strong>すべての <code>p</code></strong> の文字色を <code>#555</code>、②<strong><code>class=\"note\"</code></strong> の背景を <code>#fff6d6</code>、③<strong><code>id=\"lead\"</code></strong> の文字を太字にします。", "stageHtml": "<p id=\"lead\">これはリード文です。</p>\n<p>これは普通の段落です。</p>\n<p class=\"note\">これは補足です。</p>", "starter": "\n", "answer": "p {\n  color: #555;\n}\n\n.note {\n  background-color: #fff6d6;\n}\n\n#lead {\n  font-weight: bold;\n}\n"},
  {"id": 13, "title": "何番目かで指定する", "questionHtml": "リストの<strong>最初の項目</strong>を太字に、<strong>最後の項目</strong>の文字色を <code>#c00</code> に、<strong>偶数番目の項目</strong>の背景を <code>#f2f2f2</code> にしてください（<code>:first-child</code> / <code>:last-child</code> / <code>:nth-child(even)</code>）。", "stageHtml": "<ul class=\"menu\">\n  <li>ホーム</li>\n  <li>サービス</li>\n  <li>実績</li>\n  <li>会社概要</li>\n  <li>お問い合わせ</li>\n</ul>", "starter": ".menu li {\n  padding: 6px 10px;\n  list-style: none;\n}\n", "answer": ".menu li {\n  padding: 6px 10px;\n  list-style: none;\n}\n\n.menu li:first-child {\n  font-weight: bold;\n}\n\n.menu li:last-child {\n  color: #c00;\n}\n\n.menu li:nth-child(even) {\n  background-color: #f2f2f2;\n}\n"},
  {"id": 14, "title": "Flexbox で横に並べる", "questionHtml": "3つのボックスを<strong>横一列</strong>に並べ、<strong>左右の端に寄せて等間隔</strong>にし、<strong>高さは中央揃え</strong>にしてください（<code>flex-direction</code> / <code>justify-content</code> / <code>align-items</code>）。", "stageHtml": "<div class=\"row\">\n  <div class=\"item tall\">A</div>\n  <div class=\"item\">B</div>\n  <div class=\"item\">C</div>\n</div>", "starter": ".row {\n  height: 160px;\n  border: 1px dashed #999;\n  display: flex;\n  \n}\n\n.item {\n  background-color: #cfe8ff;\n  padding: 12px 20px;\n}\n\n.tall {\n  padding-top: 40px;\n  padding-bottom: 40px;\n}\n", "answer": ".row {\n  height: 160px;\n  border: 1px dashed #999;\n  display: flex;\n  flex-direction: row;\n  justify-content: space-between;\n  align-items: center;\n}\n\n.item {\n  background-color: #cfe8ff;\n  padding: 12px 20px;\n}\n\n.tall {\n  padding-top: 40px;\n  padding-bottom: 40px;\n}\n"},
  {"id": 15, "title": "折り返しと伸び縮み", "questionHtml": "カードを<strong>入りきらなければ折り返す</strong>ようにし（<code>flex-wrap</code>）、<strong>間隔を16px</strong>空け、<strong>各カードが余ったぶんを均等に分け合う</strong>ようにしてください（<code>flex: 1</code>）。カードの最小幅は <code>flex-basis</code> で 160px にします。", "stageHtml": "<div class=\"cards\">\n  <div class=\"c\">カード1</div>\n  <div class=\"c\">カード2</div>\n  <div class=\"c\">カード3</div>\n  <div class=\"c\">カード4</div>\n</div>", "starter": ".cards {\n  display: flex;\n  \n}\n\n.c {\n  background-color: #e6f4ea;\n  padding: 20px;\n  text-align: center;\n  \n}\n", "answer": ".cards {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 16px;\n}\n\n.c {\n  background-color: #e6f4ea;\n  padding: 20px;\n  text-align: center;\n  flex: 1 1 160px;\n}\n"},
  {"id": 16, "title": "Grid で格子に並べる", "questionHtml": "6つのセルを <strong>3列</strong>の格子に並べ、<strong>間隔を12px</strong>空けてください。列幅は <code>1fr</code> を使って等分します。", "stageHtml": "<div class=\"grid\">\n  <div class=\"g\">1</div>\n  <div class=\"g\">2</div>\n  <div class=\"g\">3</div>\n  <div class=\"g\">4</div>\n  <div class=\"g\">5</div>\n  <div class=\"g\">6</div>\n</div>", "starter": ".grid {\n  \n}\n\n.g {\n  background-color: #ffe0e6;\n  padding: 24px;\n  text-align: center;\n}\n", "answer": ".grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 12px;\n}\n\n.g {\n  background-color: #ffe0e6;\n  padding: 24px;\n  text-align: center;\n}\n"},
  {"id": 17, "title": "Grid でページの骨組みを作る", "questionHtml": "<code>grid-template-areas</code> を使って、<strong>上にヘッダー・左にサイドバー・右にメイン・下にフッター</strong>の形に組んでください。サイドバーの幅は <strong>160px</strong>、メインは残り全部（<code>1fr</code>）です。", "stageHtml": "<div class=\"layout\">\n  <div class=\"hd\">header</div>\n  <div class=\"sd\">side</div>\n  <div class=\"mn\">main</div>\n  <div class=\"ft\">footer</div>\n</div>", "starter": ".layout {\n  display: grid;\n  gap: 8px;\n  \n}\n\n.layout > div {\n  background-color: #dbe4ff;\n  padding: 16px;\n  text-align: center;\n}\n", "answer": ".layout {\n  display: grid;\n  gap: 8px;\n  grid-template-columns: 160px 1fr;\n  grid-template-areas:\n    \"hd hd\"\n    \"sd mn\"\n    \"ft ft\";\n}\n\n.hd { grid-area: hd; }\n.sd { grid-area: sd; }\n.mn { grid-area: mn; }\n.ft { grid-area: ft; }\n\n.layout > div {\n  background-color: #dbe4ff;\n  padding: 16px;\n  text-align: center;\n}\n"},
  {"id": 18, "title": "要素を好きな位置に置く", "questionHtml": "商品カードの<strong>右上に「NEW」バッジ</strong>を重ねてください。親に <code>position: relative</code>、バッジに <code>position: absolute</code> を指定し、<code>top</code> と <code>right</code> で位置を決めます。", "stageHtml": "<div class=\"product\">\n  <span class=\"badge\">NEW</span>\n  <p>商品名</p>\n</div>", "starter": ".product {\n  width: 200px;\n  padding: 24px;\n  background-color: #f5f5f5;\n  \n}\n\n.badge {\n  background-color: #c00;\n  color: #fff;\n  padding: 4px 10px;\n  \n}\n", "answer": ".product {\n  width: 200px;\n  padding: 24px;\n  background-color: #f5f5f5;\n  position: relative;\n}\n\n.badge {\n  background-color: #c00;\n  color: #fff;\n  padding: 4px 10px;\n  position: absolute;\n  top: 8px;\n  right: 8px;\n}\n"},
  {"id": 19, "title": "重なりの順番を変える", "questionHtml": "いま<strong>青が赤の上</strong>に乗っています。<code>z-index</code> を使って<strong>赤を一番上</strong>に持ってきてください（<code>position</code> が付いていないと <code>z-index</code> は効きません）。", "stageHtml": "<div class=\"stack\">\n  <div class=\"red\">red</div>\n  <div class=\"blue\">blue</div>\n</div>", "starter": ".stack {\n  position: relative;\n  height: 160px;\n}\n\n.red,\n.blue {\n  position: absolute;\n  width: 120px;\n  height: 120px;\n  color: #fff;\n  padding: 8px;\n}\n\n.red {\n  background-color: #d33;\n  top: 0;\n  left: 0;\n  \n}\n\n.blue {\n  background-color: #36c;\n  top: 30px;\n  left: 40px;\n}\n", "answer": ".stack {\n  position: relative;\n  height: 160px;\n}\n\n.red,\n.blue {\n  position: absolute;\n  width: 120px;\n  height: 120px;\n  color: #fff;\n  padding: 8px;\n}\n\n.red {\n  background-color: #d33;\n  top: 0;\n  left: 0;\n  z-index: 1;\n}\n\n.blue {\n  background-color: #36c;\n  top: 30px;\n  left: 40px;\n}\n"},
  {"id": 20, "title": "動きをなめらかにする", "questionHtml": "ボタンに<strong>マウスを乗せたら少し大きくなり、色が濃くなる</strong>ようにしてください。変化は <code>transition</code> で <strong>0.2秒かけて</strong>なめらかにします（拡大は <code>transform: scale()</code>）。", "stageHtml": "<button class=\"btn\">送信する</button>", "starter": ".btn {\n  font-size: 16px;\n  padding: 12px 28px;\n  border: none;\n  border-radius: 6px;\n  background-color: #4a90d9;\n  color: #fff;\n  cursor: pointer;\n  \n}\n", "answer": ".btn {\n  font-size: 16px;\n  padding: 12px 28px;\n  border: none;\n  border-radius: 6px;\n  background-color: #4a90d9;\n  color: #fff;\n  cursor: pointer;\n  transition: transform 0.2s, background-color 0.2s;\n}\n\n.btn:hover {\n  transform: scale(1.08);\n  background-color: #2f6ea8;\n}\n"},
  {"id": 21, "title": "色を変数にまとめる", "questionHtml": "同じ色が3か所に散らばっています。<strong>CSS変数</strong>にまとめて、<code>:root</code> で <code>--brand</code> を1回だけ定義し、各所から <code>var(--brand)</code> で参照してください。変数の値を変えるだけで3か所とも変わる状態にします。", "stageHtml": "<h2 class=\"t\">見出し</h2>\n<p class=\"line\">区切り線の色も揃えます</p>\n<button class=\"b\">ボタン</button>", "starter": ".t {\n  color: #7b4bd8;\n}\n\n.line {\n  border-bottom: 3px solid #7b4bd8;\n  padding-bottom: 8px;\n}\n\n.b {\n  font-size: 16px;\n  padding: 10px 24px;\n  border: none;\n  color: #fff;\n  background-color: #7b4bd8;\n}\n", "answer": ":root {\n  --brand: #7b4bd8;\n}\n\n.t {\n  color: var(--brand);\n}\n\n.line {\n  border-bottom: 3px solid var(--brand);\n  padding-bottom: 8px;\n}\n\n.b {\n  font-size: 16px;\n  padding: 10px 24px;\n  border: none;\n  color: #fff;\n  background-color: var(--brand);\n}\n"},
  {"id": 22, "title": "メディアクエリを使わずに可変にする", "questionHtml": "見出しの文字サイズを <code>clamp()</code> で<strong>最小20px・最大40px</strong>の間で画面幅に応じて変わるようにしてください（真ん中の値には <code>vw</code> を含めます）。<strong>プレビューの幅をPCとSPで切り替える</strong>と変化が見えます。", "stageHtml": "<h2 class=\"fluid\">画面幅で伸び縮みする見出し</h2>", "starter": ".fluid {\n  \n}\n", "answer": ".fluid {\n  font-size: clamp(20px, 4vw + 8px, 40px);\n}\n"},
  {"id": 23, "title": "カードを1枚仕上げる", "questionHtml": "ここまでの内容を使って、<strong>画像・見出し・本文が縦に並んだカード</strong>を仕上げてください。<strong>幅280px・角丸・影・内側の余白・画像は幅いっぱい</strong>を満たします。", "stageHtml": "<div class=\"pcard\">\n  <img class=\"pimg\" src=\"https://picsum.photos/id/1025/560/320\" alt=\"サンプル画像\" width=\"560\" height=\"320\">\n  <div class=\"pbody\">\n    <h3 class=\"ptitle\">カードのタイトル</h3>\n    <p class=\"ptext\">説明文がここに入ります。</p>\n  </div>\n</div>", "starter": ".pcard {\n  \n}\n\n.pimg {\n  \n}\n\n.pbody {\n  \n}\n", "answer": ".pcard {\n  width: 280px;\n  border-radius: 12px;\n  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);\n  overflow: hidden;\n  background-color: #fff;\n}\n\n.pimg {\n  display: block;\n  width: 100%;\n  height: auto;\n}\n\n.pbody {\n  padding: 16px 20px 20px;\n}\n"},
  {"id": 24, "title": "総仕上げ：ナビとカード一覧", "questionHtml": "ページの上部を仕上げてください。①<strong>ナビは横並び・右寄せ・間隔24px・下線なし</strong>、②<strong>カードは3列のGrid・間隔16px</strong>（画面が狭いときは1列）、③<strong>各カードは角丸・影・内側20px</strong>。<strong>プレビューをSPに切り替えて1列になるか</strong>も確認します。", "stageHtml": "<nav class=\"nav\">\n  <a href=\"#\">ホーム</a>\n  <a href=\"#\">サービス</a>\n  <a href=\"#\">お問い合わせ</a>\n</nav>\n\n<div class=\"list\">\n  <div class=\"card3\"><h3>カード1</h3><p>説明が入ります。</p></div>\n  <div class=\"card3\"><h3>カード2</h3><p>説明が入ります。</p></div>\n  <div class=\"card3\"><h3>カード3</h3><p>説明が入ります。</p></div>\n</div>", "starter": ".nav {\n  \n}\n\n.nav a {\n  \n}\n\n.list {\n  \n}\n\n.card3 {\n  background-color: #fff;\n  \n}\n", "answer": ".nav {\n  display: flex;\n  justify-content: flex-end;\n  gap: 24px;\n  margin-bottom: 24px;\n}\n\n.nav a {\n  color: #333;\n  text-decoration: none;\n}\n\n.nav a:hover {\n  text-decoration: underline;\n}\n\n.list {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 16px;\n}\n\n@media (max-width: 600px) {\n  .list {\n    grid-template-columns: 1fr;\n  }\n}\n\n.card3 {\n  background-color: #fff;\n  border-radius: 12px;\n  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.12);\n  padding: 20px;\n}\n"},
];

const LEVELS = [
  {"key": "all", "label": "すべて (24問)", "range": [1, 24]},
  {"key": "article", "label": "記事同期 1-5", "range": [1, 5]},
  {"key": "basic", "label": "見た目の基本 6-13", "range": [6, 13]},
  {"key": "layout", "label": "レイアウト 14-19", "range": [14, 19]},
  {"key": "practice", "label": "実践 20-24", "range": [20, 24]},
];
