// 定番のアイコン変形（10種）
// 各エフェクトは self-contained（HTML + CSS + 開閉用の3行JS）でそのままコピペできる
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する
// 開閉状態は button の aria-expanded="true" で表現する（CSSのクラス切替は使わない）

const BARS = "<span></span><span></span><span></span>";

export const BASIC_ICONS = [
  {
    key: "hb-cross",
    mode: "icon",
    cat: "basic",
    label: { ja: "クロス（定番）", en: "Cross (classic)" },
    html: '<button class="hb-cross" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-cross {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-cross span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease, opacity 0.3s ease;",
      "}",
      ".hb-cross span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-cross span:nth-child(3) { transform: translateY(9px); }",
      '.hb-cross[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-cross[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-cross[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-scale",
    mode: "icon",
    cat: "basic",
    label: { ja: "中央が縮んで消える", en: "Middle bar shrinks away" },
    html: '<button class="hb-scale" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-scale {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-scale span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease;",
      "}",
      ".hb-scale span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-scale span:nth-child(3) { transform: translateY(9px); }",
      '.hb-scale[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-scale[aria-expanded="true"] span:nth-child(2) { transform: scaleX(0); }',
      '.hb-scale[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-slidemid",
    mode: "icon",
    cat: "basic",
    label: { ja: "中央が左へ滑って消える", en: "Middle bar slides out left" },
    html: '<button class="hb-slidemid" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-slidemid {",
      "  position: relative; width: 48px; height: 48px; padding: 0; overflow: hidden;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-slidemid span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.25s ease;",
      "}",
      ".hb-slidemid span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-slidemid span:nth-child(3) { transform: translateY(9px); }",
      '.hb-slidemid[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-slidemid[aria-expanded="true"] span:nth-child(2) { transform: translateX(-40px); opacity: 0; }',
      '.hb-slidemid[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-squeeze",
    mode: "icon",
    cat: "basic",
    label: { ja: "スクイーズ（寄ってから回る）", en: "Squeeze (gather, then rotate)" },
    html: '<button class="hb-squeeze" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-squeeze {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-squeeze span {",
      "  position: absolute; left: 9px; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "}",
      "/* 閉じる時は「回転→広がる」、開く時は「寄る→回転」の順になるよう delay を反転させる */",
      ".hb-squeeze span { transition: top 0.2s ease 0.2s, transform 0.2s ease, opacity 0.2s ease 0.2s; }",
      ".hb-squeeze span:nth-child(1) { top: calc(50% - 9px); }",
      ".hb-squeeze span:nth-child(2) { top: 50%; }",
      ".hb-squeeze span:nth-child(3) { top: calc(50% + 9px); }",
      '.hb-squeeze[aria-expanded="true"] span { transition: top 0.2s ease, transform 0.2s ease 0.2s, opacity 0.2s ease; }',
      '.hb-squeeze[aria-expanded="true"] span:nth-child(1) { top: 50%; transform: rotate(45deg); }',
      '.hb-squeeze[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-squeeze[aria-expanded="true"] span:nth-child(3) { top: 50%; transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-fade",
    mode: "icon",
    cat: "basic",
    label: { ja: "フェードで×に入れ替わる", en: "Cross-fade into ×" },
    html: '<button class="hb-fade" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-fade {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-fade span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.25s ease, opacity 0.25s ease;",
      "}",
      ".hb-fade span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-fade span:nth-child(3) { transform: translateY(9px); }",
      "/* ×の2本は擬似要素。3本線が消えるのを待って現れる */",
      ".hb-fade::before,",
      ".hb-fade::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px; opacity: 0;",
      "  transition: transform 0.25s ease 0.12s, opacity 0.25s ease 0.12s;",
      "}",
      ".hb-fade::before { transform: rotate(45deg) scale(0.4); }",
      ".hb-fade::after { transform: rotate(-45deg) scale(0.4); }",
      '.hb-fade[aria-expanded="true"] span { opacity: 0; transform: translateY(0) scale(0.4); transition-delay: 0s; }',
      '.hb-fade[aria-expanded="true"]::before { opacity: 1; transform: rotate(45deg) scale(1); }',
      '.hb-fade[aria-expanded="true"]::after { opacity: 1; transform: rotate(-45deg) scale(1); }',
    ],
  },
  {
    key: "hb-elastic",
    mode: "icon",
    cat: "basic",
    label: { ja: "弾む×", en: "Elastic cross" },
    html: '<button class="hb-elastic" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-elastic {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-elastic span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.45s cubic-bezier(0.68, -0.6, 0.27, 1.6), opacity 0.2s ease;",
      "}",
      ".hb-elastic span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-elastic span:nth-child(3) { transform: translateY(9px); }",
      '.hb-elastic[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-elastic[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-elastic[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-crossrev",
    mode: "icon",
    cat: "basic",
    label: { ja: "逆向きの×", en: "Reversed cross" },
    html: '<button class="hb-crossrev" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-crossrev {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-crossrev span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.25s ease, background 0.35s ease;",
      "}",
      ".hb-crossrev span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-crossrev span:nth-child(3) { transform: translateY(9px); }",
      '.hb-crossrev[aria-expanded="true"] span { background: #ec4899; }',
      '.hb-crossrev[aria-expanded="true"] span:nth-child(1) { transform: rotate(-45deg); }',
      '.hb-crossrev[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-crossrev[aria-expanded="true"] span:nth-child(3) { transform: rotate(45deg); }',
    ],
  },
  {
    key: "hb-plus",
    mode: "icon",
    cat: "basic",
    label: { ja: "プラス（＋）になる", en: "Turns into a plus" },
    html: '<button class="hb-plus" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-plus {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-plus span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.25s ease;",
      "}",
      ".hb-plus span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-plus span:nth-child(3) { transform: translateY(9px); }",
      "/* 1本目が中央へ移動しながら縦になり、3本目は消えて ＋ が残る */",
      '.hb-plus[aria-expanded="true"] span:nth-child(1) { transform: rotate(90deg); }',
      '.hb-plus[aria-expanded="true"] span:nth-child(3) { transform: translateY(0) scaleX(0); opacity: 0; }',
    ],
  },
  {
    key: "hb-thin",
    mode: "icon",
    cat: "basic",
    label: { ja: "細くなりながら×", en: "Thins out into ×" },
    html: '<button class="hb-thin" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-thin {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-thin span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 4px; margin-top: -2px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.25s ease, height 0.35s ease, margin-top 0.35s ease;",
      "}",
      ".hb-thin span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-thin span:nth-child(3) { transform: translateY(9px); }",
      '.hb-thin[aria-expanded="true"] span { height: 2px; margin-top: -1px; }',
      '.hb-thin[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-thin[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-thin[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-wide",
    mode: "icon",
    cat: "basic",
    label: { ja: "伸びながら×", en: "Stretches into ×" },
    html: '<button class="hb-wide" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-wide {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-wide span {",
      "  position: absolute; left: 50%; top: 50%; width: 28px; height: 3px; margin: -1.5px 0 0 -14px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.25s ease, width 0.35s ease, margin-left 0.35s ease;",
      "}",
      ".hb-wide span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-wide span:nth-child(3) { transform: translateY(9px); }",
      '.hb-wide[aria-expanded="true"] span { width: 36px; margin-left: -18px; }',
      '.hb-wide[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-wide[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-wide[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
];
