// 枠・背景つきのアイコン変形（10種）
// ヘッダーに置いた時にボタンとして認識されやすいタイプ
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

const BARS = "<span></span><span></span><span></span>";

export const FRAME_ICONS = [
  {
    key: "hb-circle",
    mode: "icon",
    cat: "frame",
    label: { ja: "丸背景が広がって×", en: "Circle fills in behind the ×" },
    html: '<button class="hb-circle" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-circle {",
      "  position: relative; width: 48px; height: 48px; padding: 0; border-radius: 50%;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-circle::before {",
      '  content: ""; position: absolute; inset: 0; border-radius: 50%;',
      "  background: #6366f1; transform: scale(0);",
      "  transition: transform 0.35s cubic-bezier(0.34, 1.4, 0.64, 1);",
      "}",
      ".hb-circle span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease, background 0.35s ease;",
      "}",
      ".hb-circle span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-circle span:nth-child(3) { transform: translateY(9px); }",
      '.hb-circle[aria-expanded="true"]::before { transform: scale(1); }',
      '.hb-circle[aria-expanded="true"] span { background: #fff; }',
      '.hb-circle[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-circle[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-circle[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-square",
    mode: "icon",
    cat: "frame",
    label: { ja: "角丸の枠が現れて×", en: "Rounded frame appears" },
    html: '<button class="hb-square" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-square {",
      "  position: relative; width: 48px; height: 48px; padding: 0; border-radius: 12px;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-square::before {",
      '  content: ""; position: absolute; inset: 0; border-radius: 12px;',
      "  border: 2px solid #6366f1; opacity: 0; transform: scale(0.7);",
      "  transition: transform 0.35s ease, opacity 0.3s ease;",
      "}",
      ".hb-square span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease 0.1s, opacity 0.3s ease, width 0.35s ease 0.1s, left 0.35s ease 0.1s;",
      "}",
      ".hb-square span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-square span:nth-child(3) { transform: translateY(9px); }",
      '.hb-square[aria-expanded="true"]::before { opacity: 1; transform: scale(1); }',
      '.hb-square[aria-expanded="true"] span { left: 14px; width: 20px; }',
      '.hb-square[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-square[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-square[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-borderdraw",
    mode: "icon",
    cat: "frame",
    label: { ja: "枠線が描かれて×", en: "Frame draws itself" },
    html: '<button class="hb-borderdraw" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-borderdraw {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      "/* 上下の線が横に伸び、続いて左右の線が縦に伸びて枠になる */",
      ".hb-borderdraw::before,",
      ".hb-borderdraw::after {",
      '  content: ""; position: absolute; inset: 0;',
      "  transition: transform 0.3s ease;",
      "}",
      ".hb-borderdraw::before {",
      "  border-top: 2px solid #6366f1; border-bottom: 2px solid #6366f1;",
      "  transform: scaleX(0);",
      "}",
      ".hb-borderdraw::after {",
      "  border-left: 2px solid #6366f1; border-right: 2px solid #6366f1;",
      "  transform: scaleY(0); transition-delay: 0.28s;",
      "}",
      ".hb-borderdraw span {",
      "  position: absolute; left: 12px; top: 50%; width: 24px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease, opacity 0.25s ease;",
      "}",
      ".hb-borderdraw span:nth-child(1) { transform: translateY(-8px); }",
      ".hb-borderdraw span:nth-child(3) { transform: translateY(8px); }",
      '.hb-borderdraw[aria-expanded="true"]::before { transform: scaleX(1); transition-delay: 0s; }',
      '.hb-borderdraw[aria-expanded="true"]::after { transform: scaleY(1); transition-delay: 0.28s; }',
      '.hb-borderdraw[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-borderdraw[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-borderdraw[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-ripple",
    mode: "icon",
    cat: "frame",
    label: { ja: "波紋が広がって×", en: "Ripple spreads out" },
    html: '<button class="hb-ripple" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-ripple {",
      "  position: relative; width: 48px; height: 48px; padding: 0; border-radius: 50%;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-ripple::before {",
      '  content: ""; position: absolute; inset: 0; border-radius: 50%;',
      "  border: 2px solid #ec4899; opacity: 0;",
      "}",
      ".hb-ripple span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease;",
      "}",
      ".hb-ripple span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-ripple span:nth-child(3) { transform: translateY(9px); }",
      '.hb-ripple[aria-expanded="true"]::before { animation: hb-ripple-out 0.6s ease-out; }',
      '.hb-ripple[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-ripple[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-ripple[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
      "@keyframes hb-ripple-out {",
      "  0% { opacity: 0.9; transform: scale(0.6); }",
      "  100% { opacity: 0; transform: scale(1.7); }",
      "}",
    ],
  },
  {
    key: "hb-fill",
    mode: "icon",
    cat: "frame",
    label: { ja: "下から塗りつぶされて×", en: "Fills up from the bottom" },
    html: '<button class="hb-fill" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-fill {",
      "  position: relative; width: 48px; height: 48px; padding: 0; overflow: hidden; border-radius: 10px;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-fill::before {",
      '  content: ""; position: absolute; left: 0; right: 0; bottom: 0; height: 100%;',
      "  background: #ec4899; transform: scaleY(0); transform-origin: bottom;",
      "  transition: transform 0.35s ease;",
      "}",
      ".hb-fill span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease, background 0.35s ease;",
      "}",
      ".hb-fill span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-fill span:nth-child(3) { transform: translateY(9px); }",
      '.hb-fill[aria-expanded="true"]::before { transform: scaleY(1); }',
      '.hb-fill[aria-expanded="true"] span { background: #fff; }',
      '.hb-fill[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-fill[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-fill[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-neon",
    mode: "icon",
    cat: "frame",
    dark: true,
    label: { ja: "ネオンが灯って×", en: "Neon glow" },
    html: '<button class="hb-neon" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      "/* 暗い背景向け */",
      ".hb-neon {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-neon span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  box-shadow: 0 0 6px rgba(99, 102, 241, 0.7);",
      "  transition: transform 0.35s ease, opacity 0.3s ease, background 0.35s ease, box-shadow 0.35s ease;",
      "}",
      ".hb-neon span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-neon span:nth-child(3) { transform: translateY(9px); }",
      '.hb-neon[aria-expanded="true"] span { background: #ec4899; box-shadow: 0 0 8px rgba(236, 72, 153, 0.9), 0 0 20px rgba(236, 72, 153, 0.6); }',
      '.hb-neon[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-neon[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-neon[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-glass",
    mode: "icon",
    cat: "frame",
    dark: true,
    label: { ja: "ガラス風の丸ボタン", en: "Frosted glass button" },
    html: '<button class="hb-glass" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      "/* 暗い背景・写真の上向き。backdrop-filter は主要ブラウザで対応 */",
      ".hb-glass {",
      "  position: relative; width: 52px; height: 52px; padding: 0; border-radius: 50%;",
      "  background: rgba(255, 255, 255, 0.1); border: 1px solid rgba(255, 255, 255, 0.25);",
      "  backdrop-filter: blur(8px); -webkit-backdrop-filter: blur(8px);",
      "  cursor: pointer;",
      "  transition: background 0.35s ease, border-color 0.35s ease;",
      "}",
      ".hb-glass span {",
      "  position: absolute; left: 11px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #fff; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease, background 0.35s ease;",
      "}",
      ".hb-glass span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-glass span:nth-child(3) { transform: translateY(9px); }",
      '.hb-glass[aria-expanded="true"] { background: rgba(99, 102, 241, 0.35); border-color: rgba(255, 255, 255, 0.5); }',
      '.hb-glass[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-glass[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-glass[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-press",
    mode: "icon",
    cat: "frame",
    label: { ja: "押し込まれる立体ボタン", en: "Pressed-in button" },
    html: '<button class="hb-press" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-press {",
      "  position: relative; width: 52px; height: 52px; padding: 0; border-radius: 14px;",
      "  background: #eef2ff; border: none; cursor: pointer;",
      "  box-shadow: 0 4px 0 rgba(99, 102, 241, 0.35), 0 6px 14px rgba(99, 102, 241, 0.25);",
      "  transition: transform 0.2s ease, box-shadow 0.2s ease, background 0.3s ease;",
      "}",
      ".hb-press span {",
      "  position: absolute; left: 11px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease;",
      "}",
      ".hb-press span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-press span:nth-child(3) { transform: translateY(9px); }",
      '.hb-press[aria-expanded="true"] { transform: translateY(4px); box-shadow: 0 0 0 rgba(99, 102, 241, 0.35), inset 0 2px 6px rgba(99, 102, 241, 0.35); }',
      '.hb-press[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-press[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-press[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-outlinespin",
    mode: "icon",
    cat: "frame",
    label: { ja: "枠が回りながら現れて×", en: "Frame spins into place" },
    html: '<button class="hb-outlinespin" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-outlinespin {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-outlinespin::before {",
      '  content: ""; position: absolute; inset: 2px; border-radius: 10px;',
      "  border: 2px solid #ec4899; opacity: 0; transform: rotate(-90deg) scale(0.5);",
      "  transition: transform 0.45s cubic-bezier(0.34, 1.3, 0.64, 1), opacity 0.35s ease;",
      "}",
      ".hb-outlinespin span {",
      "  position: absolute; left: 11px; top: 50%; width: 26px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.4s ease, opacity 0.3s ease;",
      "}",
      ".hb-outlinespin span:nth-child(1) { transform: translateY(-8px); }",
      ".hb-outlinespin span:nth-child(3) { transform: translateY(8px); }",
      '.hb-outlinespin[aria-expanded="true"]::before { opacity: 1; transform: rotate(0) scale(1); }',
      '.hb-outlinespin[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-outlinespin[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-outlinespin[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-badge",
    mode: "icon",
    cat: "frame",
    label: { ja: "丸バッジが回って色が変わる", en: "Badge spins and changes color" },
    html: '<button class="hb-badge" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-badge {",
      "  position: relative; width: 52px; height: 52px; padding: 0; border-radius: 50%;",
      "  background: #6366f1; border: none; cursor: pointer;",
      "  transition: transform 0.5s cubic-bezier(0.65, 0, 0.35, 1), background 0.4s ease;",
      "}",
      ".hb-badge span {",
      "  position: absolute; left: 13px; top: 50%; width: 26px; height: 3px; margin-top: -1.5px;",
      "  background: #fff; border-radius: 2px;",
      "  transition: transform 0.5s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.3s ease;",
      "}",
      ".hb-badge span:nth-child(1) { transform: translateY(-8px); }",
      ".hb-badge span:nth-child(3) { transform: translateY(8px); }",
      '.hb-badge[aria-expanded="true"] { background: #ec4899; transform: rotate(180deg); }',
      '.hb-badge[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-badge[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-badge[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
];
