// スライド・押し出し系のアイコン変形（10種）
// アクセント色 #6366f1 / サブ色 #ec4899 は main.js が置換する

const BARS = "<span></span><span></span><span></span>";

export const SLIDE_ICONS = [
  {
    key: "hb-slideout",
    mode: "icon",
    cat: "slide",
    label: { ja: "右へ抜けて×が入る", en: "Slides out right, × slides in" },
    html: '<button class="hb-slideout" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-slideout {",
      "  position: relative; width: 48px; height: 48px; padding: 0; overflow: hidden;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-slideout span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease;",
      "}",
      ".hb-slideout span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-slideout span:nth-child(3) { transform: translateY(9px); }",
      "/* ×は擬似要素で作り、3本線が抜けきってから左から入れる */",
      ".hb-slideout::before,",
      ".hb-slideout::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px;",
      "  transition: transform 0.3s ease 0.22s;",
      "}",
      ".hb-slideout::before { transform: translateX(-52px) rotate(45deg); }",
      ".hb-slideout::after { transform: translateX(-52px) rotate(-45deg); }",
      '.hb-slideout[aria-expanded="true"] span:nth-child(1) { transform: translate(52px, -9px); }',
      '.hb-slideout[aria-expanded="true"] span:nth-child(2) { transform: translateX(52px); }',
      '.hb-slideout[aria-expanded="true"] span:nth-child(3) { transform: translate(52px, 9px); }',
      '.hb-slideout[aria-expanded="true"]::before { transform: translateX(0) rotate(45deg); }',
      '.hb-slideout[aria-expanded="true"]::after { transform: translateX(0) rotate(-45deg); }',
    ],
  },
  {
    key: "hb-slideleft",
    mode: "icon",
    cat: "slide",
    label: { ja: "左へ抜けて×が入る", en: "Slides out left, × slides in" },
    html: '<button class="hb-slideleft" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-slideleft {",
      "  position: relative; width: 48px; height: 48px; padding: 0; overflow: hidden;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-slideleft span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease;",
      "}",
      ".hb-slideleft span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-slideleft span:nth-child(3) { transform: translateY(9px); }",
      ".hb-slideleft::before,",
      ".hb-slideleft::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px;",
      "  transition: transform 0.3s ease 0.22s;",
      "}",
      ".hb-slideleft::before { transform: translateX(52px) rotate(45deg); }",
      ".hb-slideleft::after { transform: translateX(52px) rotate(-45deg); }",
      '.hb-slideleft[aria-expanded="true"] span:nth-child(1) { transform: translate(-52px, -9px); }',
      '.hb-slideleft[aria-expanded="true"] span:nth-child(2) { transform: translateX(-52px); }',
      '.hb-slideleft[aria-expanded="true"] span:nth-child(3) { transform: translate(-52px, 9px); }',
      '.hb-slideleft[aria-expanded="true"]::before { transform: translateX(0) rotate(45deg); }',
      '.hb-slideleft[aria-expanded="true"]::after { transform: translateX(0) rotate(-45deg); }',
    ],
  },
  {
    key: "hb-stagger",
    mode: "icon",
    cat: "slide",
    label: { ja: "時間差で1本ずつ抜ける", en: "Bars exit one after another" },
    html: '<button class="hb-stagger" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-stagger {",
      "  position: relative; width: 48px; height: 48px; padding: 0; overflow: hidden;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-stagger span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.28s ease;",
      "}",
      ".hb-stagger span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-stagger span:nth-child(3) { transform: translateY(9px); }",
      ".hb-stagger::before,",
      ".hb-stagger::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px;",
      "  transition: transform 0.3s ease 0.36s;",
      "}",
      ".hb-stagger::before { transform: translateX(-52px) rotate(45deg); }",
      ".hb-stagger::after { transform: translateX(-52px) rotate(-45deg); }",
      '.hb-stagger[aria-expanded="true"] span:nth-child(1) { transform: translate(52px, -9px); transition-delay: 0s; }',
      '.hb-stagger[aria-expanded="true"] span:nth-child(2) { transform: translateX(52px); transition-delay: 0.07s; }',
      '.hb-stagger[aria-expanded="true"] span:nth-child(3) { transform: translate(52px, 9px); transition-delay: 0.14s; }',
      '.hb-stagger[aria-expanded="true"]::before { transform: translateX(0) rotate(45deg); }',
      '.hb-stagger[aria-expanded="true"]::after { transform: translateX(0) rotate(-45deg); }',
    ],
  },
  {
    key: "hb-slideup",
    mode: "icon",
    cat: "slide",
    label: { ja: "上へ抜けて×が入る", en: "Slides out upward" },
    html: '<button class="hb-slideup" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-slideup {",
      "  position: relative; width: 48px; height: 48px; padding: 0; overflow: hidden;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-slideup span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease;",
      "}",
      ".hb-slideup span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-slideup span:nth-child(3) { transform: translateY(9px); }",
      ".hb-slideup::before,",
      ".hb-slideup::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px;",
      "  transition: transform 0.3s ease 0.22s;",
      "}",
      ".hb-slideup::before { transform: translateY(52px) rotate(45deg); }",
      ".hb-slideup::after { transform: translateY(52px) rotate(-45deg); }",
      '.hb-slideup[aria-expanded="true"] span:nth-child(1) { transform: translateY(-52px); }',
      '.hb-slideup[aria-expanded="true"] span:nth-child(2) { transform: translateY(-52px); }',
      '.hb-slideup[aria-expanded="true"] span:nth-child(3) { transform: translateY(-52px); }',
      '.hb-slideup[aria-expanded="true"]::before { transform: translateY(0) rotate(45deg); }',
      '.hb-slideup[aria-expanded="true"]::after { transform: translateY(0) rotate(-45deg); }',
    ],
  },
  {
    key: "hb-slidedown",
    mode: "icon",
    cat: "slide",
    label: { ja: "下へ抜けて×が入る", en: "Slides out downward" },
    html: '<button class="hb-slidedown" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-slidedown {",
      "  position: relative; width: 48px; height: 48px; padding: 0; overflow: hidden;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-slidedown span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease;",
      "}",
      ".hb-slidedown span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-slidedown span:nth-child(3) { transform: translateY(9px); }",
      ".hb-slidedown::before,",
      ".hb-slidedown::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px;",
      "  transition: transform 0.3s ease 0.22s;",
      "}",
      ".hb-slidedown::before { transform: translateY(-52px) rotate(45deg); }",
      ".hb-slidedown::after { transform: translateY(-52px) rotate(-45deg); }",
      '.hb-slidedown[aria-expanded="true"] span { transform: translateY(52px); }',
      '.hb-slidedown[aria-expanded="true"]::before { transform: translateY(0) rotate(45deg); }',
      '.hb-slidedown[aria-expanded="true"]::after { transform: translateY(0) rotate(-45deg); }',
    ],
  },
  {
    key: "hb-split",
    mode: "icon",
    cat: "slide",
    label: { ja: "上下に開いてから×", en: "Spreads apart, then ×" },
    html: '<button class="hb-split" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-split {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-split span {",
      "  position: absolute; left: 9px; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: top 0.3s ease, transform 0.3s ease, opacity 0.2s ease;",
      "}",
      ".hb-split span:nth-child(1) { top: calc(50% - 9px); }",
      ".hb-split span:nth-child(2) { top: 50%; }",
      ".hb-split span:nth-child(3) { top: calc(50% + 9px); }",
      '.hb-split[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      "/* 「一度大きく開く → 中央で×になる」の2段モーションは keyframes で表現する */",
      '.hb-split[aria-expanded="true"] span:nth-child(1) { animation: hb-split-top 0.55s ease forwards; }',
      '.hb-split[aria-expanded="true"] span:nth-child(3) { animation: hb-split-bottom 0.55s ease forwards; }',
      "@keyframes hb-split-top {",
      "  0% { top: calc(50% - 9px); transform: rotate(0); }",
      "  45% { top: calc(50% - 18px); transform: rotate(0); }",
      "  100% { top: 50%; transform: rotate(45deg); }",
      "}",
      "@keyframes hb-split-bottom {",
      "  0% { top: calc(50% + 9px); transform: rotate(0); }",
      "  45% { top: calc(50% + 18px); transform: rotate(0); }",
      "  100% { top: 50%; transform: rotate(-45deg); }",
      "}",
    ],
  },
  {
    key: "hb-zip",
    mode: "icon",
    cat: "slide",
    label: { ja: "左右にずれてから×", en: "Offsets sideways, then ×" },
    html: '<button class="hb-zip" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-zip {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-zip span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.25s ease;",
      "}",
      ".hb-zip span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-zip span:nth-child(3) { transform: translateY(9px); }",
      '.hb-zip[aria-expanded="true"] span:nth-child(1) { animation: hb-zip-top 0.5s ease forwards; }',
      '.hb-zip[aria-expanded="true"] span:nth-child(2) { opacity: 0; transform: translateX(20px); }',
      '.hb-zip[aria-expanded="true"] span:nth-child(3) { animation: hb-zip-bottom 0.5s ease forwards; }',
      "@keyframes hb-zip-top {",
      "  0% { transform: translateY(-9px); }",
      "  45% { transform: translate(12px, -9px); }",
      "  100% { transform: rotate(45deg); }",
      "}",
      "@keyframes hb-zip-bottom {",
      "  0% { transform: translateY(9px); }",
      "  45% { transform: translate(-12px, 9px); }",
      "  100% { transform: rotate(-45deg); }",
      "}",
    ],
  },
  {
    key: "hb-fadeorder",
    mode: "icon",
    cat: "slide",
    label: { ja: "上から順に消えて×", en: "Fades away top to bottom" },
    html: '<button class="hb-fadeorder" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-fadeorder {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-fadeorder span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px; transform-origin: right center;",
      "  transition: transform 0.25s ease, opacity 0.25s ease;",
      "}",
      ".hb-fadeorder span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-fadeorder span:nth-child(3) { transform: translateY(9px); }",
      ".hb-fadeorder::before,",
      ".hb-fadeorder::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px; transform-origin: center; opacity: 0;",
      "  transition: transform 0.3s ease 0.3s, opacity 0.3s ease 0.3s;",
      "}",
      ".hb-fadeorder::before { transform: rotate(45deg) scaleX(0); }",
      ".hb-fadeorder::after { transform: rotate(-45deg) scaleX(0); }",
      '.hb-fadeorder[aria-expanded="true"] span { opacity: 0; }',
      '.hb-fadeorder[aria-expanded="true"] span:nth-child(1) { transform: translateY(-9px) scaleX(0); transition-delay: 0s; }',
      '.hb-fadeorder[aria-expanded="true"] span:nth-child(2) { transform: scaleX(0); transition-delay: 0.09s; }',
      '.hb-fadeorder[aria-expanded="true"] span:nth-child(3) { transform: translateY(9px) scaleX(0); transition-delay: 0.18s; }',
      '.hb-fadeorder[aria-expanded="true"]::before { opacity: 1; transform: rotate(45deg) scaleX(1); }',
      '.hb-fadeorder[aria-expanded="true"]::after { opacity: 1; transform: rotate(-45deg) scaleX(1); }',
    ],
  },
  {
    key: "hb-diagonal",
    mode: "icon",
    cat: "slide",
    label: { ja: "斜めに抜けて×", en: "Exits diagonally" },
    html: '<button class="hb-diagonal" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-diagonal {",
      "  position: relative; width: 48px; height: 48px; padding: 0; overflow: hidden;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-diagonal span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.32s ease;",
      "}",
      ".hb-diagonal span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-diagonal span:nth-child(3) { transform: translateY(9px); }",
      ".hb-diagonal::before,",
      ".hb-diagonal::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px;",
      "  transition: transform 0.32s ease 0.24s;",
      "}",
      ".hb-diagonal::before { transform: translate(-46px, -46px) rotate(45deg); }",
      ".hb-diagonal::after { transform: translate(-46px, -46px) rotate(-45deg); }",
      '.hb-diagonal[aria-expanded="true"] span:nth-child(1) { transform: translate(46px, 37px); }',
      '.hb-diagonal[aria-expanded="true"] span:nth-child(2) { transform: translate(46px, 46px); }',
      '.hb-diagonal[aria-expanded="true"] span:nth-child(3) { transform: translate(46px, 55px); }',
      '.hb-diagonal[aria-expanded="true"]::before { transform: translate(0, 0) rotate(45deg); }',
      '.hb-diagonal[aria-expanded="true"]::after { transform: translate(0, 0) rotate(-45deg); }',
    ],
  },
  {
    key: "hb-slidealt",
    mode: "icon",
    cat: "slide",
    label: { ja: "1本ずつ交互の向きへ抜ける", en: "Bars exit alternating sides" },
    html: '<button class="hb-slidealt" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-slidealt {",
      "  position: relative; width: 48px; height: 48px; padding: 0; overflow: hidden;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-slidealt span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease;",
      "}",
      ".hb-slidealt span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-slidealt span:nth-child(3) { transform: translateY(9px); }",
      ".hb-slidealt::before,",
      ".hb-slidealt::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px; opacity: 0;",
      "  transition: transform 0.3s ease 0.3s, opacity 0.2s ease 0.3s;",
      "}",
      ".hb-slidealt::before { transform: rotate(45deg) scale(0.3); }",
      ".hb-slidealt::after { transform: rotate(-45deg) scale(0.3); }",
      '.hb-slidealt[aria-expanded="true"] span:nth-child(1) { transform: translate(52px, -9px); transition-delay: 0s; }',
      '.hb-slidealt[aria-expanded="true"] span:nth-child(2) { transform: translateX(-52px); transition-delay: 0.08s; }',
      '.hb-slidealt[aria-expanded="true"] span:nth-child(3) { transform: translate(52px, 9px); transition-delay: 0.16s; }',
      '.hb-slidealt[aria-expanded="true"]::before { opacity: 1; transform: rotate(45deg) scale(1); }',
      '.hb-slidealt[aria-expanded="true"]::after { opacity: 1; transform: rotate(-45deg) scale(1); }',
    ],
  },
];
