// 回転・スピン系のアイコン変形（10種）
// アクセント色 #6366f1 / サブ色 #ec4899 は main.js が置換する

const BARS = "<span></span><span></span><span></span>";

export const SPIN_ICONS = [
  {
    key: "hb-spin",
    mode: "icon",
    cat: "spin",
    label: { ja: "半回転しながら×", en: "Half spin into ×" },
    html: '<button class="hb-spin" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-spin {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transition: transform 0.45s ease;",
      "}",
      ".hb-spin span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.45s ease, opacity 0.3s ease;",
      "}",
      ".hb-spin span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-spin span:nth-child(3) { transform: translateY(9px); }",
      '.hb-spin[aria-expanded="true"] { transform: rotate(180deg); }',
      '.hb-spin[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-spin[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-spin[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-spin360",
    mode: "icon",
    cat: "spin",
    label: { ja: "1回転しながら×", en: "Full spin into ×" },
    html: '<button class="hb-spin360" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-spin360 {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transition: transform 0.6s ease;",
      "}",
      ".hb-spin360 span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.6s ease, opacity 0.3s ease 0.2s;",
      "}",
      ".hb-spin360 span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-spin360 span:nth-child(3) { transform: translateY(9px); }",
      '.hb-spin360[aria-expanded="true"] { transform: rotate(360deg); }',
      '.hb-spin360[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-spin360[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-spin360[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-spinrev",
    mode: "icon",
    cat: "spin",
    label: { ja: "逆回転しながら×", en: "Counter spin into ×" },
    html: '<button class="hb-spinrev" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-spinrev {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transition: transform 0.45s ease;",
      "}",
      ".hb-spinrev span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.45s ease, opacity 0.3s ease, background 0.45s ease;",
      "}",
      ".hb-spinrev span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-spinrev span:nth-child(3) { transform: translateY(9px); }",
      '.hb-spinrev[aria-expanded="true"] { transform: rotate(-180deg); }',
      '.hb-spinrev[aria-expanded="true"] span { background: #ec4899; }',
      '.hb-spinrev[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-spinrev[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-spinrev[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-spinbounce",
    mode: "icon",
    cat: "spin",
    label: { ja: "弾む回転", en: "Bouncy spin" },
    html: '<button class="hb-spinbounce" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-spinbounce {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transition: transform 0.7s cubic-bezier(0.68, -0.4, 0.27, 1.4);",
      "}",
      ".hb-spinbounce span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.5s cubic-bezier(0.68, -0.6, 0.27, 1.6), opacity 0.3s ease;",
      "}",
      ".hb-spinbounce span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-spinbounce span:nth-child(3) { transform: translateY(9px); }",
      '.hb-spinbounce[aria-expanded="true"] { transform: rotate(360deg); }',
      '.hb-spinbounce[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-spinbounce[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-spinbounce[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-flipx",
    mode: "icon",
    cat: "spin",
    label: { ja: "横軸でめくれて×", en: "Flips on the X axis" },
    html: '<button class="hb-flipx" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-flipx {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transform-style: preserve-3d;",
      "  transition: transform 0.5s ease;",
      "}",
      ".hb-flipx span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.5s ease, opacity 0.25s ease 0.15s;",
      "}",
      ".hb-flipx span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-flipx span:nth-child(3) { transform: translateY(9px); }",
      '.hb-flipx[aria-expanded="true"] { transform: perspective(220px) rotateX(180deg); }',
      '.hb-flipx[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-flipx[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-flipx[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-flipy",
    mode: "icon",
    cat: "spin",
    label: { ja: "縦軸でめくれて×", en: "Flips on the Y axis" },
    html: '<button class="hb-flipy" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-flipy {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transform-style: preserve-3d;",
      "  transition: transform 0.5s ease;",
      "}",
      ".hb-flipy span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.5s ease, opacity 0.25s ease 0.15s;",
      "}",
      ".hb-flipy span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-flipy span:nth-child(3) { transform: translateY(9px); }",
      '.hb-flipy[aria-expanded="true"] { transform: perspective(220px) rotateY(180deg); }',
      '.hb-flipy[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-flipy[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-flipy[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-twist",
    mode: "icon",
    cat: "spin",
    label: { ja: "上下が逆向きに大きく回る", en: "Bars twist in opposite ways" },
    html: '<button class="hb-twist" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-twist {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-twist span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.55s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.3s ease;",
      "}",
      ".hb-twist span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-twist span:nth-child(3) { transform: translateY(9px); }",
      "/* 225deg / -225deg ＝ 半周以上まわってから×の角度に収まる */",
      '.hb-twist[aria-expanded="true"] span:nth-child(1) { transform: rotate(225deg); }',
      '.hb-twist[aria-expanded="true"] span:nth-child(2) { opacity: 0; transform: scaleX(0); }',
      '.hb-twist[aria-expanded="true"] span:nth-child(3) { transform: rotate(-225deg); }',
    ],
  },
  {
    key: "hb-spinscale",
    mode: "icon",
    cat: "spin",
    label: { ja: "縮んで回って×", en: "Shrink, spin, then ×" },
    html: '<button class="hb-spinscale" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-spinscale {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transition: transform 0.5s cubic-bezier(0.5, -0.4, 0.5, 1.4);",
      "}",
      ".hb-spinscale span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.5s ease, opacity 0.3s ease;",
      "}",
      ".hb-spinscale span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-spinscale span:nth-child(3) { transform: translateY(9px); }",
      '.hb-spinscale[aria-expanded="true"] { transform: rotate(180deg) scale(0.75); }',
      '.hb-spinscale[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-spinscale[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-spinscale[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-spinslow",
    mode: "icon",
    cat: "spin",
    label: { ja: "ゆっくり大きく回る", en: "Slow, wide spin" },
    html: '<button class="hb-spinslow" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-spinslow {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transition: transform 0.9s cubic-bezier(0.65, 0, 0.35, 1);",
      "}",
      ".hb-spinslow span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.9s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.4s ease 0.25s;",
      "}",
      ".hb-spinslow span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-spinslow span:nth-child(3) { transform: translateY(9px); }",
      '.hb-spinslow[aria-expanded="true"] { transform: rotate(720deg); }',
      '.hb-spinslow[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-spinslow[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-spinslow[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-crossspin",
    mode: "icon",
    cat: "spin",
    label: { ja: "×が回りながら現れる", en: "The × spins in" },
    html: '<button class="hb-crossspin" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-crossspin {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-crossspin span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease, opacity 0.3s ease;",
      "}",
      ".hb-crossspin span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-crossspin span:nth-child(3) { transform: translateY(9px); }",
      "/* 3本線が縮んで消えた後、擬似要素の×が半回転しながら現れる */",
      ".hb-crossspin::before,",
      ".hb-crossspin::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px; opacity: 0;",
      "  transition: transform 0.45s ease 0.15s, opacity 0.3s ease 0.15s;",
      "}",
      ".hb-crossspin::before { transform: rotate(-135deg) scaleX(0.2); }",
      ".hb-crossspin::after { transform: rotate(135deg) scaleX(0.2); }",
      '.hb-crossspin[aria-expanded="true"] span { opacity: 0; transform: translateY(0) scaleX(0); transition-delay: 0s; }',
      '.hb-crossspin[aria-expanded="true"]::before { opacity: 1; transform: rotate(45deg) scaleX(1); }',
      '.hb-crossspin[aria-expanded="true"]::after { opacity: 1; transform: rotate(-45deg) scaleX(1); }',
    ],
  },
];
