// 矢印・記号に変わるアイコン変形（10種）
// 戻る矢印やアコーディオンの開閉マークなど、×以外の意味を持たせたい時に使う
// アクセント色 #6366f1 / サブ色 #ec4899 は main.js が置換する

const BARS = "<span></span><span></span><span></span>";
const MORPH_TRANSITION =
  "  transition: left 0.35s ease, top 0.35s ease, width 0.35s ease, height 0.35s ease, margin-top 0.35s ease, border-radius 0.35s ease, transform 0.35s ease, opacity 0.25s ease, background 0.35s ease;";

export const SYMBOL_ICONS = [
  {
    key: "hb-arrowleft",
    mode: "icon",
    cat: "symbol",
    label: { ja: "左向き矢印（←）になる", en: "Turns into a back arrow" },
    html: '<button class="hb-arrowleft" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-arrowleft {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-arrowleft span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      MORPH_TRANSITION,
      "}",
      "/* 上下の線は矢じりになるので、左端（矢印の先端）を軸に回す */",
      ".hb-arrowleft span:nth-child(1) { transform-origin: left center; transform: translateY(-9px); }",
      ".hb-arrowleft span:nth-child(3) { transform-origin: left center; transform: translateY(9px); }",
      '.hb-arrowleft[aria-expanded="true"] span:nth-child(1) { width: 15px; transform: rotate(-45deg); }',
      '.hb-arrowleft[aria-expanded="true"] span:nth-child(3) { width: 15px; transform: rotate(45deg); }',
    ],
  },
  {
    key: "hb-arrowright",
    mode: "icon",
    cat: "symbol",
    label: { ja: "右向き矢印（→）になる", en: "Turns into a forward arrow" },
    html: '<button class="hb-arrowright" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-arrowright {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-arrowright span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      MORPH_TRANSITION,
      "}",
      ".hb-arrowright span:nth-child(1) { transform-origin: right center; transform: translateY(-9px); }",
      ".hb-arrowright span:nth-child(3) { transform-origin: right center; transform: translateY(9px); }",
      '.hb-arrowright[aria-expanded="true"] span:nth-child(1) { left: 24px; width: 15px; transform: rotate(-45deg); }',
      '.hb-arrowright[aria-expanded="true"] span:nth-child(3) { left: 24px; width: 15px; transform: rotate(45deg); }',
    ],
  },
  {
    key: "hb-arrowup",
    mode: "icon",
    cat: "symbol",
    label: { ja: "上向き矢印（↑）になる", en: "Turns into an up arrow" },
    html: '<button class="hb-arrowup" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-arrowup {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transition: transform 0.4s ease;",
      "}",
      ".hb-arrowup span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      MORPH_TRANSITION,
      "}",
      ".hb-arrowup span:nth-child(1) { transform-origin: left center; transform: translateY(-9px); }",
      ".hb-arrowup span:nth-child(3) { transform-origin: left center; transform: translateY(9px); }",
      "/* 左向き矢印を作り、ボタンごと90度回して上向きにする */",
      '.hb-arrowup[aria-expanded="true"] { transform: rotate(90deg); }',
      '.hb-arrowup[aria-expanded="true"] span:nth-child(1) { width: 15px; transform: rotate(-45deg); }',
      '.hb-arrowup[aria-expanded="true"] span:nth-child(3) { width: 15px; transform: rotate(45deg); }',
    ],
  },
  {
    key: "hb-arrowdown",
    mode: "icon",
    cat: "symbol",
    label: { ja: "下向き矢印（↓）になる", en: "Turns into a down arrow" },
    html: '<button class="hb-arrowdown" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-arrowdown {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "  transition: transform 0.4s ease;",
      "}",
      ".hb-arrowdown span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      MORPH_TRANSITION,
      "}",
      ".hb-arrowdown span:nth-child(1) { transform-origin: left center; transform: translateY(-9px); }",
      ".hb-arrowdown span:nth-child(3) { transform-origin: left center; transform: translateY(9px); }",
      '.hb-arrowdown[aria-expanded="true"] { transform: rotate(-90deg); }',
      '.hb-arrowdown[aria-expanded="true"] span:nth-child(1) { width: 15px; transform: rotate(-45deg); }',
      '.hb-arrowdown[aria-expanded="true"] span:nth-child(3) { width: 15px; transform: rotate(45deg); }',
    ],
  },
  {
    key: "hb-chevron",
    mode: "icon",
    cat: "symbol",
    label: { ja: "山形（＞）になる", en: "Turns into a chevron" },
    html: '<button class="hb-chevron" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-chevron {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-chevron span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      MORPH_TRANSITION,
      "}",
      ".hb-chevron span:nth-child(1) { transform-origin: right center; transform: translateY(-9px); }",
      ".hb-chevron span:nth-child(3) { transform-origin: right center; transform: translateY(9px); }",
      '.hb-chevron[aria-expanded="true"] span:nth-child(1) { left: 15px; width: 17px; transform: rotate(-45deg); background: #ec4899; }',
      '.hb-chevron[aria-expanded="true"] span:nth-child(2) { opacity: 0; transform: scaleX(0); }',
      '.hb-chevron[aria-expanded="true"] span:nth-child(3) { left: 15px; width: 17px; transform: rotate(45deg); background: #ec4899; }',
    ],
  },
  {
    key: "hb-check",
    mode: "icon",
    cat: "symbol",
    label: { ja: "チェック（✓）になる", en: "Turns into a checkmark" },
    html: '<button class="hb-check" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-check {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-check span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      MORPH_TRANSITION,
      "}",
      ".hb-check span:nth-child(1) { transform-origin: right center; transform: translateY(-9px); }",
      ".hb-check span:nth-child(3) { transform-origin: left center; transform: translateY(9px); }",
      "/* 2本の線が「く」の字の頂点で接するよう、左右の端を軸にして畳む */",
      '.hb-check[aria-expanded="true"] span:nth-child(1) { left: 8px; top: calc(50% + 6px); width: 14px; transform: rotate(45deg); background: #ec4899; }',
      '.hb-check[aria-expanded="true"] span:nth-child(2) { opacity: 0; transform: scaleX(0); }',
      '.hb-check[aria-expanded="true"] span:nth-child(3) { left: 22px; top: calc(50% + 6px); width: 24px; transform: rotate(-50deg); background: #ec4899; }',
    ],
  },
  {
    key: "hb-minus",
    mode: "icon",
    cat: "symbol",
    label: { ja: "1本線（−）に集約", en: "Collapses to a single bar" },
    html: '<button class="hb-minus" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-minus {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-minus span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease, background 0.35s ease;",
      "}",
      ".hb-minus span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-minus span:nth-child(3) { transform: translateY(9px); }",
      '.hb-minus[aria-expanded="true"] span { background: #ec4899; }',
      '.hb-minus[aria-expanded="true"] span:nth-child(1) { transform: translateY(0); opacity: 0; }',
      '.hb-minus[aria-expanded="true"] span:nth-child(3) { transform: translateY(0); opacity: 0; }',
    ],
  },
  {
    key: "hb-equal",
    mode: "icon",
    cat: "symbol",
    label: { ja: "2本線（＝）になる", en: "Becomes an equals sign" },
    html: '<button class="hb-equal" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-equal {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-equal span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease, width 0.35s ease, background 0.35s ease;",
      "}",
      ".hb-equal span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-equal span:nth-child(3) { transform: translateY(9px); }",
      '.hb-equal[aria-expanded="true"] span { width: 22px; background: #ec4899; }',
      '.hb-equal[aria-expanded="true"] span:nth-child(1) { transform: translateY(-5px); }',
      '.hb-equal[aria-expanded="true"] span:nth-child(2) { opacity: 0; transform: scaleX(0); }',
      '.hb-equal[aria-expanded="true"] span:nth-child(3) { transform: translateY(5px); }',
    ],
  },
  {
    key: "hb-dots",
    mode: "icon",
    cat: "symbol",
    label: { ja: "縦3点（︙）になる", en: "Becomes a kebab menu" },
    html: '<button class="hb-dots" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-dots {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-dots span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      MORPH_TRANSITION,
      "}",
      ".hb-dots span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-dots span:nth-child(3) { transform: translateY(9px); }",
      '.hb-dots[aria-expanded="true"] span { left: 21px; width: 6px; height: 6px; margin-top: -3px; border-radius: 50%; background: #ec4899; }',
      '.hb-dots[aria-expanded="true"] span:nth-child(1) { transform: translateY(-10px); }',
      '.hb-dots[aria-expanded="true"] span:nth-child(3) { transform: translateY(10px); }',
    ],
  },
  {
    key: "hb-dot",
    mode: "icon",
    cat: "symbol",
    label: { ja: "1つの点に集まる", en: "Collapses into one dot" },
    html: '<button class="hb-dot" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-dot {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-dot span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      MORPH_TRANSITION,
      "}",
      ".hb-dot span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-dot span:nth-child(3) { transform: translateY(9px); }",
      "/* 3本が重なって1つの点に見える */",
      '.hb-dot[aria-expanded="true"] span { left: 19px; width: 10px; height: 10px; margin-top: -5px; border-radius: 50%; background: #ec4899; transform: translateY(0); }',
    ],
  },
];
