// 応用のアイコン変形（10種）＝定番の変形に一手加えたもの
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

const BARS = "<span></span><span></span><span></span>";

export const UNIQUE_ICONS = [
  {
    key: "hb-text",
    mode: "icon",
    cat: "unique",
    label: { ja: "MENU / CLOSE の文字が切り替わる", en: "MENU / CLOSE label swaps" },
    html:
      '<button class="hb-text" aria-label="メニュー" aria-expanded="false">' +
      '<span class="hb-text__bars"><i></i><i></i><i></i></span>' +
      '<span class="hb-text__label"><b>MENU</b><b>CLOSE</b></span>' +
      "</button>",
    css: [
      ".hb-text {",
      "  display: flex; flex-direction: column; align-items: center; gap: 6px;",
      "  padding: 0; border: none; background: none; cursor: pointer;",
      "}",
      ".hb-text__bars { position: relative; display: block; width: 34px; height: 24px; }",
      ".hb-text__bars i {",
      "  position: absolute; left: 0; top: 50%; width: 34px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease;",
      "}",
      ".hb-text__bars i:nth-child(1) { transform: translateY(-8px); }",
      ".hb-text__bars i:nth-child(3) { transform: translateY(8px); }",
      "/* MENU と CLOSE を縦に並べ、開閉に合わせてスライドさせる */",
      ".hb-text__label {",
      "  display: block; width: 68px; height: 18px; overflow: hidden;",
      "  font-family: inherit; font-size: 16px; font-weight: 700; letter-spacing: 0.04em; color: #6366f1;",
      "}",
      ".hb-text__label b {",
      "  display: block; height: 18px; line-height: 18px; font-weight: 700; text-align: center;",
      "  transition: transform 0.35s ease;",
      "}",
      '.hb-text[aria-expanded="true"] .hb-text__bars i:nth-child(1) { transform: rotate(45deg); }',
      '.hb-text[aria-expanded="true"] .hb-text__bars i:nth-child(2) { opacity: 0; }',
      '.hb-text[aria-expanded="true"] .hb-text__bars i:nth-child(3) { transform: rotate(-45deg); }',
      '.hb-text[aria-expanded="true"] .hb-text__label b { transform: translateY(-18px); }',
    ],
  },
  {
    key: "hb-jelly",
    mode: "icon",
    cat: "unique",
    label: { ja: "ぷるんと弾んで×", en: "Jelly wobble into ×" },
    html: '<button class="hb-jelly" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-jelly {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-jelly span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease;",
      "}",
      ".hb-jelly span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-jelly span:nth-child(3) { transform: translateY(9px); }",
      '.hb-jelly[aria-expanded="true"] span:nth-child(1) { animation: hb-jelly-top 0.65s ease forwards; }',
      '.hb-jelly[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-jelly[aria-expanded="true"] span:nth-child(3) { animation: hb-jelly-bottom 0.65s ease forwards; }',
      "@keyframes hb-jelly-top {",
      "  0% { transform: translateY(-9px) scale(1, 1); }",
      "  35% { transform: translateY(-3px) scale(1.25, 0.6); }",
      "  65% { transform: rotate(45deg) scale(0.85, 1.35); }",
      "  100% { transform: rotate(45deg) scale(1, 1); }",
      "}",
      "@keyframes hb-jelly-bottom {",
      "  0% { transform: translateY(9px) scale(1, 1); }",
      "  35% { transform: translateY(3px) scale(1.25, 0.6); }",
      "  65% { transform: rotate(-45deg) scale(0.85, 1.35); }",
      "  100% { transform: rotate(-45deg) scale(1, 1); }",
      "}",
    ],
  },
  {
    key: "hb-step",
    mode: "icon",
    cat: "unique",
    label: { ja: "長さ違いの3本が×に揃う", en: "Uneven bars line up into ×" },
    html: '<button class="hb-step" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-step {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-step span {",
      "  position: absolute; left: 9px; top: 50%; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease, width 0.35s ease;",
      "}",
      ".hb-step span:nth-child(1) { width: 30px; transform: translateY(-9px); }",
      ".hb-step span:nth-child(2) { width: 22px; }",
      ".hb-step span:nth-child(3) { width: 14px; transform: translateY(9px); }",
      '.hb-step[aria-expanded="true"] span { width: 30px; }',
      '.hb-step[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-step[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-step[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
    ],
  },
  {
    key: "hb-double",
    mode: "icon",
    cat: "unique",
    label: { ja: "5本に増えてから×", en: "Grows to five bars, then ×" },
    html: '<button class="hb-double" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-double {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-double span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.4s ease, opacity 0.3s ease;",
      "}",
      ".hb-double span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-double span:nth-child(3) { transform: translateY(9px); }",
      "/* 擬似要素の2本が割り込んで5本になり、そのまま中央へ吸い込まれる */",
      ".hb-double::before,",
      ".hb-double::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px; opacity: 0;",
      "  transition: transform 0.4s ease, opacity 0.3s ease;",
      "}",
      '.hb-double[aria-expanded="true"]::before { opacity: 1; animation: hb-double-a 0.6s ease forwards; }',
      '.hb-double[aria-expanded="true"]::after { opacity: 1; animation: hb-double-b 0.6s ease forwards; }',
      '.hb-double[aria-expanded="true"] span:nth-child(1) { transform: rotate(45deg); }',
      '.hb-double[aria-expanded="true"] span:nth-child(2) { opacity: 0; }',
      '.hb-double[aria-expanded="true"] span:nth-child(3) { transform: rotate(-45deg); }',
      "@keyframes hb-double-a {",
      "  0% { opacity: 0; transform: translateY(0); }",
      "  40% { opacity: 1; transform: translateY(-4.5px); }",
      "  100% { opacity: 0; transform: translateY(0) scaleX(0.2); }",
      "}",
      "@keyframes hb-double-b {",
      "  0% { opacity: 0; transform: translateY(0); }",
      "  40% { opacity: 1; transform: translateY(4.5px); }",
      "  100% { opacity: 0; transform: translateY(0) scaleX(0.2); }",
      "}",
    ],
  },
  {
    key: "hb-skew",
    mode: "icon",
    cat: "unique",
    label: { ja: "斜めにひしゃげてから×", en: "Skews, then snaps into ×" },
    html: '<button class="hb-skew" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-skew {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-skew span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease;",
      "}",
      ".hb-skew span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-skew span:nth-child(3) { transform: translateY(9px); }",
      '.hb-skew[aria-expanded="true"] span:nth-child(1) { animation: hb-skew-top 0.6s ease forwards; }',
      '.hb-skew[aria-expanded="true"] span:nth-child(2) { opacity: 0; transform: skewX(-40deg) scaleX(0); }',
      '.hb-skew[aria-expanded="true"] span:nth-child(3) { animation: hb-skew-bottom 0.6s ease forwards; }',
      "@keyframes hb-skew-top {",
      "  0% { transform: translateY(-9px) skewX(0); }",
      "  40% { transform: translateY(-9px) skewX(-35deg); }",
      "  100% { transform: rotate(45deg) skewX(0); }",
      "}",
      "@keyframes hb-skew-bottom {",
      "  0% { transform: translateY(9px) skewX(0); }",
      "  40% { transform: translateY(9px) skewX(35deg); }",
      "  100% { transform: rotate(-45deg) skewX(0); }",
      "}",
    ],
  },
  {
    key: "hb-fold",
    mode: "icon",
    cat: "unique",
    label: { ja: "折り畳まれて×が起き上がる", en: "Folds away, × rises" },
    html: '<button class="hb-fold" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-fold {",
      "  position: relative; width: 48px; height: 48px; padding: 0; perspective: 240px;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-fold span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease, opacity 0.25s ease;",
      "}",
      ".hb-fold span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-fold span:nth-child(3) { transform: translateY(9px); }",
      ".hb-fold::before,",
      ".hb-fold::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px; opacity: 0;",
      "  transition: transform 0.35s ease 0.2s, opacity 0.25s ease 0.2s;",
      "}",
      ".hb-fold::before { transform: rotateX(-90deg) rotate(45deg); }",
      ".hb-fold::after { transform: rotateX(-90deg) rotate(-45deg); }",
      '.hb-fold[aria-expanded="true"] span { opacity: 0; }',
      '.hb-fold[aria-expanded="true"] span:nth-child(1) { transform: translateY(-9px) rotateX(90deg); }',
      '.hb-fold[aria-expanded="true"] span:nth-child(2) { transform: rotateX(90deg); }',
      '.hb-fold[aria-expanded="true"] span:nth-child(3) { transform: translateY(9px) rotateX(90deg); }',
      '.hb-fold[aria-expanded="true"]::before { opacity: 1; transform: rotateX(0) rotate(45deg); }',
      '.hb-fold[aria-expanded="true"]::after { opacity: 1; transform: rotateX(0) rotate(-45deg); }',
    ],
  },
  {
    key: "hb-blur",
    mode: "icon",
    cat: "unique",
    label: { ja: "ぼやけて×に入れ替わる", en: "Blurs out into ×" },
    html: '<button class="hb-blur" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-blur {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-blur span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.3s ease, opacity 0.3s ease, filter 0.3s ease;",
      "}",
      ".hb-blur span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-blur span:nth-child(3) { transform: translateY(9px); }",
      ".hb-blur::before,",
      ".hb-blur::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px; opacity: 0; filter: blur(6px);",
      "  transition: filter 0.3s ease 0.18s, opacity 0.3s ease 0.18s;",
      "}",
      ".hb-blur::before { transform: rotate(45deg); }",
      ".hb-blur::after { transform: rotate(-45deg); }",
      '.hb-blur[aria-expanded="true"] span { opacity: 0; filter: blur(6px); }',
      '.hb-blur[aria-expanded="true"]::before,',
      '.hb-blur[aria-expanded="true"]::after { opacity: 1; filter: blur(0); }',
    ],
  },
  {
    key: "hb-cube",
    mode: "icon",
    cat: "unique",
    label: { ja: "立方体が回って裏面の×へ", en: "Cube flips to its × face" },
    html:
      '<button class="hb-cube" aria-label="メニュー" aria-expanded="false">' +
      '<span class="hb-cube__box"><span class="hb-cube__front"><i></i><i></i><i></i></span><span class="hb-cube__back"></span></span>' +
      "</button>",
    css: [
      ".hb-cube {",
      "  position: relative; width: 48px; height: 48px; padding: 0; perspective: 320px;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-cube__box {",
      "  position: absolute; inset: 0; transform-style: preserve-3d;",
      "  transition: transform 0.55s cubic-bezier(0.65, 0, 0.35, 1);",
      "}",
      ".hb-cube__front,",
      ".hb-cube__back { position: absolute; inset: 0; backface-visibility: hidden; }",
      ".hb-cube__front { transform: translateZ(24px); }",
      ".hb-cube__back { transform: rotateX(90deg) translateZ(24px); }",
      ".hb-cube__front i {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "}",
      ".hb-cube__front i:nth-child(1) { transform: translateY(-9px); }",
      ".hb-cube__front i:nth-child(3) { transform: translateY(9px); }",
      ".hb-cube__back::before,",
      ".hb-cube__back::after {",
      '  content: ""; position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;',
      "  background: #ec4899; border-radius: 2px;",
      "}",
      ".hb-cube__back::before { transform: rotate(45deg); }",
      ".hb-cube__back::after { transform: rotate(-45deg); }",
      '.hb-cube[aria-expanded="true"] .hb-cube__box { transform: rotateX(-90deg); }',
    ],
  },
  {
    key: "hb-wave",
    mode: "icon",
    cat: "unique",
    label: { ja: "波のように順に揺れて×", en: "Ripples like a wave, then ×" },
    html: '<button class="hb-wave" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-wave {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-wave span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease;",
      "}",
      ".hb-wave span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-wave span:nth-child(3) { transform: translateY(9px); }",
      '.hb-wave[aria-expanded="true"] span:nth-child(1) { animation: hb-wave-top 0.7s ease forwards; }',
      '.hb-wave[aria-expanded="true"] span:nth-child(2) { animation: hb-wave-mid 0.7s ease forwards 0.08s; }',
      '.hb-wave[aria-expanded="true"] span:nth-child(3) { animation: hb-wave-bottom 0.7s ease forwards 0.16s; }',
      "@keyframes hb-wave-top {",
      "  0% { transform: translateY(-9px); }",
      "  35% { transform: translate(-8px, -9px) scaleX(0.75); }",
      "  100% { transform: rotate(45deg); }",
      "}",
      "@keyframes hb-wave-mid {",
      "  0% { transform: translateY(0); opacity: 1; }",
      "  35% { transform: translateX(-8px) scaleX(0.75); opacity: 1; }",
      "  100% { transform: scaleX(0); opacity: 0; }",
      "}",
      "@keyframes hb-wave-bottom {",
      "  0% { transform: translateY(9px); }",
      "  35% { transform: translate(-8px, 9px) scaleX(0.75); }",
      "  100% { transform: rotate(-45deg); }",
      "}",
    ],
  },
  {
    key: "hb-rubber",
    mode: "icon",
    cat: "unique",
    label: { ja: "ゴムのように伸びて×", en: "Stretches like rubber into ×" },
    html: '<button class="hb-rubber" aria-label="メニュー" aria-expanded="false">' + BARS + "</button>",
    css: [
      ".hb-rubber {",
      "  position: relative; width: 48px; height: 48px; padding: 0;",
      "  border: none; background: none; cursor: pointer;",
      "}",
      ".hb-rubber span {",
      "  position: absolute; left: 9px; top: 50%; width: 30px; height: 3px; margin-top: -1.5px;",
      "  background: #6366f1; border-radius: 2px;",
      "  transition: transform 0.35s ease, opacity 0.3s ease;",
      "}",
      ".hb-rubber span:nth-child(1) { transform: translateY(-9px); }",
      ".hb-rubber span:nth-child(3) { transform: translateY(9px); }",
      '.hb-rubber[aria-expanded="true"] span:nth-child(1) { animation: hb-rubber-top 0.6s cubic-bezier(0.5, 0, 0.3, 1.3) forwards; }',
      '.hb-rubber[aria-expanded="true"] span:nth-child(2) { opacity: 0; transform: scaleX(1.6); }',
      '.hb-rubber[aria-expanded="true"] span:nth-child(3) { animation: hb-rubber-bottom 0.6s cubic-bezier(0.5, 0, 0.3, 1.3) forwards; }',
      "@keyframes hb-rubber-top {",
      "  0% { transform: translateY(-9px) scaleX(1); }",
      "  45% { transform: translateY(-9px) scaleX(1.45); }",
      "  100% { transform: rotate(45deg) scaleX(1); }",
      "}",
      "@keyframes hb-rubber-bottom {",
      "  0% { transform: translateY(9px) scaleX(1); }",
      "  45% { transform: translateY(9px) scaleX(1.45); }",
      "  100% { transform: rotate(-45deg) scaleX(1); }",
      "}",
    ],
  },
];
