// カーテン：方向・分割（10種）
//
// 【共通の約束】遷移演出（カーテン・ページ遷移）は「幕が閉じている」が初期状態。
// JSが .is-open を付けると幕が開き、外すと閉じる。読み込み直後に開き、リンククリックで閉じてから遷移する。
// ms は幕が閉じ切るまでの時間（ミリ秒）＝コピーコードの setTimeout に使う。
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

const P1 = "<i></i>";
const P2 = "<i></i><i></i>";
const P5 = "<i></i><i></i><i></i><i></i><i></i>";
const P9 = "<i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i>";

export const CURTAIN_MOVE = [
  {
    key: "pt-split-x",
    cat: "curtain",
    ms: 600,
    label: { ja: "中央から左右に開く", en: "Splits open left and right" },
    html: '<div class="pt-split-x" aria-hidden="true">' + P2 + "</div>",
    css: [
      ".pt-split-x {",
      "  position: fixed; inset: 0; z-index: 9999; display: flex;",
      "  pointer-events: auto;",
      "}",
      ".pt-split-x.is-open { pointer-events: none; }",
      ".pt-split-x i {",
      "  flex: 1; background: #6366f1;",
      "  transition: transform 0.6s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-split-x.is-open i:nth-child(1) { transform: translateX(-100%); }",
      ".pt-split-x.is-open i:nth-child(2) { transform: translateX(100%); }",
    ],
  },
  {
    key: "pt-split-y",
    cat: "curtain",
    ms: 600,
    label: { ja: "中央から上下に開く", en: "Splits open top and bottom" },
    html: '<div class="pt-split-y" aria-hidden="true">' + P2 + "</div>",
    css: [
      ".pt-split-y {",
      "  position: fixed; inset: 0; z-index: 9999; display: flex; flex-direction: column;",
      "  pointer-events: auto;",
      "}",
      ".pt-split-y.is-open { pointer-events: none; }",
      ".pt-split-y i {",
      "  flex: 1; background: #6366f1;",
      "  transition: transform 0.6s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-split-y.is-open i:nth-child(1) { transform: translateY(-100%); }",
      ".pt-split-y.is-open i:nth-child(2) { transform: translateY(100%); }",
    ],
  },
  {
    key: "pt-slide-l",
    cat: "curtain",
    ms: 550,
    label: { ja: "一枚幕が左へ抜ける", en: "Single sheet exits left" },
    html: '<div class="pt-slide-l" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-slide-l {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-slide-l.is-open { pointer-events: none; }",
      ".pt-slide-l i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  transition: transform 0.55s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-slide-l.is-open i { transform: translateX(-100%); }",
    ],
  },
  {
    key: "pt-slide-r",
    cat: "curtain",
    ms: 550,
    label: { ja: "一枚幕が右へ抜ける", en: "Single sheet exits right" },
    html: '<div class="pt-slide-r" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-slide-r {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-slide-r.is-open { pointer-events: none; }",
      ".pt-slide-r i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  transition: transform 0.55s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-slide-r.is-open i { transform: translateX(100%); }",
    ],
  },
  {
    key: "pt-slide-u",
    cat: "curtain",
    ms: 550,
    label: { ja: "一枚幕が上へ抜ける", en: "Single sheet exits upward" },
    html: '<div class="pt-slide-u" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-slide-u {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-slide-u.is-open { pointer-events: none; }",
      ".pt-slide-u i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  transition: transform 0.55s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-slide-u.is-open i { transform: translateY(-100%); }",
    ],
  },
  {
    key: "pt-slide-d",
    cat: "curtain",
    ms: 550,
    label: { ja: "一枚幕が下へ抜ける", en: "Single sheet exits downward" },
    html: '<div class="pt-slide-d" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-slide-d {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-slide-d.is-open { pointer-events: none; }",
      ".pt-slide-d i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  transition: transform 0.55s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-slide-d.is-open i { transform: translateY(100%); }",
    ],
  },
  {
    key: "pt-stagger",
    cat: "curtain",
    ms: 800,
    label: { ja: "左右2枚が時間差で開く", en: "Two sheets open with a delay" },
    html: '<div class="pt-stagger" aria-hidden="true">' + P2 + "</div>",
    css: [
      ".pt-stagger {",
      "  position: fixed; inset: 0; z-index: 9999; display: flex;",
      "  pointer-events: auto;",
      "}",
      ".pt-stagger.is-open { pointer-events: none; }",
      ".pt-stagger i {",
      "  flex: 1;",
      "  transition: transform 0.6s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-stagger i:nth-child(1) { background: #6366f1; }",
      ".pt-stagger i:nth-child(2) { background: #ec4899; }",
      ".pt-stagger.is-open i:nth-child(1) { transform: translateX(-100%); }",
      ".pt-stagger.is-open i:nth-child(2) { transform: translateX(100%); transition-delay: 0.18s; }",
    ],
  },
  {
    key: "pt-stripe-v",
    cat: "curtain",
    ms: 900,
    label: { ja: "縦ストライプが順に抜ける", en: "Vertical stripes exit in sequence" },
    html: '<div class="pt-stripe-v" aria-hidden="true">' + P5 + "</div>",
    css: [
      ".pt-stripe-v {",
      "  position: fixed; inset: 0; z-index: 9999; display: flex;",
      "  pointer-events: auto;",
      "}",
      ".pt-stripe-v.is-open { pointer-events: none; }",
      ".pt-stripe-v i {",
      "  flex: 1; background: #6366f1;",
      "  transition: transform 0.55s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-stripe-v.is-open i { transform: translateY(-100%); }",
      ".pt-stripe-v.is-open i:nth-child(2) { transition-delay: 0.08s; }",
      ".pt-stripe-v.is-open i:nth-child(3) { transition-delay: 0.16s; }",
      ".pt-stripe-v.is-open i:nth-child(4) { transition-delay: 0.24s; }",
      ".pt-stripe-v.is-open i:nth-child(5) { transition-delay: 0.32s; }",
    ],
  },
  {
    key: "pt-stripe-h",
    cat: "curtain",
    ms: 900,
    label: { ja: "横ストライプが順に抜ける", en: "Horizontal stripes exit in sequence" },
    html: '<div class="pt-stripe-h" aria-hidden="true">' + P5 + "</div>",
    css: [
      ".pt-stripe-h {",
      "  position: fixed; inset: 0; z-index: 9999; display: flex; flex-direction: column;",
      "  pointer-events: auto;",
      "}",
      ".pt-stripe-h.is-open { pointer-events: none; }",
      ".pt-stripe-h i {",
      "  flex: 1; background: #6366f1;",
      "  transition: transform 0.55s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      "/* 1本ごとに左右へ交互に抜ける */",
      ".pt-stripe-h.is-open i { transform: translateX(-100%); }",
      ".pt-stripe-h.is-open i:nth-child(even) { transform: translateX(100%); }",
      ".pt-stripe-h.is-open i:nth-child(2) { transition-delay: 0.08s; }",
      ".pt-stripe-h.is-open i:nth-child(3) { transition-delay: 0.16s; }",
      ".pt-stripe-h.is-open i:nth-child(4) { transition-delay: 0.24s; }",
      ".pt-stripe-h.is-open i:nth-child(5) { transition-delay: 0.32s; }",
    ],
  },
  {
    key: "pt-checker",
    cat: "curtain",
    ms: 950,
    label: { ja: "市松のタイルが順に消える", en: "Checkered tiles fade out in order" },
    html: '<div class="pt-checker" aria-hidden="true">' + P9 + "</div>",
    css: [
      ".pt-checker {",
      "  position: fixed; inset: 0; z-index: 9999;",
      "  display: grid; grid-template-columns: repeat(3, 1fr); grid-template-rows: repeat(3, 1fr);",
      "  pointer-events: auto;",
      "}",
      ".pt-checker.is-open { pointer-events: none; }",
      ".pt-checker i {",
      "  background: #6366f1;",
      "  transition: transform 0.45s cubic-bezier(0.5, 0, 0.5, 1), opacity 0.45s ease;",
      "}",
      ".pt-checker i:nth-child(even) { background: #ec4899; }",
      ".pt-checker.is-open i { transform: scale(0); opacity: 0; }",
      "/* 左上から右下へ、対角線の順に消える */",
      ".pt-checker.is-open i:nth-child(2),",
      ".pt-checker.is-open i:nth-child(4) { transition-delay: 0.1s; }",
      ".pt-checker.is-open i:nth-child(3),",
      ".pt-checker.is-open i:nth-child(5),",
      ".pt-checker.is-open i:nth-child(7) { transition-delay: 0.2s; }",
      ".pt-checker.is-open i:nth-child(6),",
      ".pt-checker.is-open i:nth-child(8) { transition-delay: 0.3s; }",
      ".pt-checker.is-open i:nth-child(9) { transition-delay: 0.4s; }",
    ],
  },
];
