// カーテン：形状・質感（10種）
//
// 【共通の約束】幕が閉じているのが初期状態。JSが .is-open を付けると開く。
// ms は幕が閉じ切るまでの時間（ミリ秒）。
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

const P1 = "<i></i>";
const P4 = "<i></i><i></i><i></i><i></i>";
const P5 = "<i></i><i></i><i></i><i></i><i></i>";

export const CURTAIN_SHAPE = [
  {
    key: "pt-skew",
    cat: "curtain",
    ms: 600,
    label: { ja: "斜めに傾いた幕が抜ける", en: "Slanted sheet sweeps away" },
    html: '<div class="pt-skew" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-skew {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-skew.is-open { pointer-events: none; }",
      "/* 傾けたぶん画面より大きくして、角に隙間ができないようにする */",
      ".pt-skew i {",
      "  position: absolute; inset: -20%; background: #6366f1;",
      "  transform: skewX(-12deg);",
      "  transition: transform 0.6s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-skew.is-open i { transform: skewX(-12deg) translateX(-140%); }",
    ],
  },
  {
    key: "pt-circle",
    cat: "curtain",
    ms: 700,
    label: { ja: "円形に開く", en: "Circle iris opens" },
    html: '<div class="pt-circle" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-circle {",
      "  position: fixed; inset: 0; z-index: 9999;",
      "  pointer-events: auto;",
      "}",
      ".pt-circle.is-open { pointer-events: none; }",
      ".pt-circle i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  clip-path: circle(150% at 50% 50%);",
      "  transition: clip-path 0.7s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-circle.is-open i { clip-path: circle(0% at 50% 50%); }",
    ],
  },
  {
    key: "pt-diagonal",
    cat: "curtain",
    ms: 650,
    label: { ja: "対角線でスパッと切れる", en: "Diagonal cut wipe" },
    html: '<div class="pt-diagonal" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-diagonal {",
      "  position: fixed; inset: 0; z-index: 9999;",
      "  pointer-events: auto;",
      "}",
      ".pt-diagonal.is-open { pointer-events: none; }",
      "/* 4点の多角形どうしを補間するので、開いた側も同じ点数で書く */",
      ".pt-diagonal i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  clip-path: polygon(0 0, 100% 0, 100% 100%, 0 100%);",
      "  transition: clip-path 0.65s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-diagonal.is-open i { clip-path: polygon(0 0, 0 0, -60% 100%, -60% 100%); }",
    ],
  },
  {
    key: "pt-wave",
    cat: "curtain",
    ms: 700,
    label: { ja: "波形のふちで持ち上がる", en: "Lifts with a wavy edge" },
    html: '<div class="pt-wave" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-wave {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-wave.is-open { pointer-events: none; }",
      "/* 下辺だけ楕円にして、めくれ上がる布のふちに見せる */",
      ".pt-wave i {",
      "  position: absolute; left: -10%; right: -10%; top: -20%; height: 140%;",
      "  background: #6366f1;",
      "  border-radius: 0 0 50% 50% / 0 0 18% 18%;",
      "  transition: transform 0.7s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-wave.is-open i { transform: translateY(-145%); }",
    ],
  },
  {
    key: "pt-zigzag",
    cat: "curtain",
    ms: 700,
    label: { ja: "ギザギザのふちで抜ける", en: "Zigzag edge sweeps away" },
    html: '<div class="pt-zigzag" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-zigzag {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-zigzag.is-open { pointer-events: none; }",
      ".pt-zigzag i {",
      "  position: absolute; left: 0; right: 0; top: -25%; height: 125%;",
      "  background: #6366f1;",
      "  clip-path: polygon(",
      "    0 0, 100% 0, 100% 88%,",
      "    87.5% 100%, 75% 88%, 62.5% 100%, 50% 88%,",
      "    37.5% 100%, 25% 88%, 12.5% 100%, 0 88%",
      "  );",
      "  transition: transform 0.7s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-zigzag.is-open i { transform: translateY(-130%); }",
    ],
  },
  {
    key: "pt-roll",
    cat: "curtain",
    ms: 700,
    label: { ja: "ロールカーテンが巻き上がる", en: "Roller blind winds up" },
    html: '<div class="pt-roll" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-roll {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-roll.is-open { pointer-events: none; }",
      "/* 下辺の影が巻き取り棒に見える */",
      ".pt-roll i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  box-shadow: inset 0 -10px 0 rgba(15, 23, 42, 0.2);",
      "  transform-origin: top;",
      "  transition: transform 0.7s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-roll.is-open i { transform: scaleY(0); }",
    ],
  },
  {
    key: "pt-fold",
    cat: "curtain",
    ms: 850,
    label: { ja: "アコーディオンに折り畳まれる", en: "Folds up like an accordion" },
    html: '<div class="pt-fold" aria-hidden="true">' + P5 + "</div>",
    css: [
      ".pt-fold {",
      "  position: fixed; inset: 0; z-index: 9999; display: flex; flex-direction: column;",
      "  pointer-events: auto;",
      "}",
      ".pt-fold.is-open { pointer-events: none; }",
      "/* 折り目を上下交互にすると蛇腹らしく畳まれる */",
      ".pt-fold i {",
      "  flex: 1; background: #6366f1;",
      "  transition: transform 0.5s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-fold i:nth-child(odd) { transform-origin: top; }",
      ".pt-fold i:nth-child(even) {",
      "  transform-origin: bottom;",
      "  background: linear-gradient(rgba(15, 23, 42, 0.16), rgba(15, 23, 42, 0.16)), #6366f1;",
      "}",
      ".pt-fold.is-open i { transform: scaleY(0); }",
      ".pt-fold.is-open i:nth-child(2) { transition-delay: 0.07s; }",
      ".pt-fold.is-open i:nth-child(3) { transition-delay: 0.14s; }",
      ".pt-fold.is-open i:nth-child(4) { transition-delay: 0.21s; }",
      ".pt-fold.is-open i:nth-child(5) { transition-delay: 0.28s; }",
    ],
  },
  {
    key: "pt-flip",
    cat: "curtain",
    ms: 700,
    label: { ja: "幕が奥へめくれる", en: "Sheet flips away" },
    html: '<div class="pt-flip" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-flip {",
      "  position: fixed; inset: 0; z-index: 9999; perspective: 1200px;",
      "  pointer-events: auto;",
      "}",
      ".pt-flip.is-open { pointer-events: none; }",
      ".pt-flip i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  transform-origin: top; backface-visibility: hidden;",
      "  transition: transform 0.7s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-flip.is-open i { transform: rotateX(-95deg); }",
    ],
  },
  {
    key: "pt-drape",
    cat: "curtain",
    ms: 900,
    label: { ja: "布のドレープが持ち上がる", en: "Draped cloth lifts up" },
    html: '<div class="pt-drape" aria-hidden="true">' + P5 + "</div>",
    css: [
      ".pt-drape {",
      "  position: fixed; inset: 0; z-index: 9999; display: flex;",
      "  pointer-events: auto;",
      "}",
      ".pt-drape.is-open { pointer-events: none; }",
      "/* 縦の陰影で布のひだを表現する */",
      ".pt-drape i {",
      "  flex: 1;",
      "  background: linear-gradient(90deg, rgba(15, 23, 42, 0.25), transparent 35%, transparent 65%, rgba(15, 23, 42, 0.25)), #6366f1;",
      "  transition: transform 0.6s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-drape.is-open i { transform: translateY(-105%); }",
      ".pt-drape.is-open i:nth-child(2) { transition-delay: 0.06s; }",
      ".pt-drape.is-open i:nth-child(3) { transition-delay: 0.12s; }",
      ".pt-drape.is-open i:nth-child(4) { transition-delay: 0.18s; }",
      ".pt-drape.is-open i:nth-child(5) { transition-delay: 0.24s; }",
    ],
  },
  {
    key: "pt-iris",
    cat: "curtain",
    ms: 700,
    label: { ja: "中央の四角が広がって開く", en: "Rectangle opens from the center" },
    html: '<div class="pt-iris" aria-hidden="true">' + P4 + "</div>",
    css: [
      ".pt-iris {",
      "  position: fixed; inset: 0; z-index: 9999;",
      "  pointer-events: auto;",
      "}",
      ".pt-iris.is-open { pointer-events: none; }",
      "/* 上下左右の4枚が同時に縮み、中央から長方形の穴が広がる */",
      ".pt-iris i {",
      "  position: absolute; background: #6366f1;",
      "  transition: transform 0.7s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-iris i:nth-child(1) { top: 0; left: 0; right: 0; height: 50%; transform-origin: top; }",
      ".pt-iris i:nth-child(2) { bottom: 0; left: 0; right: 0; height: 50%; transform-origin: bottom; }",
      ".pt-iris i:nth-child(3) { top: 0; bottom: 0; left: 0; width: 50%; transform-origin: left; }",
      ".pt-iris i:nth-child(4) { top: 0; bottom: 0; right: 0; width: 50%; transform-origin: right; }",
      ".pt-iris.is-open i:nth-child(1),",
      ".pt-iris.is-open i:nth-child(2) { transform: scaleY(0); }",
      ".pt-iris.is-open i:nth-child(3),",
      ".pt-iris.is-open i:nth-child(4) { transform: scaleX(0); }",
    ],
  },
];
