// ローディング / オープニング（12種）
//
// 【共通の約束】遷移演出とは逆で「表示されている」が初期状態。
// 読み込み完了（window の load）で .is-done が付き、画面から消える。
// ms は消え切るまでの時間（ミリ秒）。
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

// ローディング画面の土台。exit には「消え方」の宣言を渡す
function shell(ns, extra) {
  return [
    "." + ns + " {",
    "  position: fixed; inset: 0; z-index: 9999;",
    "  display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 18px;",
    "  background: #6366f1;",
    "  visibility: visible;",
    "  transition: " + extra.base + ", visibility 0s;",
    "}",
    "." + ns + ".is-done {",
    "  " + extra.done,
    "  visibility: hidden; pointer-events: none;",
    "  transition: " + extra.base + ", visibility 0s linear " + extra.delay + ";",
    "}",
  ];
}

export const LOADING_EFFECTS = [
  {
    key: "ld-spinner",
    cat: "loading",
    ms: 600,
    label: { ja: "リングが回る", en: "Spinning ring" },
    html: '<div class="ld-spinner" role="status" aria-label="読み込み中"><i></i></div>',
    css: [
      ...shell("ld-spinner", { base: "opacity 0.5s ease", done: "opacity: 0;", delay: "0.5s" }),
      ".ld-spinner i {",
      "  width: 46px; height: 46px; border-radius: 50%;",
      "  border: 4px solid rgba(255, 255, 255, 0.3); border-top-color: #fff;",
      "  animation: ld-spinner-turn 0.8s linear infinite;",
      "}",
      "@keyframes ld-spinner-turn { to { transform: rotate(360deg); } }",
    ],
  },
  {
    key: "ld-bar",
    cat: "loading",
    ms: 650,
    label: { ja: "プログレスバーが伸びる", en: "Progress bar fills" },
    html: '<div class="ld-bar" role="status" aria-label="読み込み中"><i></i></div>',
    css: [
      ...shell("ld-bar", { base: "transform 0.6s cubic-bezier(0.76, 0, 0.24, 1)", done: "transform: translateY(-100%);", delay: "0.6s" }),
      ".ld-bar i {",
      "  position: relative; width: min(240px, 60%); height: 6px; border-radius: 99px;",
      "  background: rgba(255, 255, 255, 0.28); overflow: hidden;",
      "}",
      '.ld-bar i::after {',
      '  content: ""; position: absolute; inset: 0; border-radius: 99px; background: #fff;',
      "  transform-origin: left; animation: ld-bar-fill 1.6s cubic-bezier(0.3, 0.9, 0.4, 1) forwards;",
      "}",
      "@keyframes ld-bar-fill { from { transform: scaleX(0); } to { transform: scaleX(1); } }",
    ],
  },
  {
    key: "ld-dots",
    cat: "loading",
    ms: 500,
    label: { ja: "3点が順に跳ねる", en: "Three bouncing dots" },
    html: '<div class="ld-dots" role="status" aria-label="読み込み中"><i></i><i></i><i></i></div>',
    css: [
      ...shell("ld-dots", { base: "opacity 0.45s ease", done: "opacity: 0;", delay: "0.45s" }),
      ".ld-dots { flex-direction: row; gap: 12px; }",
      ".ld-dots i {",
      "  width: 14px; height: 14px; border-radius: 50%; background: #fff;",
      "  animation: ld-dots-jump 0.9s ease-in-out infinite;",
      "}",
      ".ld-dots i:nth-child(2) { animation-delay: 0.15s; }",
      ".ld-dots i:nth-child(3) { animation-delay: 0.3s; }",
      "@keyframes ld-dots-jump {",
      "  0%, 60%, 100% { transform: translateY(0); opacity: 0.55; }",
      "  30% { transform: translateY(-14px); opacity: 1; }",
      "}",
    ],
  },
  {
    key: "ld-logo",
    cat: "loading",
    ms: 700,
    label: { ja: "ロゴが脈打つ", en: "Pulsing logo" },
    html: '<div class="ld-logo" role="status" aria-label="読み込み中"><b>LOGO</b></div>',
    css: [
      ...shell("ld-logo", { base: "transform 0.65s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.65s ease", done: "transform: scale(1.35); opacity: 0;", delay: "0.65s" }),
      ".ld-logo b {",
      "  color: #fff; font-size: clamp(1.5rem, 1rem + 3vw, 3rem); font-weight: 800; letter-spacing: 0.24em;",
      "  animation: ld-logo-beat 1.4s ease-in-out infinite;",
      "}",
      "@keyframes ld-logo-beat {",
      "  0%, 100% { transform: scale(1); opacity: 0.85; }",
      "  50% { transform: scale(1.06); opacity: 1; }",
      "}",
    ],
  },
  {
    key: "ld-text",
    cat: "loading",
    ms: 700,
    label: { ja: "文字が1つずつ現れる", en: "Letters appear one by one" },
    html:
      '<div class="ld-text" role="status" aria-label="読み込み中">' +
      "<b>L</b><b>O</b><b>A</b><b>D</b><b>I</b><b>N</b><b>G</b>" +
      "</div>",
    css: [
      ...shell("ld-text", { base: "opacity 0.5s ease", done: "opacity: 0;", delay: "0.5s" }),
      ".ld-text { flex-direction: row; gap: 4px; }",
      ".ld-text b {",
      "  color: #fff; font-size: clamp(1.3rem, 1rem + 2vw, 2.2rem); font-weight: 800; letter-spacing: 0.1em;",
      "  opacity: 0; animation: ld-text-in 1.4s ease-in-out infinite;",
      "}",
      ".ld-text b:nth-child(2) { animation-delay: 0.1s; }",
      ".ld-text b:nth-child(3) { animation-delay: 0.2s; }",
      ".ld-text b:nth-child(4) { animation-delay: 0.3s; }",
      ".ld-text b:nth-child(5) { animation-delay: 0.4s; }",
      ".ld-text b:nth-child(6) { animation-delay: 0.5s; }",
      ".ld-text b:nth-child(7) { animation-delay: 0.6s; }",
      "@keyframes ld-text-in {",
      "  0% { opacity: 0; transform: translateY(8px); }",
      "  30%, 70% { opacity: 1; transform: translateY(0); }",
      "  100% { opacity: 0; transform: translateY(-8px); }",
      "}",
    ],
  },
  {
    key: "ld-typing",
    cat: "loading",
    ms: 550,
    label: { ja: "タイピング風", en: "Typewriter" },
    html: '<div class="ld-typing" role="status" aria-label="読み込み中"><b>Loading</b><span></span></div>',
    css: [
      ...shell("ld-typing", { base: "opacity 0.5s ease", done: "opacity: 0;", delay: "0.5s" }),
      ".ld-typing { flex-direction: row; gap: 4px; }",
      ".ld-typing b {",
      "  color: #fff; font-family: Consolas, Menlo, monospace; font-size: 1.3rem; font-weight: 700;",
      "  white-space: nowrap; overflow: hidden;",
      "  animation: ld-typing-in 2s steps(7, end) infinite;",
      "}",
      ".ld-typing span {",
      "  width: 3px; height: 1.4rem; background: #fff;",
      "  animation: ld-typing-caret 0.8s step-end infinite;",
      "}",
      "@keyframes ld-typing-in { 0% { width: 0; } 60%, 100% { width: 7ch; } }",
      "@keyframes ld-typing-caret { 0%, 50% { opacity: 1; } 51%, 100% { opacity: 0; } }",
    ],
  },
  {
    key: "ld-percent",
    cat: "loading",
    ms: 800,
    label: { ja: "0→100%にカウント", en: "Counts up to 100%" },
    html: '<div class="ld-percent" role="status" aria-label="読み込み中"><b></b></div>',
    css: [
      "/* @property 対応ブラウザ（Chrome/Edge/Safari/Firefox 最新）で数字が動く */",
      "/* inherits: true が必須。false だと ::after が親の値を受け取れず 0 のまま止まる */",
      "@property --ld-n { syntax: '<integer>'; initial-value: 0; inherits: true; }",
      ...shell("ld-percent", { base: "clip-path 0.75s cubic-bezier(0.76, 0, 0.24, 1)", done: "clip-path: circle(0% at 50% 50%);", delay: "0.75s" }),
      ".ld-percent { clip-path: circle(150% at 50% 50%); }",
      ".ld-percent b {",
      "  color: #fff; font-size: clamp(2rem, 1.4rem + 4vw, 4rem); font-weight: 800; font-variant-numeric: tabular-nums;",
      "  --ld-n: 0; animation: ld-percent-count 1.4s cubic-bezier(0.4, 0.2, 0.3, 1) forwards;",
      "}",
      '.ld-percent b::after { counter-reset: ld var(--ld-n); content: counter(ld) "%"; }',
      "@keyframes ld-percent-count { to { --ld-n: 100; } }",
    ],
  },
  {
    key: "ld-square",
    cat: "loading",
    ms: 650,
    label: { ja: "四角が回る", en: "Rotating square" },
    html: '<div class="ld-square" role="status" aria-label="読み込み中"><i></i></div>',
    css: [
      ...shell("ld-square", { base: "clip-path 0.6s cubic-bezier(0.76, 0, 0.24, 1)", done: "clip-path: inset(50% 0 50% 0);", delay: "0.6s" }),
      ".ld-square { clip-path: inset(0 0 0 0); }",
      ".ld-square i {",
      "  width: 42px; height: 42px; border-radius: 6px; background: #fff;",
      "  animation: ld-square-turn 1.2s cubic-bezier(0.65, 0, 0.35, 1) infinite;",
      "}",
      "@keyframes ld-square-turn {",
      "  0% { transform: rotate(0) scale(1); }",
      "  50% { transform: rotate(180deg) scale(0.7); border-radius: 50%; }",
      "  100% { transform: rotate(360deg) scale(1); }",
      "}",
    ],
  },
  {
    key: "ld-wave",
    cat: "loading",
    ms: 500,
    label: { ja: "バーが波打つ", en: "Bars ripple like an equalizer" },
    html: '<div class="ld-wave" role="status" aria-label="読み込み中"><i></i><i></i><i></i><i></i><i></i></div>',
    css: [
      ...shell("ld-wave", { base: "opacity 0.45s ease", done: "opacity: 0;", delay: "0.45s" }),
      ".ld-wave { flex-direction: row; align-items: flex-end; gap: 6px; }",
      ".ld-wave i {",
      "  width: 8px; height: 34px; border-radius: 99px; background: #fff;",
      "  animation: ld-wave-move 1s ease-in-out infinite;",
      "}",
      ".ld-wave i:nth-child(2) { animation-delay: 0.1s; }",
      ".ld-wave i:nth-child(3) { animation-delay: 0.2s; }",
      ".ld-wave i:nth-child(4) { animation-delay: 0.3s; }",
      ".ld-wave i:nth-child(5) { animation-delay: 0.4s; }",
      "@keyframes ld-wave-move {",
      "  0%, 100% { transform: scaleY(0.4); opacity: 0.6; }",
      "  50% { transform: scaleY(1); opacity: 1; }",
      "}",
    ],
  },
  {
    key: "ld-pulse",
    cat: "loading",
    ms: 650,
    label: { ja: "波紋が広がる", en: "Expanding ripples" },
    html: '<div class="ld-pulse" role="status" aria-label="読み込み中"><i></i><i></i></div>',
    css: [
      ...shell("ld-pulse", { base: "transform 0.6s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.6s ease", done: "transform: scale(1.3); opacity: 0;", delay: "0.6s" }),
      ".ld-pulse i {",
      "  position: absolute; width: 60px; height: 60px; border-radius: 50%;",
      "  border: 3px solid #fff; animation: ld-pulse-out 1.6s ease-out infinite;",
      "}",
      ".ld-pulse i:nth-child(2) { animation-delay: 0.8s; }",
      "@keyframes ld-pulse-out {",
      "  0% { transform: scale(0.4); opacity: 1; }",
      "  100% { transform: scale(2.2); opacity: 0; }",
      "}",
    ],
  },
  {
    key: "ld-skeleton",
    cat: "loading",
    ms: 500,
    label: { ja: "スケルトンUI風", en: "Skeleton screen" },
    html: '<div class="ld-skeleton" role="status" aria-label="読み込み中"><i></i><i></i><i></i></div>',
    css: [
      ...shell("ld-skeleton", { base: "opacity 0.45s ease", done: "opacity: 0;", delay: "0.45s" }),
      ".ld-skeleton { justify-content: flex-start; padding: 18% 12% 0; gap: 12px; background: #fff; }",
      ".ld-skeleton i {",
      "  width: 100%; height: 14px; border-radius: 99px;",
      "  background: linear-gradient(90deg, #e2e8f0 25%, #f1f5f9 37%, #e2e8f0 63%);",
      "  background-size: 400% 100%; animation: ld-skeleton-shine 1.4s ease infinite;",
      "}",
      ".ld-skeleton i:nth-child(2) { width: 76%; animation-delay: 0.12s; }",
      ".ld-skeleton i:nth-child(3) { width: 52%; animation-delay: 0.24s; }",
      "@keyframes ld-skeleton-shine { from { background-position: 100% 0; } to { background-position: 0 0; } }",
    ],
  },
  {
    key: "ld-minimal",
    cat: "loading",
    ms: 450,
    label: { ja: "上端の極細バーだけ", en: "Thin top bar only" },
    html: '<div class="ld-minimal" role="status" aria-label="読み込み中"><i></i></div>',
    css: [
      "/* 画面を覆わないタイプ。本文を隠さずに読み込み中だけ知らせる */",
      ".ld-minimal {",
      "  position: fixed; top: 0; left: 0; right: 0; height: 3px; z-index: 9999;",
      "  background: transparent; pointer-events: none;",
      "  visibility: visible; transition: opacity 0.4s ease, visibility 0s;",
      "}",
      ".ld-minimal.is-done {",
      "  opacity: 0; visibility: hidden;",
      "  transition: opacity 0.4s ease, visibility 0s linear 0.4s;",
      "}",
      ".ld-minimal i {",
      "  display: block; height: 100%; background: #ec4899;",
      "  transform-origin: left; animation: ld-minimal-fill 2s cubic-bezier(0.3, 0.9, 0.4, 1) forwards;",
      "}",
      "@keyframes ld-minimal-fill { from { transform: scaleX(0); } to { transform: scaleX(1); } }",
    ],
  },
];
