// ページ遷移：幕以外の演出（10種）
//
// 【共通の約束】カーテンと同じく「覆っている」が初期状態で、.is-open が付くと消える。
// 発火するJSも共通なので、カーテンと自由に差し替えられる。
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

const P1 = "<i></i>";
const P2 = "<i></i><i></i>";
const P5 = "<i></i><i></i><i></i><i></i><i></i>";

export const TRANSITION_EFFECTS = [
  {
    key: "pt-fade",
    cat: "transition",
    ms: 500,
    label: { ja: "フェード", en: "Fade" },
    html: '<div class="pt-fade" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-fade {",
      "  position: fixed; inset: 0; z-index: 9999;",
      "  pointer-events: auto;",
      "}",
      ".pt-fade.is-open { pointer-events: none; }",
      ".pt-fade i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  transition: opacity 0.5s ease;",
      "}",
      ".pt-fade.is-open i { opacity: 0; }",
    ],
  },
  {
    key: "pt-zoom",
    cat: "transition",
    ms: 600,
    label: { ja: "ズームアウトして消える", en: "Zooms out and vanishes" },
    html: '<div class="pt-zoom" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-zoom {",
      "  position: fixed; inset: 0; z-index: 9999;",
      "  pointer-events: auto;",
      "}",
      ".pt-zoom.is-open { pointer-events: none; }",
      ".pt-zoom i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  transition: transform 0.6s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.6s ease;",
      "}",
      ".pt-zoom.is-open i { transform: scale(1.5); opacity: 0; }",
    ],
  },
  {
    key: "pt-blur",
    cat: "transition",
    ms: 600,
    label: { ja: "ぼかしが晴れて消える", en: "Blurs away" },
    html: '<div class="pt-blur" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-blur {",
      "  position: fixed; inset: 0; z-index: 9999;",
      "  pointer-events: auto;",
      "}",
      ".pt-blur.is-open { pointer-events: none; }",
      ".pt-blur i {",
      "  position: absolute; inset: -5%; background: #6366f1;",
      "  transition: filter 0.6s ease, opacity 0.6s ease;",
      "}",
      ".pt-blur.is-open i { filter: blur(40px); opacity: 0; }",
    ],
  },
  {
    key: "pt-wipe",
    cat: "transition",
    ms: 650,
    label: { ja: "色面が横切る", en: "Color panel sweeps across" },
    html: '<div class="pt-wipe" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-wipe {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-wipe.is-open { pointer-events: none; }",
      ".pt-wipe i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  transform-origin: right;",
      "  transition: transform 0.65s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      "/* 右端を軸に畳むので、面が左から右へ拭き取られるように見える */",
      ".pt-wipe.is-open i { transform: scaleX(0); }",
    ],
  },
  {
    key: "pt-double",
    cat: "transition",
    ms: 800,
    label: { ja: "2色の面が続けて横切る", en: "Two colors sweep in turn" },
    html: '<div class="pt-double" aria-hidden="true">' + P2 + "</div>",
    css: [
      ".pt-double {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-double.is-open { pointer-events: none; }",
      ".pt-double i {",
      "  position: absolute; inset: 0; transform-origin: right;",
      "  transition: transform 0.6s cubic-bezier(0.76, 0, 0.24, 1);",
      "}",
      ".pt-double i:nth-child(1) { background: #ec4899; }",
      ".pt-double i:nth-child(2) { background: #6366f1; }",
      ".pt-double.is-open i:nth-child(2) { transform: scaleX(0); }",
      ".pt-double.is-open i:nth-child(1) { transform: scaleX(0); transition-delay: 0.18s; }",
    ],
  },
  {
    key: "pt-blinds",
    cat: "transition",
    ms: 800,
    label: { ja: "ブラインドが回って開く", en: "Blinds rotate open" },
    html: '<div class="pt-blinds" aria-hidden="true">' + P5 + "</div>",
    css: [
      ".pt-blinds {",
      "  position: fixed; inset: 0; z-index: 9999; display: flex; flex-direction: column;",
      "  perspective: 1200px;",
      "  pointer-events: auto;",
      "}",
      ".pt-blinds.is-open { pointer-events: none; }",
      ".pt-blinds i {",
      "  flex: 1; background: #6366f1;",
      "  transform-origin: center; backface-visibility: hidden;",
      "  transition: transform 0.55s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.55s ease;",
      "}",
      ".pt-blinds.is-open i { transform: rotateX(90deg); opacity: 0; }",
      ".pt-blinds.is-open i:nth-child(2) { transition-delay: 0.06s; }",
      ".pt-blinds.is-open i:nth-child(3) { transition-delay: 0.12s; }",
      ".pt-blinds.is-open i:nth-child(4) { transition-delay: 0.18s; }",
      ".pt-blinds.is-open i:nth-child(5) { transition-delay: 0.24s; }",
    ],
  },
  {
    key: "pt-shrink",
    cat: "transition",
    ms: 650,
    label: { ja: "幕が縮んで消える", en: "Sheet shrinks away" },
    html: '<div class="pt-shrink" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-shrink {",
      "  position: fixed; inset: 0; z-index: 9999;",
      "  display: flex; align-items: center; justify-content: center;",
      "  pointer-events: auto;",
      "}",
      ".pt-shrink.is-open { pointer-events: none; }",
      ".pt-shrink i {",
      "  width: 100%; height: 100%; background: #6366f1; border-radius: 0;",
      "  transition: transform 0.65s cubic-bezier(0.65, 0, 0.35, 1), border-radius 0.65s ease, opacity 0.3s ease 0.35s;",
      "}",
      ".pt-shrink.is-open i { transform: scale(0.05); border-radius: 50%; opacity: 0; }",
    ],
  },
  {
    key: "pt-rotate",
    cat: "transition",
    ms: 750,
    label: { ja: "幕が回りながら消える", en: "Sheet spins away" },
    html: '<div class="pt-rotate" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-rotate {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-rotate.is-open { pointer-events: none; }",
      ".pt-rotate i {",
      "  position: absolute; inset: -30%; background: #6366f1;",
      "  transition: transform 0.75s cubic-bezier(0.65, 0, 0.35, 1), opacity 0.5s ease 0.25s;",
      "}",
      ".pt-rotate.is-open i { transform: rotate(25deg) scale(1.6) translateY(-140%); opacity: 0; }",
    ],
  },
  {
    key: "pt-logo",
    cat: "transition",
    ms: 900,
    label: { ja: "ロゴが出てから開く", en: "Logo shows, then opens" },
    html: '<div class="pt-logo" aria-hidden="true"><i></i><b>LOGO</b></div>',
    css: [
      ".pt-logo {",
      "  position: fixed; inset: 0; z-index: 9999;",
      "  display: flex; align-items: center; justify-content: center;",
      "  pointer-events: auto;",
      "}",
      ".pt-logo.is-open { pointer-events: none; }",
      ".pt-logo i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "  transform-origin: top;",
      "  transition: transform 0.5s cubic-bezier(0.76, 0, 0.24, 1) 0.35s;",
      "}",
      "/* 文字が消えてから幕が上がる（transition-delay で順番を作る） */",
      ".pt-logo b {",
      "  position: relative; color: #fff;",
      "  font-size: clamp(1.5rem, 1rem + 3vw, 3rem); font-weight: 800; letter-spacing: 0.2em;",
      "  transition: opacity 0.35s ease, transform 0.35s ease;",
      "}",
      ".pt-logo.is-open i { transform: scaleY(0); }",
      ".pt-logo.is-open b { opacity: 0; transform: scale(0.9); }",
    ],
  },
  {
    key: "pt-glitch",
    cat: "transition",
    ms: 800,
    label: { ja: "グリッチ風に消える", en: "Glitches out" },
    html: '<div class="pt-glitch" aria-hidden="true">' + P1 + "</div>",
    css: [
      ".pt-glitch {",
      "  position: fixed; inset: 0; z-index: 9999; overflow: hidden;",
      "  pointer-events: auto;",
      "}",
      ".pt-glitch.is-open { pointer-events: none; }",
      ".pt-glitch i {",
      "  position: absolute; inset: 0; background: #6366f1;",
      "}",
      ".pt-glitch.is-open i { animation: pt-glitch-out 0.8s steps(1, end) forwards; }",
      "@keyframes pt-glitch-out {",
      "  0% { clip-path: inset(0 0 0 0); transform: translateX(0); }",
      "  15% { clip-path: inset(0 0 62% 0); transform: translateX(-3%); }",
      "  30% { clip-path: inset(38% 0 24% 0); transform: translateX(4%); background: #ec4899; }",
      "  45% { clip-path: inset(70% 0 8% 0); transform: translateX(-5%); }",
      "  60% { clip-path: inset(12% 0 78% 0); transform: translateX(3%); background: #ec4899; }",
      "  75% { clip-path: inset(88% 0 4% 0); transform: translateX(-2%); }",
      "  100% { clip-path: inset(100% 0 0 0); transform: translateX(0); }",
      "}",
    ],
  },
];
