// 英語版：パターンの名前・使いどころ・設計の狙い・構成（id ごと）
export const CATEGORY_EN = {
  header: "Header",
  hero: "Hero",
  features: "Features",
  cases: "Case Studies & Testimonials",
  cards: "Card Lists",
  steps: "Steps & Flow",
  pricing: "Pricing",
  faq: "FAQ",
  cta: "CTA",
  form: "Contact Forms",
  company: "About & Access",
  footer: "Footer",
};

export const META_EN = {
  hd01: {
    name: "Logo left, nav right, CTA button",
    use: "The standard for corporate and service sites",
    intent: "Eyes travel from the top left to the right, so the logo says whose site this is before guiding visitors to the nav and CTA. Only the CTA is a filled button, so the one action you want stands out.",
    parts: ["Logo (left)", "Global nav with 4 items", "CTA button (far right)", "On mobile, the nav collapses into a hamburger"],
  },
  hd02: {
    name: "Centered logo, nav on a second row",
    use: "Media, brand and shop sites",
    intent: "A large centered logo puts the brand front and center. The nav sits on its own row, so it stays comfortable even with many categories.",
    parts: ["Search icon (left)", "Logo (center)", "Button (right)", "Category nav with 6 items on the second row"],
  },
  hd03: {
    name: "Phone bar on top + main header",
    use: "Shops, clinics and B2B businesses that get inquiries by phone",
    intent: "The phone number and opening hours stay in a slim top bar, so contact details are visible on every page. The main header keeps its usual nav and CTA, splitting the roles across two rows.",
    parts: ["Top bar: opening hours and phone number", "Logo", "Nav with 4 items", "Booking button", "On mobile, a call button and hamburger"],
  },
  hd04: {
    name: "Left-aligned nav + log in and sign up",
    use: "SaaS and membership services",
    intent: "\"Log in\" for existing users and \"Sign up\" for new ones sit side by side at the right, so both find their way in. Only sign-up, the main goal, is a filled button.",
    parts: ["Logo", "Nav with 4 items (next to the logo)", "Log in (text link)", "Sign up (filled button)"],
  },
  hd05: {
    name: "With a search bar (for e-commerce)",
    use: "Online stores with large catalogs",
    intent: "For visitors who come to search, a wide search bar takes the center of the header. Favorites and cart are grouped as icons on the right, and a category row below serves people who prefer to browse.",
    parts: ["Logo", "Search bar (center, widest)", "Icons: favorites, account, cart", "Category nav on the second row", "On mobile, the search bar moves to its own row"],
  },
  hd06: {
    name: "Mega menu (open)",
    use: "Company sites with many products or services",
    intent: "Hovering a nav item opens a large panel listing subpages by group, so visitors jump straight to the page they want without digging through levels. The right side of the panel holds featured content.",
    parts: ["Regular header (logo, nav, CTA)", "Open panel: group headings + links in 3 columns", "Panel right: featured image and link"],
  },
  fv01: {
    name: "Centered headline + two buttons",
    use: "Service landing pages and app home pages",
    intent: "No image needed: the headline and one sentence state the value. Two buttons only, a primary (sign up) and a secondary (brochure or details), give undecided visitors a softer next step.",
    parts: ["Eyebrow label", "Main headline", "1–2 lines of description", "Primary + secondary button", "Product screenshot below"],
  },
  fv02: {
    name: "Text left, image right",
    use: "The classic for service and product sites",
    intent: "Text on the left and an image on the right show what it does and what it looks like at the same time. On mobile, the image moves below so the headline is read first.",
    parts: ["Headline", "Description", "CTA button", "Reassurance line (free, no card needed)", "Image (right)"],
  },
  fv03: {
    name: "Full-bleed background image + overlaid text",
    use: "Brand sites, careers pages, hotels and restaurants",
    intent: "The photo sets the mood and makes the first impression. Because text sits on top of the image, a dark overlay keeps it readable.",
    parts: ["Full-bleed background image", "Dark overlay", "Tagline (bottom left)", "Sub copy", "One button"],
  },
  fv04: {
    name: "Pitch left, form right",
    use: "Lead-generation pages for brochures and free consultations",
    intent: "The form is visible without scrolling, so signing up takes one screen. The pitch on the left gives the reason to sign up; the form on the right shows it takes a moment.",
    parts: ["Headline", "3 benefits (bullets)", "Form: name, email, company", "Submit button", "Privacy note"],
  },
  fv05: {
    name: "Headline + key numbers + customer logos",
    use: "B2B services and products chosen on track record",
    intent: "Numbers and logos show how widely it's used right away, answering first-visit doubts before they form. Keep it to three numbers, with the strongest on the left.",
    parts: ["Headline", "Description", "CTA button", "3 key numbers", "6 customer logos"],
  },
  fv06: {
    name: "Split screen",
    use: "Fashion, beauty, portfolios and other photo-led businesses",
    intent: "Half the screen goes to the photo and half to text, balancing visual impact with readability. Few elements on the text side, with plenty of space, give an elegant feel.",
    parts: ["Left half: image (to the screen edge)", "Right half: label, headline, description, button", "On mobile, the image goes on top"],
  },
  fv07: {
    name: "Slider (rotating messages)",
    use: "Stores, venues and public bodies running several campaigns",
    intent: "When you have several messages, show them one slide at a time. Later slides get far fewer views, so put the most important one first and keep it to 3–5 slides.",
    parts: ["Slide image (with overlaid text)", "Left and right arrows", "Dots below", "A button per slide"],
  },
  fv08: {
    name: "Search form as the hero",
    use: "Search sites for real estate, jobs or travel",
    intent: "Visitors come to search, so let them enter criteria right in the hero. Keep it to 2–3 fields and leave detailed filters to the results page.",
    parts: ["Background image", "Headline", "Search panel: area, type (selects), keyword, search button", "Popular searches below"],
  },
  fa01: {
    name: "Icon + heading + text in 3 columns",
    use: "The basic feature section for service sites and landing pages",
    intent: "Three features side by side give the full picture at a glance. Icon, short heading and about two lines of text in the same order make the differences clear even when skimming.",
    parts: ["Section heading", "3 feature cards (icon, heading, text)"],
  },
  fa02: {
    name: "Alternating image and text rows",
    use: "Product pages that explain features one by one",
    intent: "Each feature gets an image and a description, stacked with sides alternating. The zigzag avoids monotony and builds understanding one feature at a time as you scroll.",
    parts: ["Section heading", "3 feature blocks (number, heading, text, image)", "Image side alternates left and right"],
  },
  fa03: {
    name: "Problems → solutions",
    use: "Problem-solving services and B2B products",
    intent: "Listing the reader's problems first makes them think \"that's me\", then each problem is answered one to one. Starting from empathy feels more personal than a list of features.",
    parts: ["Section heading", "Left: 3 common problems", "Right: a solution for each", "Arrow between them"],
  },
  fa04: {
    name: "Large numbered list (key points)",
    use: "Schools, consultants and services that need longer explanations",
    intent: "A big number for each point splits the content into steps read top to bottom. Seeing \"three in total\" sets expectations, so long explanations get read to the end.",
    parts: ["Section heading", "3 points (large number, heading, text)", "Divider lines"],
  },
  fa05: {
    name: "By the numbers",
    use: "Company profiles, careers pages and services with measurable results",
    intent: "Big numbers convey scale and results faster than words. A short label under each says what it measures; add the date or source where needed.",
    parts: ["Section heading", "4 number blocks (large number, unit, label)", "Note (as of month/year)"],
  },
  fa06: {
    name: "Six small benefit cards (grid)",
    use: "Feature-rich SaaS, tools and membership perks",
    intent: "When there are many small benefits, put an icon and a short line in small cards on a grid. Keeping each one short lets visitors scan it as a list of what they can do.",
    parts: ["Section heading", "6 cards (icon left, heading and one line right)"],
  },
  cs01: {
    name: "Three testimonial cards",
    use: "Service sites, schools and shops",
    intent: "Customers' own words add trust your copy alone can't create. A photo and company or role make it read as a real person's voice.",
    parts: ["Section heading", "3 testimonial cards (quote, photo, role, name)"],
  },
  cs02: {
    name: "Case studies with results",
    use: "B2B services, consulting and ad management",
    intent: "Each case pairs the problem before with the result in numbers, so prospects can picture the impact for their own business. The number is the biggest element on the card.",
    parts: ["Section heading", "2 case cards (image, industry, company, result, one-line summary)", "Link to all cases"],
  },
  cs03: {
    name: "Customer logo wall",
    use: "B2B services that can name their customers",
    intent: "Seeing companies you know builds trust on its own. Logos in same-size boxes show volume, and only those who want details move on to the case studies.",
    parts: ["Heading (with customer count)", "12 logo boxes (4 × 3)", "Link to case studies"],
  },
  cs04: {
    name: "Interview teaser (large photo + quote)",
    use: "Case studies, employee interviews and alumni stories",
    intent: "One story shown with a large photo and a striking line, with the full story on its own page. Pick the most compelling quote from the interview.",
    parts: ["Left: large photo", "Right: quote, company and name, button to the article", "Below: 3 small links to other stories"],
  },
  cs05: {
    name: "Star rating and reviews",
    use: "E-commerce, apps, schools and restaurants",
    intent: "The average rating and review count show overall reputation first, with individual reviews below. Specific experiences, not just praise, make the rating itself more credible.",
    parts: ["Left: average rating (number, stars), review count, bars per star level", "Right: 3 review cards (stars, title, text, reviewer)"],
  },
  cd01: {
    name: "Three-column article grid",
    use: "Blogs, news and column listings",
    intent: "Thumbnail, category, date and title in that order let readers pick by look and freshness. Titles capped at two lines keep the cards an even height.",
    parts: ["Heading + link to all", "6 article cards (image, category, date, title)"],
  },
  cd02: {
    name: "Horizontal product scroller",
    use: "E-commerce recommendations, related items and rankings",
    intent: "More products than fit the screen flow sideways, showing plenty without adding height. A partly cut-off last card signals there's more and invites a swipe.",
    parts: ["Heading + prev/next buttons", "6 product cards (image, name, price) in a horizontal scroll"],
  },
  cd03: {
    name: "List with thumbnail left, text right",
    use: "Blog archives, search results and news",
    intent: "One item per row gives room for the title and excerpt. It carries more information than a grid and suits lists where people choose by reading.",
    parts: ["4 articles (thumbnail left; category, date, title, excerpt right)", "Pagination below"],
  },
  cd04: {
    name: "One large + four small",
    use: "Media home pages, features and news highlights",
    intent: "The article you most want read is large and the rest are small, showing priority visually. It tells readers where to start better than a grid of equal cards.",
    parts: ["Left: large article card (image, category, title, excerpt)", "Right: 4 small articles (thumbnail, title)"],
  },
  cd05: {
    name: "Product grid (with badges and favorites)",
    use: "E-commerce product listings and category pages",
    intent: "Product images lead in four columns, with price, rating and badges (new, sale) in fixed spots for easy comparison. A favorite button gives a place for \"buy later\".",
    parts: ["Top: item count and sort", "8 product cards (image, badge, favorite, name, price, rating)"],
  },
  cd06: {
    name: "News list in rows",
    use: "Company news and press releases",
    intent: "No images: date, category and title on one line show many items at once. How often and how recently you post is clear at a glance, so the site feels active.",
    parts: ["Heading + link to all", "5 news items (date, category, title)", "Whole row is a link"],
  },
  st01: {
    name: "Horizontal steps (with arrows)",
    use: "How to sign up or get started",
    intent: "Up to four steps side by side make it feel easy to start. Numbers and icons show the order, and arrows between steps emphasize the flow.",
    parts: ["Section heading", "4 steps (number, icon, heading, text)", "Arrows between steps"],
  },
  st02: {
    name: "Vertical timeline",
    use: "Project phases up to delivery and how a service works",
    intent: "Phases on a single vertical line, each with its duration. Seeing the total timeline and what the customer needs to do eases pre-inquiry worries about when and what.",
    parts: ["Section heading", "4 phases (number, duration, heading, text)", "Connected by a vertical line on the left"],
  },
  st03: {
    name: "Steps with screenshots",
    use: "How-to guides for apps, settings and sign-up",
    intent: "A real screenshot for each step lets readers follow along by comparing with their own screen. Number, heading, text and image in the same order every time keeps them on track.",
    parts: ["Section heading", "3 steps (number, heading, text, screenshot)", "Image on the right; below the text on mobile"],
  },
  st04: {
    name: "Progress indicator above a form",
    use: "Multi-page forms for sign-up, checkout or registration",
    intent: "Showing where you are and how many screens are left reduces drop-off. Only the current step is filled, and completed steps get a check mark.",
    parts: ["4 steps (number, name) in a row", "Different looks for done, current and upcoming", "Steps connected by a line"],
  },
  pr01: {
    name: "Three plans, middle one recommended",
    use: "The basic for SaaS, subscriptions and courses",
    intent: "With three options, people tend to pick the middle one. Put the plan you want to sell in the center and highlight it with a border and badge. A one-line \"best for\" on each plan helps people choose.",
    parts: ["Heading + note", "3 plan cards", "\"Recommended\" badge on the middle plan", "Price, who it's for, 3 features, button"],
  },
  pr02: {
    name: "Monthly / yearly toggle",
    use: "Subscriptions with an annual discount",
    intent: "The toggle sits right above the plans, with a label showing the yearly saving to nudge annual billing. Defaulting to yearly means the lower price is the first one seen.",
    parts: ["Heading", "Monthly / yearly toggle (discount label on yearly)", "3 plan cards"],
  },
  pr03: {
    name: "Feature comparison table",
    use: "Services with many differences between plans",
    intent: "A table with features as rows and plans as columns lists the differences in one place, for people who want details cards can't hold. On mobile, the table scrolls sideways with the feature column fixed.",
    parts: ["Heading", "Table: 3 plans as columns, 6 features as rows", "Differences shown as ○ / − / values", "A button for each plan in the last row"],
  },
  pr04: {
    name: "Single price + what's included",
    use: "Single-price products, courses and one-time purchases",
    intent: "No choices, no hesitation. Everything included sits next to the price, so value is judged by what you get. Reassurance like a refund guarantee goes under the button.",
    parts: ["Heading", "Left: price, button, guarantee line", "Right: checklist of 6 included items"],
  },
  pr05: {
    name: "Usage-based price calculator",
    use: "Pay-as-you-go cloud services, APIs and per-seat SaaS",
    intent: "Unit prices alone don't show the total, so adjusting usage shows the monthly cost on the spot. Knowing \"what it costs me\" reduces drop-off before inquiry.",
    parts: ["Heading", "Left: 2 usage sliders (seats, volume)", "Right: monthly total and breakdown", "Link to the unit price list"],
  },
  pr06: {
    name: "Base price + options list",
    use: "Quote-based services such as design, repair, cleaning or lessons",
    intent: "The base price that always applies is shown large, and add-on options are listed in a table. Seeing how the total adds up answers \"so what will it cost in the end?\" in advance.",
    parts: ["Heading", "Base price card (price, what's included)", "Options table (item, details, price)", "Note (tax, travel fees, etc.)"],
  },
  fq01: {
    name: "Accordion",
    use: "FAQs with many questions; easing doubts before sign-up",
    intent: "Only questions are listed for easy scanning, and readers open the ones they care about. It uses the details element, so it opens and closes without JavaScript and closed answers are still read by search engines.",
    parts: ["Heading", "5 questions (Q, question, open/close mark)", "Answer (A) under the open question"],
  },
  fq02: {
    name: "All questions and answers in two columns",
    use: "Short FAQs (around 6 questions) near the end of a landing page",
    intent: "No toggling: every answer is visible from the start. With few questions, skipping the clicks and letting people skim causes less drop-off.",
    parts: ["Left: heading and contact link", "Right: all 4 question-answer pairs shown"],
  },
  fq03: {
    name: "Category tabs",
    use: "Services and stores with more than 20 questions",
    intent: "Questions are grouped by category and switched with tabs. Listing everything buries the one people need, so they first choose the kind of question to narrow it down.",
    parts: ["Heading", "4 category tabs (pricing, usage, contract, other)", "Questions for the selected tab (accordion)"],
  },
  fq04: {
    name: "Help center entrance with search",
    use: "Support pages for SaaS and membership services",
    intent: "People with a problem want to search in their own words, so the search bar comes first. Category cards and popular questions below give an entrance for those who don't search.",
    parts: ["Heading + search bar", "6 category cards (icon, name, count)", "4 popular questions", "Contact link if not solved"],
  },
  ct01: {
    name: "Centered band + one button",
    use: "Between sections and mid-page",
    intent: "A short band within the content lets readers act the moment they're convinced. One button only, so there's nothing to decide.",
    parts: ["Heading", "One line", "One button", "Note under the button (free, 1 minute)"],
  },
  ct02: {
    name: "Two choices (start now / talk first)",
    use: "B2B and high-ticket products with buyers at different stages",
    intent: "Separate entrances for those ready to start and those still deciding. Two cards each say who they're for, so undecided visitors aren't lost.",
    parts: ["Heading", "Left card: for those ready now (filled button)", "Right card: for those who want to talk (outline button)"],
  },
  ct03: {
    name: "Band with image, split layout",
    use: "Brochure downloads, white papers and newsletter sign-ups",
    intent: "Showing the thing they'll get (a guide or bonus) makes it concrete. Image on the left; key points and a button on the right.",
    parts: ["Left: image of the guide or bonus", "Right: heading, 3 key points, button"],
  },
  ct04: {
    name: "Sticky CTA bar at the bottom",
    use: "Mobile-first landing pages and shops where booking or calling is the goal",
    intent: "Buttons stay at the bottom of the screen while scrolling, within reach the moment someone wants to act. Two buttons at most, and keep the bar short so it doesn't crowd the screen.",
    parts: ["Bar: a short line on the left, 2 buttons on the right (call, book)", "Fixed to the bottom (position: sticky / fixed)", "On mobile, only full-width buttons"],
  },
  ct05: {
    name: "Email-only sign-up form",
    use: "Free SaaS sign-ups, waitlists and newsletters",
    intent: "One field, and sign-up finishes inside the band. Fewer fields means less drop-off; ask for a name after they've signed up.",
    parts: ["Heading", "One line", "Email field + sign-up button (side by side)", "Note (no spam, unsubscribe anytime)"],
  },
  fm01: {
    name: "Basic single-column form",
    use: "Contact forms for corporate and service sites",
    intent: "Fields in one column are filled top to bottom. Required and optional are marked next to each label, and only what's needed to reply is asked, reducing drop-off.",
    parts: ["Heading + note", "Inquiry type (select)", "Name, email, phone (optional)", "Message (multi-line)", "Privacy policy consent", "Submit button"],
  },
  fm02: {
    name: "Contact details left, form right",
    use: "Shops, professional services and B2B that also take calls",
    intent: "Some people would rather call, so the phone number and hours on the left let them choose. A link to the FAQ also cuts down on inquiries.",
    parts: ["Left: phone number, hours, FAQ link", "Right: form (name, email, message, submit)"],
  },
  fm03: {
    name: "Review before submitting",
    use: "Applications and bookings that should be checked before sending",
    intent: "Listing the entered details before sending gives a chance to catch mistakes. \"Go back and edit\" and \"Submit\" sit side by side, with only Submit filled.",
    parts: ["Progress (enter → review → done)", "Heading", "Entered details (field, value)", "Back button + submit button"],
  },
  fm04: {
    name: "Address form (two-column fields)",
    use: "E-commerce, mailing brochures and account sign-up",
    intent: "Related fields such as first and last name, or postal code and an autofill button, sit side by side to keep the form short. Labels on the left make progress easy to see.",
    parts: ["Labels left, fields right in a table layout", "First and last name side by side", "Phone and email side by side", "Postal code + address autofill button", "State (select), city and street, apartment", "Next button"],
  },
  fm05: {
    name: "Booking form with date and time",
    use: "Bookings for salons, clinics, consultations and lessons",
    intent: "Picking a date on the calendar shows that day's open times as buttons. Full slots look unavailable, so only open times can be chosen.",
    parts: ["Left: month calendar (selected day highlighted, full days dimmed)", "Right: time slot buttons for that day (full slots disabled)", "Below: name, phone, book button"],
  },
  co01: {
    name: "Company profile table",
    use: "Company information pages",
    intent: "Basic facts people check before doing business, such as name, address, founding date and CEO, go in one table. Equal label widths make it easy to read down.",
    parts: ["Heading", "Table: company name, address, founded, CEO, capital, employees, business, bank"],
  },
  co02: {
    name: "Map and directions",
    use: "Access pages for shops, offices and venues",
    intent: "A map alone doesn't give directions, so add how to get there from the nearest station and how long it takes. Train and car information side by side lets people read what applies to them.",
    parts: ["Left: large map", "Right: address, directions from the station, parking", "Open in Google Maps link"],
  },
  co03: {
    name: "Message from the CEO",
    use: "Company profiles, careers pages and greetings from a practice owner",
    intent: "A photo and the person's own words show who runs the company. A one-line headline opens, 3–4 paragraphs share the thinking behind the business, and a signature closes.",
    parts: ["Left: photo of the CEO", "Right: one-line headline, 3 paragraphs, title and signature"],
  },
  co04: {
    name: "Company history (timeline)",
    use: "Company information, brand stories and anniversary sites",
    intent: "Years and events in two columns, stacked vertically, show the history at a glance. Years align in a fixed-width column; each event is a single line.",
    parts: ["Heading", "6 timeline rows (year, event)", "Years connected by a vertical line"],
  },
  ft01: {
    name: "Simple one-line footer",
    use: "Landing pages and small sites",
    intent: "On a landing page, keep exits to a minimum: only the needed links (company, terms, privacy) on one line. With little content, generous spacing marks the end.",
    parts: ["Logo", "3 links (about, terms, privacy)", "Copyright"],
  },
  ft02: {
    name: "Logo + description + four link columns",
    use: "Corporate sites and larger sites",
    intent: "As a table of contents for the whole site, links are grouped into columns by category. People who reach the end of a page can find what to read next.",
    parts: ["Left: logo, one-line company intro, social icons", "Right: 4 link columns (3–4 links each)", "Bottom: copyright"],
  },
  ft03: {
    name: "Final CTA band + footer",
    use: "Closing a service site or landing page",
    intent: "A sign-up band right before the footer lets people act once they've finished reading. It catches those who missed the CTAs in the content.",
    parts: ["CTA band: heading, one line, 2 buttons", "Footer: logo, links, copyright"],
  },
  ft04: {
    name: "Shop details and map",
    use: "Restaurants, salons, clinics and other walk-in businesses",
    intent: "The location, hours and contact details people check before visiting are gathered in the footer, in the same place on every page.",
    parts: ["Left: logo, address, hours, closed days, phone", "Right: map", "Bottom: links and copyright"],
  },
  ft05: {
    name: "Newsletter and social first",
    use: "Media, personal brands and D2C brands",
    intent: "Turn readers into newsletter subscribers or followers so they come back. The sign-up field sits at the top of the footer, with one line saying what they'll receive.",
    parts: ["Top: newsletter heading, note, email field, sign-up button", "4 social icons", "Bottom: links and copyright"],
  },
};
