// 英語版：パターンの HTML／CSS コメント内の文言（タグに挟まれた文字列単位で完全一致させて置き換える）
export const TEXT_EN = {
  // 共通
  "商品名が入ります": "Product name",
  "必須": "Required",
  "任意": "Optional",
  "リンク": "Link",
  "カテゴリ": "Category",
  "＋": "+",
  "回答が入ります。結論を先に書き、必要なら補足を続けます。": "The answer goes here. Lead with the short answer, then add details if needed.",
  "お問い合わせ": "Contact us",
  "（税込）": "(incl. tax)",
  "/月": "/mo",
  "料金": "Pricing",
  "お名前": "Name",
  "メールアドレス": "Email",
  "一文で説明が入ります。": "A one-line description.",
  "記事タイトルが入ります。2行までに収める": "Article title goes here, two lines max",
  "このプランが合う人の説明": "Who this plan is for",
  "機能・特典1": "Feature or perk 1",
  "機能・特典2": "Feature or perk 2",
  "機能・特典3": "Feature or perk 3",
  "このプランにする": "Choose this plan",
  "00件": "00 articles",
  "よくある質問": "FAQ",
  "株式会社〇〇 様": "Company Name",
  "プライバシーポリシー": "Privacy policy",
  "0000年": "0000",
  "メニュー": "Menu",
  "会社名": "Company",
  "選択してください ▾": "Select ▾",
  "記事タイトルが入ります": "Article title goes here",
  "記事の抜粋が入ります。最初の2行ほどを表示して、続きは記事ページで読ませます。": "The article excerpt goes here. Show the first two lines or so, and let the rest be read on the article page.",
  "記事タイトルが入ります。2行までに収めます": "Article title goes here, two lines max",
  "お知らせのタイトルが入ります": "News title goes here",
  "このステップで何をするかの説明が入ります。": "What happens in this step.",
  "このステップの内容と、お客様にしていただくことの説明が入ります。": "What happens in this phase and what we'll need from you.",
  "料金についての補足文が入ります。": "A note about pricing goes here.",
  "内容の説明が入ります": "Details go here",
  "サービス名": "Service",
  "導入事例": "Case studies",
  "検索": "Search",
  "送信する": "Submit",
  "特長の説明が入ります。2行程度で具体的に書きます。": "Describe the feature in about two concrete lines.",
  "特長の説明が入ります。どんな場面で役に立つのかを、画像と合わせて伝えます。": "Describe the feature and, with the image, show when it helps.",
  "理由の説明が入ります。根拠となる事実や数字を添えて、3〜4行程度で具体的に書きます。": "Explain the reason in 3–4 concrete lines, backed by facts or numbers.",
  "「お客様の声が入ります。導入して何が変わったのかを、具体的な言葉で書きます。」": "\"The customer's words go here: what changed after they started, in concrete terms.\"",
  "会社名・役職": "Company, Role",
  "レビューのタイトル": "Review title",
  "具体的な体験談が入ります。使った場面と良かった点を書いてもらいます。": "A specific experience goes here: when they used it and what they liked.",
  "お知らせ": "News",
  "この手順で押すボタンや入力する内容を、画面と対応づけて説明します。": "Explain which button to press or what to enter in this step, matched to the screenshot.",
  "選ぶ": "Choose",
  "電話番号": "Phone",
  "お問い合わせ内容": "Message",
  "会社概要": "About us",
  "&copy; 2026 会社名": "&copy; 2026 Company",
  "イベント": "Events",
  "店舗名": "Shop Name",
  "アクセス": "Access",
  "電話する": "Call",
  "採用": "Careers",
  "無料ではじめる": "Start for free",
  "資料をダウンロード": "Download brochure",
  "詳しく見る": "Learn more",
  "継続率": "Retention",
  "前へ": "Previous",
  "次へ": "Next",
  "選ばれる理由": "Why customers choose us",
  "特長の見出し1": "Feature heading 1",
  "特長の見出し2": "Feature heading 2",
  "特長の見出し3": "Feature heading 3",
  "都道府県": "State",
  "業種": "Industry",
  "導入前の課題と、どう解決したかの要約が入ります。": "A summary of the challenge before and how it was solved.",
  "使い方": "Using the product",
  "料金プラン": "Pricing plans",
  "おすすめ": "Recommended",
  "プロ": "Pro",
  "利用人数": "Users",
  "1人": "1",
  "サポート": "Support",
  "メール": "Email",
  "基本料金": "Base price",
  "お問い合わせの種類": "Inquiry type",
  "山田 太郎": "Jane Smith",
  "〒000-0000 〇〇県〇〇市〇〇 0-0-0": "000 Main Street, City, State 00000",
  "利用規約": "Terms of service",

  // ヘッダー
  "特長": "Features",
  "無料で試す": "Try for free",
  "ブランド名": "Brand",
  "ニュース": "News",
  "コラム": "Columns",
  "インタビュー": "Interviews",
  "ショップ": "Shop",
  "私たちについて": "About us",
  "受付時間 9:00〜18:00（土日祝休み）": "Open 9:00–18:00 (closed weekends and holidays)",
  "診療案内": "Services",
  "医師紹介": "Our doctors",
  "WEB予約": "Book online",
  "プロダクト名": "Product",
  "機能": "Features",
  "ブログ": "Blog",
  "ヘルプ": "Help",
  "ログイン": "Log in",
  "新規登録": "Sign up",
  "ショップ名": "Shop",
  "キーワードで探す": "Search by keyword",
  "お気に入り": "Favorites",
  "マイページ": "Account",
  "カート": "Cart",
  "新着": "New",
  "カテゴリA": "Category A",
  "カテゴリB": "Category B",
  "カテゴリC": "Category C",
  "セール": "Sale",
  "ランキング": "Best sellers",
  "製品・サービス ▾": "Products ▾",
  "企業情報": "Company",
  "分類A": "Group A",
  "製品名1": "Product 1",
  "製品名2": "Product 2",
  "製品名3": "Product 3",
  "分類B": "Group B",
  "製品名4": "Product 4",
  "製品名5": "Product 5",
  "製品名6": "Product 6",
  "分類C": "Group C",
  "製品名7": "Product 7",
  "製品名8": "Product 8",
  "注目のお知らせ →": "Featured news →",

  // ファーストビュー
  "ラベルテキスト": "Eyebrow label",
  "サービスの価値をひとことで": "A headline that states",
  "伝える見出し": "your value in one line",
  "誰の、どんな悩みを、どう解決するのかを1〜2行で説明する文章が入ります。": "One or two lines on who it's for, what problem it solves and how.",
  "見出しが入ります。": "Your headline here,",
  "2行程度に収める": "in about two lines",
  "サービスの説明文が入ります。誰に向けた、どんな価値のものなのかを具体的に書きます。": "Describe the service: who it's for and the value it brings, in concrete terms.",
  "今すぐ申し込む": "Get started",
  "※ 補足のテキスト（無料・登録1分など）": "Reassurance text (free, sign up in a minute)",
  "世界観を伝える": "A tagline that",
  "キャッチコピー": "sets the mood",
  "サブコピーが入ります。短く、余韻を残す一文。": "Sub copy goes here. One short line that lingers.",
  "文字を読ませるため、背景画像の枠は暗いグレーにしておく（実装時は画像＋暗いオーバーレイ）": "The background box is dark gray so the text stays readable (use an image plus a dark overlay when building)",
  "資料請求で得られることを伝える見出し": "A headline about what the brochure gives you",
  "メリット1が入ります": "Benefit 1 goes here",
  "メリット2が入ります": "Benefit 2 goes here",
  "メリット3が入ります": "Benefit 3 goes here",
  "無料で資料をもらう": "Get the free brochure",
  "個人情報の取り扱いについての注記": "A note on how personal data is handled",
  "実績で選ばれていることを": "A headline showing",
  "サービスの説明文が入ります。": "The service description goes here.",
  "導入の相談をする": "Talk to sales",
  "0,000社": "0,000",
  "導入企業数": "Customers",
  "満足度": "Satisfaction",
  "短く印象的な": "Short and",
  "見出し": "Headline",
  "ブランドやコレクションの説明が入ります。余白を活かして短めに。": "Describe the brand or collection. Keep it short and let the space breathe.",
  "コレクションを見る": "View collection",
  "キャンペーンの見出し": "Campaign headline",
  "あなたにぴったりの〇〇を探そう": "Find the right one for you",
  "エリア": "Area",
  "種別": "Type",
  "キーワード": "Keyword",
  "駅名・特徴など": "Station, features, etc.",
  "検索する": "Search",
  "人気：": "Popular:",
  "キーワード1": "Keyword 1",
  "キーワード2": "Keyword 2",
  "キーワード3": "Keyword 3",

  // 特長・メリット
  "こんなお悩みはありませんか？": "Sound familiar?",
  "よくあるお悩み": "Common problems",
  "悩み1が入ります": "Problem 1 goes here",
  "悩み2が入ります": "Problem 2 goes here",
  "悩み3が入ります": "Problem 3 goes here",
  "サービス名なら": "With our service",
  "解決策1が入ります": "Solution 1 goes here",
  "解決策2が入ります": "Solution 2 goes here",
  "解決策3が入ります": "Solution 3 goes here",
  "〇〇が選ばれる3つの理由": "3 reasons people choose us",
  "理由の見出し1": "Reason heading 1",
  "理由の見出し2": "Reason heading 2",
  "理由の見出し3": "Reason heading 3",
  "数字で見る〇〇": "By the numbers",
  "導入社数": "Customers",
  "社": "",
  "対応エリア": "Regions served",
  "創業": "Founded",
  "年": "yrs",
  "※ 2026年00月時点": "As of Month 2026",
  "〇〇でできること": "What you can do",
  "メリット1": "Benefit 1",
  "メリット2": "Benefit 2",
  "メリット3": "Benefit 3",
  "メリット4": "Benefit 4",
  "メリット5": "Benefit 5",
  "メリット6": "Benefit 6",

  // 導入事例・お客様の声
  "お客様の声": "What our customers say",
  "氏名1": "Name 1",
  "氏名2": "Name 2",
  "氏名3": "Name 3",
  "削減": "reduction",
  "0倍": "0x",
  "に増加": "increase",
  "事例をもっと見る": "More case studies",
  "0,000社以上が導入しています": "Trusted by 0,000+ companies",
  "導入事例を見る →": "See case studies →",
  "お客様インタビュー": "Customer stories",
  "「記事の中で一番印象に残る発言を、ここに大きく引用します。」": "\"Quote the most memorable line from the interview here, large.\"",
  "株式会社〇〇 部署名": "Company Name, Department",
  "氏名 様": "Full Name",
  "インタビューを読む": "Read the story",
  "レビュー": "Reviews",
  "000件のレビュー": "000 reviews",
  "30代・女性": "Woman, 30s",
  "40代・男性": "Man, 40s",
  "20代・女性": "Woman, 20s",

  // カード一覧
  "新着記事": "Latest articles",
  "すべて見る →": "View all →",
  "おすすめ商品": "Recommended",
  "記事一覧": "Articles",
  "次へ →": "Next →",
  "ピックアップ": "Featured",
  "特集": "Feature",
  "一番読ませたい記事のタイトルが入ります": "The title of the article you most want read",
  "記事の抜粋が入ります。大きなカードでは2〜3行の抜粋を見せます。": "The excerpt goes here. Large cards show two or three lines.",
  "000件": "000 items",
  "おすすめ順 ▾": "Recommended ▾",
  "一覧を見る →": "View all →",
  "プレスリリース": "Press release",
  "お知らせのタイトルが入ります。長い場合は折り返します": "News title goes here. Long titles wrap to the next line",
  "メディア掲載": "In the media",

  // 流れ・ステップ
  "ご利用の流れ": "How it works",
  "お申し込み": "Apply",
  "ヒアリング": "Consultation",
  "ご提案": "Proposal",
  "ご利用開始": "Get started",
  "制作の進め方": "How we work",
  "1〜2日": "1–2 days",
  "お問い合わせ・ヒアリング": "Inquiry and consultation",
  "3日〜1週間": "3 days–1 week",
  "お見積もり・ご契約": "Quote and contract",
  "1〜2か月": "1–2 months",
  "制作・確認": "Build and review",
  "公開後": "After launch",
  "公開・運用サポート": "Launch and ongoing support",
  "手順1の見出し": "Step 1 heading",
  "手順2の見出し": "Step 2 heading",
  "手順3の見出し": "Step 3 heading",
  "プラン選択": "Choose plan",
  "お客様情報": "Your details",
  "内容の確認": "Review",
  "完了": "Done",

  // 料金表
  "ライト": "Lite",
  "スタンダード": "Standard",
  "月額": "Monthly",
  "年額": "Yearly",
  "2か月分おトク": "2 months free",
  "ベーシック": "Basic",
  "ビジネス": "Business",
  "エンタープライズ": "Enterprise",
  "要相談": "Contact us",
  "プラン比較": "Compare plans",
  "フリー": "Free",
  "チーム": "Team",
  "月額料金": "Monthly price",
  "10人まで": "Up to 10",
  "保存容量": "Storage",
  "機能A": "Feature A",
  "機能B": "Feature B",
  "電話・メール": "Phone and email",
  "プラン名": "Plan name",
  "申し込む": "Buy now",
  "30日間の返金保証つき": "30-day money-back guarantee",
  "含まれるもの1": "Included item 1",
  "含まれるもの2": "Included item 2",
  "含まれるもの3": "Included item 3",
  "含まれるもの4": "Included item 4",
  "含まれるもの5": "Included item 5",
  "含まれるもの6": "Included item 6",
  "料金シミュレーション": "Price calculator",
  "使う量を動かすと、月額の目安がわかります。": "Adjust your usage to see an estimated monthly price.",
  "10人": "10",
  "月間の処理件数": "Monthly volume",
  "5,000件": "5,000",
  "月額の目安": "Estimated monthly price",
  "人数 × 単価": "Users × unit price",
  "件数 × 単価": "Volume × unit price",
  "この内容で申し込む": "Sign up with this plan",
  "単価の一覧を見る →": "See unit prices →",
  "〜": "+",
  "基本料金に含まれる作業内容の説明が入ります。": "What the base price covers goes here.",
  "オプション": "Options",
  "項目": "Item",
  "内容": "Details",
  "オプション1": "Option 1",
  "オプション2": "Option 2",
  "オプション3": "Option 3",
  "オプション4": "Option 4",
  "要見積もり": "Quote",
  "※ 表示価格はすべて税込です。注記が入ります。": "All prices include tax. Other notes go here.",

  // FAQ
  "よくある質問1が入ります": "Frequently asked question 1",
  "よくある質問2が入ります": "Frequently asked question 2",
  "よくある質問3が入ります": "Frequently asked question 3",
  "よくある質問4が入ります": "Frequently asked question 4",
  "よくある質問5が入ります": "Frequently asked question 5",
  "ここにない質問は、お気軽にお問い合わせください。": "Can't find your question? Feel free to contact us.",
  "Q. よくある質問1が入ります": "Q. Frequently asked question 1",
  "Q. よくある質問2が入ります": "Q. Frequently asked question 2",
  "Q. よくある質問3が入ります": "Q. Frequently asked question 3",
  "Q. よくある質問4が入ります": "Q. Frequently asked question 4",
  "料金について": "Pricing",
  "契約・解約": "Billing & cancellation",
  "その他": "Other",
  "Q. 料金についての質問1が入ります": "Q. Pricing question 1",
  "Q. 料金についての質問2が入ります": "Q. Pricing question 2",
  "Q. 料金についての質問3が入ります": "Q. Pricing question 3",
  "Q. 料金についての質問4が入ります": "Q. Pricing question 4",
  "何かお困りですか？": "How can we help?",
  "キーワードで質問を探す": "Search questions by keyword",
  "はじめての方へ": "Getting started",
  "アカウント": "Account",
  "料金・お支払い": "Billing & payments",
  "機能の使い方": "Using features",
  "トラブル": "Troubleshooting",
  "解約": "Cancellation",
  "よく見られている質問": "Popular questions",
  "よく見られている質問1が入ります": "Popular question 1",
  "よく見られている質問2が入ります": "Popular question 2",
  "よく見られている質問3が入ります": "Popular question 3",
  "よく見られている質問4が入ります": "Popular question 4",
  "解決しない場合は": "Still need help?",

  // CTA
  "行動を促す見出しが入ります": "A headline that prompts action",
  "申し込むと何が得られるのかを一文で伝えます。": "One line on what they get by signing up.",
  "無料で試してみる": "Try it free",
  "登録1分・クレジットカード不要": "Sign up in a minute. No credit card needed",
  "まずはお気軽にどうぞ": "Start whichever way suits you",
  "すぐに始めたい方": "Ready to start",
  "無料トライアル": "Free trial",
  "すぐに使い始めたい方向けの説明が入ります。": "A description for those who want to start right away.",
  "無料で始める": "Start for free",
  "まずは話を聞きたい方": "Want to talk first",
  "オンライン相談": "Online consultation",
  "導入を検討中の方向けの説明が入ります。": "A description for those still evaluating.",
  "相談を予約する": "Book a call",
  "無料ダウンロード": "Free download",
  "資料のタイトルが入ります": "Guide title goes here",
  "資料でわかること1": "What you'll learn 1",
  "資料でわかること2": "What you'll learn 2",
  "資料でわかること3": "What you'll learn 3",
  "初回限定のご案内などの一言": "A short line, such as a first-visit offer",
  "WEBで予約": "Book online",
  "実装時は position: fixed; left: 0; right: 0; bottom: 0; でページ下に固定する": "When building, pin it to the bottom with position: fixed; left: 0; right: 0; bottom: 0;",
  "メールアドレスだけで、今すぐ始められます": "Start now with just your email",
  "登録すると何が起きるのかを一文で伝えます。": "One line on what happens when they sign up.",
  "無料で登録": "Sign up free",
  "登録は無料・いつでも解約できます": "Free to join. Cancel anytime",

  // お問い合わせフォーム
  "2営業日以内にご返信します。": "We reply within two business days.",
  "送信内容を確認する": "Review your message",
  "お電話でのお問い合わせ": "Call us",
  "平日 9:00〜18:00": "Weekdays 9:00–18:00",
  "お急ぎでない方は": "Not urgent? Check our",
  "もご覧ください。": "first.",
  "1. 入力": "1. Enter",
  "2. 確認": "2. Review",
  "3. 完了": "3. Done",
  "入力内容の確認": "Review your details",
  "以下の内容でよろしければ「送信する」を押してください。": "If everything looks right, press \"Submit\".",
  "サービスについて": "About the service",
  "入力した内容がそのまま表示されます。": "What you entered is shown here as is.",
  "戻って修正する": "Go back and edit",
  "お届け先の入力": "Shipping address",
  "郵便番号": "Postal code",
  "住所を自動入力": "Autofill address",
  "市区町村・番地": "City and street",
  "建物名・部屋番号": "Apartment, suite",
  "次へ進む": "Continue",
  "ご予約": "Book an appointment",
  "2026年00月": "Month 2026",
  "日": "Sun",
  "月": "Mon",
  "火": "Tue",
  "水": "Wed",
  "木": "Thu",
  "金": "Fri",
  "土": "Sat",
  "00月10日（木）の空き時間": "Available times on Thu, 10th",
  "グレーの時間は満席です。": "Gray times are fully booked.",
  "この内容で予約する": "Book this time",

  // 会社概要・アクセス
  "株式会社〇〇": "Company Name Inc.",
  "所在地": "Address",
  "〒000-0000 〇〇県〇〇市〇〇 0-0-0 〇〇ビル0F": "000 Main Street, Suite 000, City, State 00000",
  "設立": "Founded",
  "0000年0月0日": "Month 0, 0000",
  "代表者": "CEO",
  "代表取締役 氏名": "Full Name, CEO",
  "資本金": "Capital",
  "0,000万円": "$0,000,000",
  "従業員数": "Employees",
  "00名（2026年0月時点）": "00 (as of Month 2026)",
  "事業内容": "Business",
  "事業内容1": "Business line 1",
  "事業内容2": "Business line 2",
  "事業内容3": "Business line 3",
  "取引銀行": "Bank",
  "〇〇銀行 〇〇支店": "Bank Name, Branch",
  "〇〇ビル 0F": "Building Name, Floor 0",
  "電車でお越しの方": "By train",
  "〇〇線「〇〇駅」〇番出口から徒歩0分。出口を出て右へ進み、〇〇の角を左に曲がります。": "0 minutes on foot from Exit 0 of Station Name on the 00 Line. Turn right out of the exit, then left at the corner.",
  "お車でお越しの方": "By car",
  "専用駐車場はありません。近隣のコインパーキングをご利用ください。": "We have no parking of our own. Please use a nearby public lot.",
  "Googleマップで開く": "Open in Google Maps",
  "想いを一文で伝える見出しが入ります": "A one-line headline that captures what drives us",
  "本文の1段落目が入ります。会社を立ち上げたきっかけや、事業を通じて解決したいことを書きます。": "First paragraph: why the company started and what it sets out to solve.",
  "本文の2段落目が入ります。大切にしている考え方や、お客様との向き合い方を書きます。": "Second paragraph: the values you hold and how you work with customers.",
  "本文の3段落目が入ります。これから目指すことと、読み手への呼びかけで締めます。": "Third paragraph: where you're headed, closing with a word to the reader.",
  "株式会社〇〇 代表取締役": "CEO, Company Name Inc.",
  "氏名": "Full Name",
  "沿革": "Our history",
  "〇〇県〇〇市にて創業": "Founded in City, State",
  "株式会社〇〇を設立": "Incorporated as Company Name Inc.",
  "〇〇事業を開始": "Launched a new business line",
  "本社を〇〇へ移転": "Moved headquarters",
  "〇〇支店を開設": "Opened a new branch",
  "2026年": "2026",
  "創業〇〇周年を迎える": "Celebrated our 00th anniversary",
  "縦線は行ごとに引き、最初の行は点から下・最後の行は点から上だけにする": "Draw the vertical line per row: from the dot down on the first row, from the dot up on the last",

  // フッター
  "会社やサービスを一文で紹介するテキストが入ります。": "One line introducing the company or service.",
  "サービス": "Services",
  "会社情報": "Company",
  "まずは無料で試してみませんか": "Ready to try it for free?",
  "最後の背中を押す一文が入ります。": "One last line to nudge them forward.",
  "住所": "Address",
  "営業時間": "Hours",
  "11:00〜21:00（L.O. 20:30）": "11:00–21:00 (last order 20:30)",
  "定休日": "Closed",
  "毎週〇曜日": "Every Monday",
  "電話": "Phone",
  "ネット予約": "Book online",
  "店舗について": "About the shop",
  "&copy; 2026 店舗名": "&copy; 2026 Shop Name",
  "ニュースレターを受け取る": "Get the newsletter",
  "新しい記事やお知らせを週1回お届けします。いつでも解除できます。": "New articles and updates once a week. Unsubscribe anytime.",
  "登録する": "Subscribe",
  "メディア名": "Media Name",
  "運営者情報": "About",
  "&copy; 2026 メディア名": "&copy; 2026 Media Name",
};

// 語順が入れ替わる・同じ文言でも訳し分けが要る箇所は、HTML の断片ごと先に差し替える
export const HTML_EN = [
  ['<a class="wf-link" href="#"><u>プライバシーポリシー</u></a>に同意する', 'I agree to the <a class="wf-link" href="#"><u>privacy policy</u></a>'],
  ['実績で選ばれていることを<br>伝える見出し', 'A headline showing<br>proven results'],
  ['短く印象的な<br>見出し', 'Short and<br>striking headline'],
  // 英語のフォームは「名 → 姓」の順・郵便番号は5桁
  ['<div class="fm04__pair"><span class="fm-input">姓</span><span class="fm-input">名</span></div>', '<div class="fm04__pair"><span class="fm-input">First name</span><span class="fm-input">Last name</span></div>'],
  ['<span class="fm-input">000-0000</span>', '<span class="fm-input">00000</span>'],
  // フリガナ（名前の読み）は英語のフォームにない項目なので、英語版では同じ位置を「電話・メール」の行に置き換える
  ['      <div class="fm04__row"><span class="fm-label">フリガナ<span class="fm-req">必須</span></span><div class="fm04__pair"><span class="fm-input">セイ</span><span class="fm-input">メイ</span></div></div>\n', '      <div class="fm04__row"><span class="fm-label">Phone &amp; email<span class="fm-req">Required</span></span><div class="fm04__pair"><span class="fm-input">Phone</span><span class="fm-input">Email</span></div></div>\n'],
];
