// 背景塗り系ホバーエフェクト（12種）

export const BACKGROUND_EFFECTS = [
  {
    key: "bg-right",
    cat: "background",
    label: { ja: "右からスイープ", en: "Sweep from right" },
    html: '<a class="he-bg-right" href="#">Menu</a>',
    css: [
      ".he-bg-right {",
      "  position: relative; display: inline-block; padding: 10px 22px; border-radius: 8px; overflow: hidden; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease;",
      "}",
      ".he-bg-right::before {",
      '  content: ""; position: absolute; inset: 0; z-index: -1;',
      "  background: #6366f1; transform: scaleX(0); transform-origin: right;",
      "  transition: transform 0.3s ease;",
      "}",
      ".he-bg-right:hover { color: #fff; }",
      ".he-bg-right:hover::before { transform: scaleX(1); }",
    ],
  },
  {
    key: "bg-down",
    cat: "background",
    label: { ja: "上から塗り下がる", en: "Fill downward" },
    html: '<a class="he-bg-down" href="#">Menu</a>',
    css: [
      ".he-bg-down {",
      "  position: relative; display: inline-block; padding: 10px 22px; border-radius: 8px; overflow: hidden; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease;",
      "}",
      ".he-bg-down::before {",
      '  content: ""; position: absolute; inset: 0; z-index: -1;',
      "  background: #6366f1; transform: scaleY(0); transform-origin: top;",
      "  transition: transform 0.3s ease;",
      "}",
      ".he-bg-down:hover { color: #fff; }",
      ".he-bg-down:hover::before { transform: scaleY(1); }",
    ],
  },
  {
    key: "bg-center-x",
    cat: "background",
    label: { ja: "中央から左右へ", en: "Expand from center" },
    html: '<a class="he-bg-cx" href="#">Menu</a>',
    css: [
      ".he-bg-cx {",
      "  position: relative; display: inline-block; padding: 10px 22px; border-radius: 8px; overflow: hidden; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease;",
      "}",
      ".he-bg-cx::before {",
      '  content: ""; position: absolute; inset: 0; z-index: -1;',
      "  background: #6366f1; transform: scaleX(0); transform-origin: center;",
      "  transition: transform 0.3s ease;",
      "}",
      ".he-bg-cx:hover { color: #fff; }",
      ".he-bg-cx:hover::before { transform: scaleX(1); }",
    ],
  },
  {
    key: "bg-slice",
    cat: "background",
    label: { ja: "斜めスライス", en: "Diagonal slice" },
    html: '<a class="he-bg-slice" href="#">Menu</a>',
    css: [
      ".he-bg-slice {",
      "  position: relative; display: inline-block; padding: 10px 22px; border-radius: 8px; overflow: hidden; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease;",
      "}",
      ".he-bg-slice::before {",
      '  content: ""; position: absolute; top: 0; left: -20%; width: 140%; height: 100%; z-index: -1;',
      "  background: #6366f1; transform: skewX(-15deg) translateX(-120%);",
      "  transition: transform 0.35s ease;",
      "}",
      ".he-bg-slice:hover { color: #fff; }",
      ".he-bg-slice:hover::before { transform: skewX(-15deg) translateX(0); }",
    ],
  },
  {
    key: "bg-doors",
    cat: "background",
    label: { ja: "観音開きで塗る", en: "Double doors close" },
    html: '<a class="he-bg-doors" href="#">Menu</a>',
    css: [
      ".he-bg-doors {",
      "  position: relative; display: inline-block; padding: 10px 22px; border-radius: 8px; overflow: hidden; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease;",
      "}",
      ".he-bg-doors::before, .he-bg-doors::after {",
      '  content: ""; position: absolute; top: 0; width: 51%; height: 100%; z-index: -1;',
      "  background: #6366f1; transform: scaleX(0); transition: transform 0.3s ease;",
      "}",
      ".he-bg-doors::before { left: 0; transform-origin: left; }",
      ".he-bg-doors::after { right: 0; transform-origin: right; }",
      ".he-bg-doors:hover { color: #fff; }",
      ".he-bg-doors:hover::before, .he-bg-doors:hover::after { transform: scaleX(1); }",
    ],
  },
  {
    key: "bg-blinds",
    cat: "background",
    label: { ja: "ブラインドが閉じる", en: "Blinds close" },
    html: '<a class="he-bg-blinds" href="#">Menu</a>',
    css: [
      "/* @property 対応ブラウザで動作 */",
      "@property --he-blind {",
      '  syntax: "<length>"; initial-value: 0px; inherits: false;',
      "}",
      ".he-bg-blinds {",
      "  display: inline-block; padding: 10px 22px; border-radius: 8px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background: repeating-linear-gradient(180deg, rgba(99,102,241,0.85) 0 var(--he-blind), transparent var(--he-blind) 11px);",
      "  transition: --he-blind 0.35s ease, color 0.35s ease 0.15s;",
      "}",
      ".he-bg-blinds:hover { --he-blind: 11px; color: #fff; }",
    ],
  },
  {
    key: "bg-circle",
    cat: "background",
    label: { ja: "円形に広がる", en: "Circle expands" },
    html: '<a class="he-bg-circle" href="#">Menu</a>',
    css: [
      ".he-bg-circle {",
      "  position: relative; display: inline-block; padding: 10px 22px; border-radius: 8px; overflow: hidden; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease;",
      "}",
      ".he-bg-circle::before {",
      '  content: ""; position: absolute; left: 50%; top: 50%; width: 200px; height: 200px; z-index: -1;',
      "  margin: -100px 0 0 -100px; border-radius: 50%;",
      "  background: #6366f1; transform: scale(0); transition: transform 0.4s ease;",
      "}",
      ".he-bg-circle:hover { color: #fff; }",
      ".he-bg-circle:hover::before { transform: scale(1.2); }",
    ],
  },
  {
    key: "bg-diagonal",
    cat: "background",
    label: { ja: "斜めに塗り上がる", en: "Diagonal wipe up" },
    html: '<a class="he-bg-diag" href="#">Menu</a>',
    css: [
      ".he-bg-diag {",
      "  display: inline-block; padding: 10px 22px; border-radius: 8px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background: linear-gradient(135deg, #6366f1 50%, transparent 50.5%) no-repeat;",
      "  background-size: 250% 250%; background-position: 100% 100%;",
      "  transition: background-position 0.4s ease, color 0.4s ease;",
      "}",
      ".he-bg-diag:hover { background-position: 0 0; color: #fff; }",
    ],
  },
  {
    key: "bg-stripes",
    cat: "background",
    label: { ja: "ストライプが流れる", en: "Stripes flow" },
    html: '<a class="he-bg-stripes" href="#">Menu</a>',
    css: [
      ".he-bg-stripes {",
      "  position: relative; display: inline-block; padding: 10px 22px; border-radius: 8px; overflow: hidden; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease;",
      "}",
      ".he-bg-stripes::before {",
      '  content: ""; position: absolute; top: 0; left: 0; width: 200%; height: 100%; z-index: -1;',
      "  background: repeating-linear-gradient(45deg, #6366f1 0 12px, #ec4899 12px 24px);",
      "  opacity: 0; transition: opacity 0.3s ease;",
      "}",
      ".he-bg-stripes:hover { color: #fff; }",
      ".he-bg-stripes:hover::before { opacity: 1; animation: he-stripes 0.8s linear infinite; }",
      "@keyframes he-stripes {",
      "  to { transform: translateX(-33.94px); } /* 12px*2/sin(45deg)＝1周期分 */",
      "}",
    ],
  },
  {
    key: "bg-gradient-move",
    cat: "background",
    label: { ja: "グラデーションが流れる", en: "Gradient flows" },
    html: '<a class="he-bg-gradmove" href="#">Menu</a>',
    css: [
      ".he-bg-gradmove {",
      "  display: inline-block; padding: 10px 22px; border-radius: 8px;",
      "  color: #fff; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background: linear-gradient(90deg, #6366f1, #ec4899, #6366f1);",
      "  background-size: 200% 100%;",
      "}",
      ".he-bg-gradmove:hover { animation: he-gradmove 1.2s linear infinite; }",
      "@keyframes he-gradmove {",
      "  to { background-position: 200% 0; }",
      "}",
    ],
  },
  {
    key: "bg-marker",
    cat: "background",
    label: { ja: "マーカーでなぞる", en: "Marker pen swipe" },
    html: '<a class="he-bg-marker" href="#">Menu</a>',
    css: [
      ".he-bg-marker {",
      "  position: relative; display: inline-block; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-bg-marker::before {",
      '  content: ""; position: absolute; left: -4px; right: -4px; bottom: 0; height: 55%; z-index: -1;',
      "  background: rgba(236,72,153,0.4); border-radius: 4px;",
      "  transform: rotate(-1.5deg) scaleX(0); transform-origin: left;",
      "  transition: transform 0.35s ease-out;",
      "}",
      ".he-bg-marker:hover::before { transform: rotate(-1.5deg) scaleX(1); }",
    ],
  },
  {
    key: "bg-vsplit",
    cat: "background",
    label: { ja: "上下から挟んで塗る", en: "Fill from top & bottom" },
    html: '<a class="he-bg-vsplit" href="#">Menu</a>',
    css: [
      ".he-bg-vsplit {",
      "  position: relative; display: inline-block; padding: 10px 22px; border-radius: 8px; overflow: hidden; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease;",
      "}",
      ".he-bg-vsplit::before, .he-bg-vsplit::after {",
      '  content: ""; position: absolute; left: 0; width: 100%; height: 51%; z-index: -1;',
      "  background: #6366f1; transform: scaleY(0); transition: transform 0.3s ease;",
      "}",
      ".he-bg-vsplit::before { top: 0; transform-origin: top; }",
      ".he-bg-vsplit::after { bottom: 0; transform-origin: bottom; }",
      ".he-bg-vsplit:hover { color: #fff; }",
      ".he-bg-vsplit:hover::before, .he-bg-vsplit:hover::after { transform: scaleY(1); }",
    ],
  },
];
