// ボーダー系ホバーエフェクト（12種）

export const BORDER_EFFECTS = [
  {
    key: "bd-draw",
    cat: "border",
    label: { ja: "枠線を一周描く", en: "Draw border around" },
    html: '<a class="he-bd-draw" href="#">Menu</a>',
    css: [
      ".he-bd-draw {",
      "  position: relative; display: inline-block; padding: 10px 22px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-bd-draw::before, .he-bd-draw::after {",
      '  content: ""; position: absolute; width: 0; height: 0; box-sizing: border-box;',
      "}",
      "/* ::before が上→右、::after が下→左の順に描く */",
      ".he-bd-draw::before { top: 0; left: 0; border-top: 2px solid #6366f1; border-right: 2px solid #6366f1; transition: height 0.12s linear, width 0.12s linear 0.12s; }",
      ".he-bd-draw::after { bottom: 0; right: 0; border-bottom: 2px solid #6366f1; border-left: 2px solid #6366f1; transition: height 0.12s linear 0.24s, width 0.12s linear 0.36s; }",
      ".he-bd-draw:hover::before { width: 100%; height: 100%; transition: width 0.12s linear, height 0.12s linear 0.12s; }",
      ".he-bd-draw:hover::after { width: 100%; height: 100%; transition: width 0.12s linear 0.24s, height 0.12s linear 0.36s; }",
    ],
  },
  {
    key: "bd-corners",
    cat: "border",
    label: { ja: "四隅から枠になる", en: "Corners to frame" },
    html: '<a class="he-bd-corners" href="#">Menu</a>',
    css: [
      ".he-bd-corners {",
      "  position: relative; display: inline-block; padding: 10px 22px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-bd-corners::before, .he-bd-corners::after {",
      '  content: ""; position: absolute; width: 14px; height: 14px; box-sizing: border-box;',
      "  border: 0 solid #6366f1; transition: width 0.3s ease, height 0.3s ease;",
      "}",
      ".he-bd-corners::before { top: 0; left: 0; border-top-width: 2px; border-left-width: 2px; }",
      ".he-bd-corners::after { bottom: 0; right: 0; border-bottom-width: 2px; border-right-width: 2px; }",
      ".he-bd-corners:hover::before, .he-bd-corners:hover::after { width: 100%; height: 100%; }",
    ],
  },
  {
    key: "bd-bracket",
    cat: "border",
    label: { ja: "ブラケットが寄る", en: "Brackets close in" },
    html: '<a class="he-bd-bracket" href="#">Menu</a>',
    css: [
      ".he-bd-bracket {",
      "  position: relative; display: inline-block; padding: 8px 18px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-bd-bracket::before, .he-bd-bracket::after {",
      '  content: ""; position: absolute; top: 0; bottom: 0; width: 10px;',
      "  border: 2px solid #6366f1; opacity: 0; transition: transform 0.25s ease, opacity 0.25s ease;",
      "}",
      ".he-bd-bracket::before { left: 0; border-right: none; transform: translateX(-10px); }",
      ".he-bd-bracket::after { right: 0; border-left: none; transform: translateX(10px); }",
      ".he-bd-bracket:hover::before, .he-bd-bracket:hover::after { opacity: 1; transform: translateX(0); }",
    ],
  },
  {
    key: "bd-tb-center",
    cat: "border",
    label: { ja: "上下線が中央から", en: "Top/bottom from center" },
    html: '<a class="he-bd-tbc" href="#">Menu</a>',
    css: [
      ".he-bd-tbc {",
      "  position: relative; display: inline-block; padding: 10px 18px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-bd-tbc::before, .he-bd-tbc::after {",
      '  content: ""; position: absolute; left: 0; width: 100%; height: 2px;',
      "  background: #6366f1; transform: scaleX(0); transform-origin: center;",
      "  transition: transform 0.3s ease;",
      "}",
      ".he-bd-tbc::before { top: 0; }",
      ".he-bd-tbc::after { bottom: 0; }",
      ".he-bd-tbc:hover::before, .he-bd-tbc:hover::after { transform: scaleX(1); }",
    ],
  },
  {
    key: "bd-outline-gap",
    cat: "border",
    label: { ja: "枠が外へ広がる", en: "Outline expands out" },
    html: '<a class="he-bd-gap" href="#">Menu</a>',
    css: [
      ".he-bd-gap {",
      "  display: inline-block; padding: 8px 18px; border-radius: 6px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  outline: 2px solid transparent; outline-offset: 0px;",
      "  transition: outline-color 0.3s ease, outline-offset 0.3s ease;",
      "}",
      ".he-bd-gap:hover { outline-color: #6366f1; outline-offset: 6px; }",
    ],
  },
  {
    key: "bd-inset",
    cat: "border",
    label: { ja: "内側に枠が現れる", en: "Inner frame appears" },
    html: '<a class="he-bd-inset" href="#">Menu</a>',
    css: [
      ".he-bd-inset {",
      "  display: inline-block; padding: 10px 22px; border-radius: 8px; background: #f1f5f9;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: box-shadow 0.3s ease;",
      "}",
      ".he-bd-inset:hover { box-shadow: inset 0 0 0 3px #6366f1; }",
    ],
  },
  {
    key: "bd-ants",
    cat: "border",
    label: { ja: "破線が流れる", en: "Marching ants" },
    html: '<a class="he-bd-ants" href="#">Menu</a>',
    css: [
      ".he-bd-ants {",
      "  display: inline-block; padding: 10px 22px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background-image:",
      "    linear-gradient(90deg, #6366f1 50%, transparent 50%),",
      "    linear-gradient(90deg, #6366f1 50%, transparent 50%),",
      "    linear-gradient(0deg, #6366f1 50%, transparent 50%),",
      "    linear-gradient(0deg, #6366f1 50%, transparent 50%);",
      "  background-size: 12px 2px, 12px 2px, 2px 12px, 2px 12px;",
      "  background-position: 0 0, 0 100%, 0 0, 100% 0;",
      "  background-repeat: repeat-x, repeat-x, repeat-y, repeat-y;",
      "}",
      ".he-bd-ants:hover { animation: he-ants 0.6s linear infinite; }",
      "@keyframes he-ants {",
      "  to { background-position: 12px 0, -12px 100%, 0 -12px, 100% 12px; }",
      "}",
    ],
  },
  {
    key: "bd-gradient-run",
    cat: "border",
    label: { ja: "グラデ枠が回る", en: "Gradient border spins" },
    html: '<a class="he-bd-grad" href="#">Menu</a>',
    css: [
      "/* @property 対応ブラウザ（Chrome/Edge/Safari/Firefox 最新）で動作 */",
      "@property --he-angle {",
      '  syntax: "<angle>"; initial-value: 0deg; inherits: false;',
      "}",
      ".he-bd-grad {",
      "  display: inline-block; padding: 10px 22px; border-radius: 8px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  border: 2px solid transparent;",
      "  background: linear-gradient(#fff, #fff) padding-box,",
      "    conic-gradient(from var(--he-angle), #6366f1, #ec4899, #6366f1) border-box;",
      "}",
      ".he-bd-grad:hover { animation: he-grad-spin 1.2s linear infinite; }",
      "@keyframes he-grad-spin { to { --he-angle: 360deg; } }",
    ],
  },
  {
    key: "bd-thicken",
    cat: "border",
    label: { ja: "枠が太くなる", en: "Border thickens" },
    html: '<a class="he-bd-thicken" href="#">Menu</a>',
    css: [
      ".he-bd-thicken {",
      "  display: inline-block; padding: 10px 22px; border-radius: 8px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  box-shadow: 0 0 0 1px #cbd5e1;",
      "  transition: box-shadow 0.25s ease, color 0.25s ease;",
      "}",
      ".he-bd-thicken:hover { box-shadow: 0 0 0 3px #6366f1; color: #6366f1; }",
    ],
  },
  {
    key: "bd-pill",
    cat: "border",
    label: { ja: "角丸ピル化", en: "Rounds into pill" },
    html: '<a class="he-bd-pill" href="#">Menu</a>',
    css: [
      ".he-bd-pill {",
      "  display: inline-block; padding: 8px 20px; border: 2px solid #6366f1; border-radius: 6px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: border-radius 0.35s ease, color 0.35s ease;",
      "}",
      ".he-bd-pill:hover { border-radius: 999px; color: #6366f1; }",
    ],
  },
  {
    key: "bd-cross",
    cat: "border",
    label: { ja: "上下線が交差して現れる", en: "Lines cross in" },
    html: '<a class="he-bd-cross" href="#">Menu</a>',
    css: [
      ".he-bd-cross {",
      "  position: relative; display: inline-block; padding: 10px 18px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-bd-cross::before, .he-bd-cross::after {",
      '  content: ""; position: absolute; left: 0; width: 100%; height: 2px;',
      "  background: #6366f1; transform: scaleX(0); transition: transform 0.3s ease;",
      "}",
      "/* 上線は左から・下線は右から＝すれ違うように現れる */",
      ".he-bd-cross::before { top: 0; transform-origin: left; }",
      ".he-bd-cross::after { bottom: 0; transform-origin: right; transition-delay: 0.08s; }",
      ".he-bd-cross:hover::before, .he-bd-cross:hover::after { transform: scaleX(1); }",
    ],
  },
  {
    key: "bd-glow",
    cat: "border",
    label: { ja: "枠が発光する", en: "Border glows" },
    html: '<a class="he-bd-glow" href="#">Menu</a>',
    css: [
      ".he-bd-glow {",
      "  display: inline-block; padding: 10px 22px; border: 2px solid #6366f1; border-radius: 8px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: box-shadow 0.3s ease;",
      "}",
      ".he-bd-glow:hover {",
      "  box-shadow: 0 0 12px rgba(99,102,241,0.6), inset 0 0 8px rgba(99,102,241,0.25);",
      "}",
    ],
  },
];
