// エフェクト系ホバーエフェクト（8種）

export const FX_EFFECTS = [
  {
    key: "fx-ripple",
    cat: "fx",
    label: { ja: "波紋が広がる", en: "Ripple expands" },
    html: '<a class="he-fx-ripple" href="#">Menu</a>',
    css: [
      ".he-fx-ripple {",
      "  position: relative; display: inline-block; padding: 8px 20px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-fx-ripple::after {",
      '  content: ""; position: absolute; left: 50%; top: 50%; width: 60px; height: 60px;',
      "  margin: -30px 0 0 -30px; border: 2px solid #6366f1; border-radius: 50%;",
      "  opacity: 0; transform: scale(0.3); pointer-events: none;",
      "}",
      ".he-fx-ripple:hover::after { animation: he-ripple 0.6s ease-out forwards; }",
      "@keyframes he-ripple {",
      "  0% { opacity: 1; transform: scale(0.3); }",
      "  100% { opacity: 0; transform: scale(2.2); }",
      "}",
    ],
  },
  {
    key: "fx-sparkle",
    cat: "fx",
    label: { ja: "キラッと光る", en: "Sparkles twinkle" },
    html: '<a class="he-fx-sparkle" href="#">Menu</a>',
    css: [
      ".he-fx-sparkle {",
      "  position: relative; display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.25s ease;",
      "}",
      ".he-fx-sparkle::before, .he-fx-sparkle::after {",
      '  content: "✦"; position: absolute; font-size: 0.7em;',
      "  opacity: 0; transform: scale(0) rotate(-40deg);",
      "  transition: opacity 0.3s ease, transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);",
      "}",
      ".he-fx-sparkle::before { top: -10px; left: -12px; color: #6366f1; }",
      ".he-fx-sparkle::after { bottom: -10px; right: -12px; color: #ec4899; transition-delay: 0.1s; }",
      ".he-fx-sparkle:hover { color: #6366f1; }",
      ".he-fx-sparkle:hover::before, .he-fx-sparkle:hover::after { opacity: 1; transform: scale(1) rotate(0); }",
    ],
  },
  {
    key: "fx-color-slice",
    cat: "fx",
    label: { ja: "色が斜めに切り替わる", en: "Diagonal color swap" },
    html: '<a class="he-fx-slice" href="#" data-text="Menu">Menu</a>',
    css: [
      ".he-fx-slice {",
      "  position: relative; display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      "/* data-text の複製がアクセント色で重なり、斜めのクリップで塗り替わる */",
      ".he-fx-slice::after {",
      "  content: attr(data-text); position: absolute; left: 0; top: 0; color: #6366f1;",
      "  clip-path: polygon(0 0, 30% 0, 0 100%, -30% 100%);",
      "  transition: clip-path 0.4s ease;",
      "}",
      ".he-fx-slice:hover::after {",
      "  clip-path: polygon(0 0, 130% 0, 100% 100%, 0 100%);",
      "}",
    ],
  },
  {
    key: "fx-layers",
    cat: "fx",
    label: { ja: "2色レイヤーがずれる", en: "Two-color layer offset" },
    html: '<a class="he-fx-layers" href="#" data-text="Menu">Menu</a>',
    css: [
      ".he-fx-layers {",
      "  position: relative; display: inline-block; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-fx-layers::before, .he-fx-layers::after {",
      "  content: attr(data-text); position: absolute; left: 0; top: 0; z-index: -1;",
      "  opacity: 0; transition: opacity 0.25s ease, transform 0.25s ease;",
      "}",
      ".he-fx-layers::before { color: #6366f1; }",
      ".he-fx-layers::after { color: #ec4899; }",
      ".he-fx-layers:hover::before { opacity: 0.85; transform: translate(-4px, -4px); }",
      ".he-fx-layers:hover::after { opacity: 0.85; transform: translate(4px, 4px); }",
    ],
  },
  {
    key: "fx-ghost",
    cat: "fx",
    label: { ja: "残像が広がる", en: "Ghost echo" },
    html: '<a class="he-fx-ghost" href="#" data-text="Menu">Menu</a>',
    css: [
      ".he-fx-ghost {",
      "  position: relative; display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.25s ease;",
      "}",
      ".he-fx-ghost::after {",
      "  content: attr(data-text); position: absolute; left: 0; top: 0; color: #6366f1;",
      "  opacity: 0; pointer-events: none;",
      "}",
      ".he-fx-ghost:hover { color: #6366f1; }",
      ".he-fx-ghost:hover::after { animation: he-ghost 0.7s ease-out infinite; }",
      "@keyframes he-ghost {",
      "  0% { opacity: 0.6; transform: scale(1); }",
      "  100% { opacity: 0; transform: scale(1.7); }",
      "}",
    ],
  },
  {
    key: "fx-dotline",
    cat: "fx",
    label: { ja: "ドット線が流れる", en: "Dotted line flows" },
    html: '<a class="he-fx-dotline" href="#">Menu</a>',
    css: [
      ".he-fx-dotline {",
      "  position: relative; display: inline-block; padding-bottom: 6px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-fx-dotline::after {",
      '  content: ""; position: absolute; left: 0; bottom: 0; width: 100%; height: 4px;',
      "  background: radial-gradient(circle, #6366f1 1.5px, transparent 1.6px) repeat-x left center / 8px 4px;",
      "  opacity: 0; transition: opacity 0.25s ease;",
      "}",
      ".he-fx-dotline:hover::after { opacity: 1; animation: he-dotline 0.4s linear infinite; }",
      "@keyframes he-dotline {",
      "  to { background-position: 8px center; }",
      "}",
    ],
  },
  {
    key: "fx-burst",
    cat: "fx",
    label: { ja: "粒が弾ける", en: "Particle burst" },
    html: '<a class="he-fx-burst" href="#">Menu</a>',
    css: [
      ".he-fx-burst {",
      "  position: relative; display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.25s ease;",
      "}",
      "/* box-shadow の複数指定で粒を配置し、ホバーで一斉に飛び散らせる */",
      ".he-fx-burst::after {",
      '  content: ""; position: absolute; left: 50%; top: 50%; width: 5px; height: 5px;',
      "  margin: -2px 0 0 -2px; border-radius: 50%; opacity: 0; pointer-events: none;",
      "  box-shadow: 18px -14px 0 #6366f1, -20px -10px 0 #ec4899, 14px 12px 0 #6366f1,",
      "    -14px 14px 0 #ec4899, 0 -20px 0 #6366f1, 22px 4px 0 #ec4899, -24px 2px 0 #6366f1;",
      "}",
      ".he-fx-burst:hover { color: #6366f1; }",
      ".he-fx-burst:hover::after { animation: he-burst 0.5s ease-out forwards; }",
      "@keyframes he-burst {",
      "  0% { opacity: 1; transform: scale(0.4); }",
      "  100% { opacity: 0; transform: scale(1.3); }",
      "}",
    ],
  },
  {
    key: "fx-caret",
    cat: "fx",
    label: { ja: "入力カーソル点滅", en: "Blinking caret" },
    html: '<a class="he-fx-caret" href="#">Menu</a>',
    css: [
      ".he-fx-caret {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  font-family: Consolas, Menlo, monospace;",
      "}",
      ".he-fx-caret::after {",
      '  content: ""; display: inline-block; width: 2px; height: 1.05em; margin-left: 4px;',
      "  background: #6366f1; vertical-align: text-bottom; opacity: 0;",
      "}",
      ".he-fx-caret:hover::after { animation: he-caret 0.8s steps(2) infinite; }",
      "@keyframes he-caret {",
      "  0% { opacity: 1; }",
      "  100% { opacity: 0; }",
      "}",
    ],
  },
];
