// 発光・影系ホバーエフェクト（10種）
// dark: true のものは暗い背景向け（ギャラリーのステージも暗色で表示する）

export const GLOW_EFFECTS = [
  {
    key: "gl-neon",
    cat: "glow",
    label: { ja: "ネオン点灯", en: "Neon light-up" },
    dark: true,
    html: '<a class="he-gl-neon" href="#">Menu</a>',
    css: [
      "/* 暗い背景向け */",
      ".he-gl-neon {",
      "  display: inline-block;",
      "  color: #94a3b8; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease, text-shadow 0.3s ease;",
      "}",
      ".he-gl-neon:hover {",
      "  color: #fff;",
      "  text-shadow: 0 0 8px #6366f1, 0 0 20px #6366f1, 0 0 42px #6366f1;",
      "}",
    ],
  },
  {
    key: "gl-pulse",
    cat: "glow",
    label: { ja: "光がパルスする", en: "Pulsing glow" },
    dark: true,
    html: '<a class="he-gl-pulse" href="#">Menu</a>',
    css: [
      "/* 暗い背景向け */",
      ".he-gl-pulse {",
      "  display: inline-block;",
      "  color: #e2e8f0; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-gl-pulse:hover { animation: he-glpulse 1.2s ease-in-out infinite; }",
      "@keyframes he-glpulse {",
      "  0%, 100% { text-shadow: 0 0 6px rgba(99,102,241,0.4); }",
      "  50% { text-shadow: 0 0 14px #6366f1, 0 0 30px #6366f1; }",
      "}",
    ],
  },
  {
    key: "gl-float-shadow",
    cat: "glow",
    label: { ja: "ふわっと浮く影", en: "Float with soft shadow" },
    html: '<a class="he-gl-float" href="#">Menu</a>',
    css: [
      ".he-gl-float {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.3s ease, filter 0.3s ease;",
      "}",
      ".he-gl-float:hover {",
      "  transform: translateY(-4px);",
      "  filter: drop-shadow(0 8px 6px rgba(30,41,59,0.35));",
      "}",
    ],
  },
  {
    key: "gl-long",
    cat: "glow",
    label: { ja: "ロングシャドウ", en: "Long shadow" },
    html: '<a class="he-gl-long" href="#">Menu</a>',
    css: [
      ".he-gl-long {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.25s ease, text-shadow 0.25s ease;",
      "}",
      ".he-gl-long:hover {",
      "  transform: translate(-2px, -2px);",
      "  text-shadow: 1px 1px 0 #ec4899, 2px 2px 0 #ec4899, 3px 3px 0 #ec4899,",
      "    4px 4px 0 #ec4899, 5px 5px 0 #ec4899, 6px 6px 0 #ec4899;",
      "}",
    ],
  },
  {
    key: "gl-spot",
    cat: "glow",
    label: { ja: "スポットライト", en: "Spotlight" },
    dark: true,
    html: '<a class="he-gl-spot" href="#">Menu</a>',
    css: [
      "/* 暗い背景向け */",
      ".he-gl-spot {",
      "  position: relative; display: inline-block; z-index: 0;",
      "  color: #cbd5e1; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.35s ease;",
      "}",
      ".he-gl-spot::before {",
      '  content: ""; position: absolute; left: 50%; top: 50%; width: 140px; height: 140px; z-index: -1;',
      "  margin: -70px 0 0 -70px; border-radius: 50%;",
      "  background: radial-gradient(circle, rgba(99,102,241,0.45), transparent 65%);",
      "  opacity: 0; transform: scale(0.5);",
      "  transition: opacity 0.35s ease, transform 0.35s ease;",
      "}",
      ".he-gl-spot:hover { color: #fff; }",
      ".he-gl-spot:hover::before { opacity: 1; transform: scale(1); }",
    ],
  },
  {
    key: "gl-ring",
    cat: "glow",
    label: { ja: "パルスリング", en: "Pulse ring" },
    html: '<a class="he-gl-ring" href="#">Menu</a>',
    css: [
      ".he-gl-ring {",
      "  position: relative; display: inline-block; padding: 8px 20px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-gl-ring::after {",
      '  content: ""; position: absolute; inset: 0; border-radius: 999px;',
      "  border: 2px solid #6366f1; opacity: 0;",
      "}",
      ".he-gl-ring:hover::after { animation: he-ring 0.9s ease-out infinite; }",
      "@keyframes he-ring {",
      "  0% { opacity: 1; transform: scale(0.9); }",
      "  100% { opacity: 0; transform: scale(1.35); }",
      "}",
    ],
  },
  {
    key: "gl-shine-sweep",
    cat: "glow",
    label: { ja: "文字を光が走る", en: "Shine sweeps across text" },
    dark: true,
    html: '<a class="he-gl-shine" href="#">Menu</a>',
    css: [
      "/* 暗い背景向け */",
      ".he-gl-shine {",
      "  display: inline-block;",
      "  font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background-image: linear-gradient(110deg, #94a3b8 42%, #fff 50%, #94a3b8 58%);",
      "  background-size: 250% 100%; background-position: 100% 0;",
      "  -webkit-background-clip: text; background-clip: text; color: transparent;",
      "}",
      ".he-gl-shine:hover { animation: he-shine 1.2s linear infinite; }",
      "@keyframes he-shine {",
      "  to { background-position: -150% 0; }",
      "}",
    ],
  },
  {
    key: "gl-flicker",
    cat: "glow",
    label: { ja: "蛍光灯フリッカー点灯", en: "Fluorescent flicker on" },
    dark: true,
    html: '<a class="he-gl-flicker" href="#">Menu</a>',
    css: [
      "/* 暗い背景向け */",
      ".he-gl-flicker {",
      "  display: inline-block;",
      "  color: #64748b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-gl-flicker:hover { animation: he-flicker 0.8s linear forwards; }",
      "@keyframes he-flicker {",
      "  0% { color: #64748b; text-shadow: none; }",
      "  10% { color: #fff; text-shadow: 0 0 12px #6366f1; }",
      "  15% { color: #64748b; text-shadow: none; }",
      "  25% { color: #fff; text-shadow: 0 0 12px #6366f1; }",
      "  35% { color: #64748b; text-shadow: none; }",
      "  50%, 100% { color: #fff; text-shadow: 0 0 10px #6366f1, 0 0 26px #6366f1; }",
      "}",
    ],
  },
  {
    key: "gl-stroke-glow",
    cat: "glow",
    label: { ja: "中抜き発光", en: "Glowing outline text" },
    dark: true,
    html: '<a class="he-gl-stroke" href="#">Menu</a>',
    css: [
      "/* 暗い背景向け */",
      ".he-gl-stroke {",
      "  display: inline-block;",
      "  color: #f8fafc; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  -webkit-text-stroke: 1px transparent;",
      "  transition: color 0.3s ease, -webkit-text-stroke-color 0.3s ease, text-shadow 0.3s ease;",
      "}",
      ".he-gl-stroke:hover {",
      "  color: transparent; -webkit-text-stroke-color: #6366f1;",
      "  text-shadow: 0 0 14px rgba(99,102,241,0.8);",
      "}",
    ],
  },
  {
    key: "gl-backlight",
    cat: "glow",
    label: { ja: "背光がにじむ", en: "Backlight blooms" },
    html: '<a class="he-gl-back" href="#">Menu</a>',
    css: [
      ".he-gl-back {",
      "  position: relative; display: inline-block; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-gl-back::before {",
      '  content: ""; position: absolute; inset: -6px -14px; z-index: -1; border-radius: 999px;',
      "  background: rgba(99,102,241,0.35); filter: blur(12px);",
      "  opacity: 0; transform: scale(0.7);",
      "  transition: opacity 0.35s ease, transform 0.35s ease;",
      "}",
      ".he-gl-back:hover::before { opacity: 1; transform: scale(1); }",
    ],
  },
];
