// ナビ装飾系ホバーエフェクト（10種）
// ナビメニューの項目に付ける「印」のアクセント

export const NAV_EFFECTS = [
  {
    key: "nav-dot",
    cat: "nav",
    label: { ja: "ドットが現れる", en: "Dot appears" },
    html: '<a class="he-nav-dot" href="#">Menu</a>',
    css: [
      ".he-nav-dot {",
      "  position: relative; display: inline-block; padding-left: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: padding-left 0.25s ease, color 0.25s ease;",
      "}",
      ".he-nav-dot::before {",
      '  content: ""; position: absolute; left: 0; top: 50%; margin-top: -4px;',
      "  width: 8px; height: 8px; border-radius: 50%; background: #6366f1;",
      "  transform: scale(0); transition: transform 0.25s ease;",
      "}",
      ".he-nav-dot:hover { padding-left: 16px; color: #6366f1; }",
      ".he-nav-dot:hover::before { transform: scale(1); }",
    ],
  },
  {
    key: "nav-arrow",
    cat: "nav",
    label: { ja: "矢印がスライドイン", en: "Arrow slides in" },
    html: '<a class="he-nav-arrow" href="#">Menu</a>',
    css: [
      ".he-nav-arrow {",
      "  position: relative; display: inline-block; padding-right: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: padding-right 0.25s ease, color 0.25s ease;",
      "}",
      ".he-nav-arrow::after {",
      '  content: "→"; position: absolute; right: 0; top: 0; color: #6366f1;',
      "  opacity: 0; transform: translateX(-8px);",
      "  transition: opacity 0.25s ease, transform 0.25s ease;",
      "}",
      ".he-nav-arrow:hover { padding-right: 26px; color: #6366f1; }",
      ".he-nav-arrow:hover::after { opacity: 1; transform: translateX(0); }",
    ],
  },
  {
    key: "nav-brackets",
    cat: "nav",
    label: { ja: "ブラケット記号で挟む", en: "Text brackets wrap" },
    html: '<a class="he-nav-bracket" href="#">Menu</a>',
    css: [
      ".he-nav-bracket {",
      "  position: relative; display: inline-block; padding: 0 18px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.25s ease;",
      "}",
      ".he-nav-bracket::before, .he-nav-bracket::after {",
      "  position: absolute; top: 0; color: #6366f1; opacity: 0;",
      "  transition: opacity 0.25s ease, transform 0.25s ease;",
      "}",
      '.he-nav-bracket::before { content: "["; left: 0; transform: translateX(8px); }',
      '.he-nav-bracket::after { content: "]"; right: 0; transform: translateX(-8px); }',
      ".he-nav-bracket:hover { color: #6366f1; }",
      ".he-nav-bracket:hover::before, .he-nav-bracket:hover::after { opacity: 1; transform: translateX(0); }",
    ],
  },
  {
    key: "nav-slash",
    cat: "nav",
    label: { ja: "スラッシュが入る", en: "Slash prefix drops in" },
    html: '<a class="he-nav-slash" href="#">Menu</a>',
    css: [
      ".he-nav-slash {",
      "  position: relative; display: inline-block; padding-left: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: padding-left 0.25s ease, color 0.25s ease;",
      "}",
      ".he-nav-slash::before {",
      '  content: "/"; position: absolute; left: 0; top: 0; color: #ec4899; font-weight: 800;',
      "  opacity: 0; transform: translateY(-8px) rotate(-15deg);",
      "  transition: opacity 0.25s ease, transform 0.25s ease;",
      "}",
      ".he-nav-slash:hover { padding-left: 16px; color: #ec4899; }",
      ".he-nav-slash:hover::before { opacity: 1; transform: translateY(0) rotate(0); }",
    ],
  },
  {
    key: "nav-pill",
    cat: "nav",
    label: { ja: "ピル背景がふわっと", en: "Soft pill background" },
    html: '<a class="he-nav-pill" href="#">Menu</a>',
    css: [
      ".he-nav-pill {",
      "  position: relative; display: inline-block; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.25s ease;",
      "}",
      ".he-nav-pill::before {",
      '  content: ""; position: absolute; inset: -8px -16px; z-index: -1; border-radius: 999px;',
      "  background: rgba(99,102,241,0.12);",
      "  opacity: 0; transform: scale(0.8);",
      "  transition: opacity 0.25s ease, transform 0.25s ease;",
      "}",
      ".he-nav-pill:hover { color: #6366f1; }",
      ".he-nav-pill:hover::before { opacity: 1; transform: scale(1); }",
    ],
  },
  {
    key: "nav-bar",
    cat: "nav",
    label: { ja: "左に縦バー", en: "Vertical bar on left" },
    html: '<a class="he-nav-bar" href="#">Menu</a>',
    css: [
      ".he-nav-bar {",
      "  position: relative; display: inline-block; padding-left: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: padding-left 0.25s ease, color 0.25s ease;",
      "}",
      ".he-nav-bar::before {",
      '  content: ""; position: absolute; left: 0; top: 10%; width: 3px; height: 80%;',
      "  background: #6366f1; border-radius: 2px;",
      "  transform: scaleY(0); transform-origin: bottom;",
      "  transition: transform 0.25s ease;",
      "}",
      ".he-nav-bar:hover { padding-left: 12px; color: #6366f1; }",
      ".he-nav-bar:hover::before { transform: scaleY(1); }",
    ],
  },
  {
    key: "nav-badge",
    cat: "nav",
    label: { ja: "通知バッジがポップ", en: "Badge pops up" },
    html: '<a class="he-nav-badge" href="#">Menu</a>',
    css: [
      ".he-nav-badge {",
      "  position: relative; display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-nav-badge::after {",
      '  content: ""; position: absolute; top: -4px; right: -10px;',
      "  width: 8px; height: 8px; border-radius: 50%; background: #ec4899;",
      "  transform: scale(0);",
      "  transition: transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);",
      "}",
      ".he-nav-badge:hover::after { transform: scale(1); }",
    ],
  },
  {
    key: "nav-chevron",
    cat: "nav",
    label: { ja: "シェブロンが回転", en: "Chevron rotates" },
    html: '<a class="he-nav-chev" href="#">Menu<span class="he-nav-chev-ico">▾</span></a>',
    css: [
      ".he-nav-chev {",
      "  display: inline-flex; align-items: center; gap: 6px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.25s ease;",
      "}",
      ".he-nav-chev-ico {",
      "  display: inline-block; transition: transform 0.3s ease; color: #6366f1;",
      "}",
      ".he-nav-chev:hover { color: #6366f1; }",
      ".he-nav-chev:hover .he-nav-chev-ico { transform: rotate(-180deg); }",
    ],
  },
  {
    key: "nav-icon",
    cat: "nav",
    label: { ja: "アイコンが跳ねる", en: "Icon hops" },
    html: '<a class="he-nav-ico" href="#"><span class="he-nav-ico-mark">🏠</span>Home</a>',
    css: [
      ".he-nav-ico {",
      "  display: inline-flex; align-items: center; gap: 8px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.25s ease;",
      "}",
      ".he-nav-ico-mark {",
      "  display: inline-block; transition: transform 0.25s cubic-bezier(0.34, 1.56, 0.64, 1);",
      "}",
      ".he-nav-ico:hover { color: #6366f1; }",
      ".he-nav-ico:hover .he-nav-ico-mark { transform: translateY(-4px) rotate(-10deg); }",
    ],
  },
  {
    key: "nav-lines",
    cat: "nav",
    label: { ja: "左右に線が伸びる", en: "Lines extend both sides" },
    html: '<a class="he-nav-lines" href="#">Menu</a>',
    css: [
      ".he-nav-lines {",
      "  position: relative; display: inline-block; padding: 0 26px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.25s ease;",
      "}",
      ".he-nav-lines::before, .he-nav-lines::after {",
      '  content: ""; position: absolute; top: 50%; width: 18px; height: 2px; margin-top: -1px;',
      "  background: #6366f1; transform: scaleX(0); transition: transform 0.3s ease;",
      "}",
      ".he-nav-lines::before { left: 0; transform-origin: left; }",
      ".he-nav-lines::after { right: 0; transform-origin: right; }",
      ".he-nav-lines:hover { color: #6366f1; }",
      ".he-nav-lines:hover::before, .he-nav-lines:hover::after { transform: scaleX(1); }",
    ],
  },
];
