// テキスト系ホバーエフェクト（14種）
// 1文字ずつ動かすものはHTML側で <span> に分割している（コピーコードにもそのまま入る）

export const TEXT_EFFECTS = [
  {
    key: "tx-lift",
    cat: "text",
    label: { ja: "1文字ずつ持ち上がる", en: "Letters lift one by one" },
    html: '<a class="he-tx-lift" href="#"><span>M</span><span>e</span><span>n</span><span>u</span></a>',
    css: [
      ".he-tx-lift {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-tx-lift span {",
      "  display: inline-block;",
      "  transition: transform 0.25s ease, color 0.25s ease;",
      "}",
      ".he-tx-lift span:nth-child(2) { transition-delay: 0.05s; }",
      ".he-tx-lift span:nth-child(3) { transition-delay: 0.1s; }",
      ".he-tx-lift span:nth-child(4) { transition-delay: 0.15s; }",
      ".he-tx-lift:hover span { transform: translateY(-6px); color: #6366f1; }",
    ],
  },
  {
    key: "tx-roll",
    cat: "text",
    label: { ja: "上下ロールオーバー", en: "Vertical roll-over" },
    html: '<a class="he-tx-roll" href="#" data-text="Menu"><span>Menu</span></a>',
    css: [
      ".he-tx-roll {",
      "  position: relative; display: inline-block; overflow: hidden; vertical-align: bottom;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-tx-roll span {",
      "  display: inline-block; transition: transform 0.3s ease;",
      "}",
      "/* data-text 属性の複製テキストが下に控えていて、ホバーで一緒にせり上がる */",
      ".he-tx-roll::after {",
      "  content: attr(data-text); position: absolute; left: 0; top: 100%;",
      "  color: #6366f1; transition: transform 0.3s ease;",
      "}",
      ".he-tx-roll:hover span, .he-tx-roll:hover::after { transform: translateY(-100%); }",
    ],
  },
  {
    key: "tx-wipe",
    cat: "text",
    label: { ja: "色が左からワイプ", en: "Color wipe from left" },
    html: '<a class="he-tx-wipe" href="#">Menu</a>',
    css: [
      ".he-tx-wipe {",
      "  display: inline-block;",
      "  font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background: linear-gradient(90deg, #6366f1 50%, #1e293b 50%);",
      "  background-size: 200% 100%; background-position: 100% 0;",
      "  -webkit-background-clip: text; background-clip: text; color: transparent;",
      "  transition: background-position 0.4s ease;",
      "}",
      ".he-tx-wipe:hover { background-position: 0 0; }",
    ],
  },
  {
    key: "tx-spacing",
    cat: "text",
    label: { ja: "字間が広がる", en: "Letter spacing expands" },
    html: '<a class="he-tx-spacing" href="#">Menu</a>',
    css: [
      ".he-tx-spacing {",
      "  display: inline-block; letter-spacing: 0.02em;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: letter-spacing 0.3s ease, color 0.3s ease;",
      "}",
      ".he-tx-spacing:hover { letter-spacing: 0.18em; color: #6366f1; }",
    ],
  },
  {
    key: "tx-shadow-pop",
    cat: "text",
    label: { ja: "影がポップに付く", en: "Pop shadow" },
    html: '<a class="he-tx-pop" href="#">Menu</a>',
    css: [
      ".he-tx-pop {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.25s ease, text-shadow 0.25s ease;",
      "}",
      ".he-tx-pop:hover {",
      "  transform: translate(-2px, -2px);",
      "  text-shadow: 2px 2px 0 #ec4899, 4px 4px 0 #6366f1;",
      "}",
    ],
  },
  {
    key: "tx-strike",
    cat: "text",
    label: { ja: "打ち消し線が走る", en: "Strike-through runs" },
    html: '<a class="he-tx-strike" href="#">Menu</a>',
    css: [
      ".he-tx-strike {",
      "  position: relative; display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: color 0.3s ease;",
      "}",
      ".he-tx-strike::after {",
      '  content: ""; position: absolute; left: -2px; right: -2px; top: 50%; height: 2px;',
      "  background: #ec4899; transform: scaleX(0); transform-origin: left;",
      "  transition: transform 0.3s ease;",
      "}",
      ".he-tx-strike:hover { color: #94a3b8; }",
      ".he-tx-strike:hover::after { transform: scaleX(1); }",
    ],
  },
  {
    key: "tx-wave",
    cat: "text",
    label: { ja: "文字が波打つ", en: "Letters wave" },
    html: '<a class="he-tx-wave" href="#"><span>M</span><span>e</span><span>n</span><span>u</span></a>',
    css: [
      ".he-tx-wave {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-tx-wave span { display: inline-block; }",
      ".he-tx-wave:hover span { animation: he-wave 0.6s ease-in-out infinite; color: #6366f1; }",
      ".he-tx-wave span:nth-child(2) { animation-delay: 0.08s; }",
      ".he-tx-wave span:nth-child(3) { animation-delay: 0.16s; }",
      ".he-tx-wave span:nth-child(4) { animation-delay: 0.24s; }",
      "@keyframes he-wave {",
      "  0%, 100% { transform: translateY(0); }",
      "  50% { transform: translateY(-6px); }",
      "}",
    ],
  },
  {
    key: "tx-flip",
    cat: "text",
    label: { ja: "1文字ずつ縦回転", en: "Letters flip one by one" },
    html: '<a class="he-tx-flip" href="#"><span>M</span><span>e</span><span>n</span><span>u</span></a>',
    css: [
      ".he-tx-flip {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-tx-flip span {",
      "  display: inline-block;",
      "  transition: transform 0.5s ease, color 0.5s ease;",
      "}",
      ".he-tx-flip span:nth-child(2) { transition-delay: 0.07s; }",
      ".he-tx-flip span:nth-child(3) { transition-delay: 0.14s; }",
      ".he-tx-flip span:nth-child(4) { transition-delay: 0.21s; }",
      ".he-tx-flip:hover span { transform: rotateX(360deg); color: #6366f1; }",
    ],
  },
  {
    key: "tx-glitch",
    cat: "text",
    label: { ja: "グリッチ", en: "Glitch" },
    dark: true,
    html: '<a class="he-tx-glitch" href="#" data-text="Menu">Menu</a>',
    css: [
      "/* 暗い背景向け */",
      ".he-tx-glitch {",
      "  position: relative; display: inline-block;",
      "  color: #f8fafc; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-tx-glitch::before, .he-tx-glitch::after {",
      "  content: attr(data-text); position: absolute; left: 0; top: 0; opacity: 0;",
      "}",
      ".he-tx-glitch::before { color: #22d3ee; }",
      ".he-tx-glitch::after { color: #ec4899; }",
      ".he-tx-glitch:hover::before { opacity: 0.9; animation: he-glitch-a 0.3s steps(2) infinite; }",
      ".he-tx-glitch:hover::after { opacity: 0.9; animation: he-glitch-b 0.3s steps(2) infinite; }",
      "@keyframes he-glitch-a {",
      "  0% { transform: translate(-2px, -1px); clip-path: inset(0 0 60% 0); }",
      "  50% { transform: translate(2px, 1px); clip-path: inset(40% 0 20% 0); }",
      "  100% { transform: translate(-1px, 2px); clip-path: inset(70% 0 0 0); }",
      "}",
      "@keyframes he-glitch-b {",
      "  0% { transform: translate(2px, 1px); clip-path: inset(50% 0 10% 0); }",
      "  50% { transform: translate(-2px, -1px); clip-path: inset(0 0 70% 0); }",
      "  100% { transform: translate(1px, -2px); clip-path: inset(30% 0 40% 0); }",
      "}",
    ],
  },
  {
    key: "tx-gradient-flow",
    cat: "text",
    label: { ja: "グラデ文字に変わる", en: "Turns into gradient text" },
    html: '<a class="he-tx-gradflow" href="#">Menu</a>',
    css: [
      ".he-tx-gradflow {",
      "  display: inline-block;",
      "  font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background-image: linear-gradient(90deg, #1e293b 0%, #1e293b 33%, #6366f1 66%, #ec4899 100%);",
      "  background-size: 300% 100%; background-position: 0 0;",
      "  -webkit-background-clip: text; background-clip: text; color: transparent;",
      "  transition: background-position 0.5s ease;",
      "}",
      ".he-tx-gradflow:hover { background-position: 100% 0; }",
    ],
  },
  {
    key: "tx-skew",
    cat: "text",
    label: { ja: "斜めに滑る", en: "Skew slide" },
    html: '<a class="he-tx-skew" href="#">Menu</a>',
    css: [
      ".he-tx-skew {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.25s ease, color 0.25s ease;",
      "}",
      ".he-tx-skew:hover { transform: skewX(-10deg) translateX(4px); color: #6366f1; }",
    ],
  },
  {
    key: "tx-outline",
    cat: "text",
    label: { ja: "中抜き文字になる", en: "Turns into outline text" },
    html: '<a class="he-tx-outline" href="#">Menu</a>',
    css: [
      ".he-tx-outline {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  -webkit-text-stroke: 1.5px transparent;",
      "  transition: color 0.3s ease, -webkit-text-stroke-color 0.3s ease;",
      "}",
      ".he-tx-outline:hover { color: transparent; -webkit-text-stroke-color: #6366f1; }",
    ],
  },
  {
    key: "tx-weight",
    cat: "text",
    label: { ja: "太さが変わる", en: "Weight morphs" },
    html: '<a class="he-tx-weight" href="#">Menu</a>',
    css: [
      "/* 可変フォント（variable font）読み込み時に太さが滑らかに変化する */",
      ".he-tx-weight {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 400; text-decoration: none;",
      "  transition: font-weight 0.3s ease, color 0.3s ease;",
      "}",
      ".he-tx-weight:hover { font-weight: 800; color: #6366f1; }",
    ],
  },
  {
    key: "tx-slide-h",
    cat: "text",
    label: { ja: "横スライドで入れ替わる", en: "Horizontal slide swap" },
    html: '<a class="he-tx-slideh" href="#" data-text="Menu"><span>Menu</span></a>',
    css: [
      ".he-tx-slideh {",
      "  position: relative; display: inline-block; overflow: hidden; vertical-align: bottom;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-tx-slideh span {",
      "  display: inline-block; transition: transform 0.3s ease;",
      "}",
      ".he-tx-slideh::after {",
      "  content: attr(data-text); position: absolute; left: 100%; top: 0;",
      "  color: #6366f1; transition: transform 0.3s ease;",
      "}",
      ".he-tx-slideh:hover span, .he-tx-slideh:hover::after { transform: translateX(-100%); }",
    ],
  },
];
