// 3D系ホバーエフェクト（12種）
// キューブ回転などのnav定番。perspective は要素側に指定して self-contained にしている

export const THREED_EFFECTS = [
  {
    key: "cube-up",
    cat: "threed",
    label: { ja: "キューブ回転（上へ）", en: "Cube rotate up" },
    html: '<a class="he-cbu" href="#"><span class="he-cbu-box"><span class="he-cbu-front">Menu</span><span class="he-cbu-top">Menu</span></span></a>',
    css: [
      ".he-cbu {",
      "  display: inline-block; perspective: 400px; text-decoration: none;",
      "  font-size: 1.15rem; font-weight: 700;",
      "}",
      ".he-cbu-box {",
      "  position: relative; display: block; width: 110px; height: 40px;",
      "  transform-style: preserve-3d; transition: transform 0.4s ease;",
      "}",
      ".he-cbu-front, .he-cbu-top {",
      "  position: absolute; inset: 0; display: flex; align-items: center; justify-content: center;",
      "  border-radius: 6px;",
      "}",
      ".he-cbu-front { background: #f1f5f9; color: #1e293b; transform: translateZ(20px); }",
      ".he-cbu-top { background: #6366f1; color: #fff; transform: rotateX(90deg) translateZ(20px); }",
      ".he-cbu:hover .he-cbu-box { transform: rotateX(-90deg); }",
    ],
  },
  {
    key: "cube-side",
    cat: "threed",
    label: { ja: "キューブ回転（横へ）", en: "Cube rotate sideways" },
    html: '<a class="he-cbs" href="#"><span class="he-cbs-box"><span class="he-cbs-front">Menu</span><span class="he-cbs-side">Menu</span></span></a>',
    css: [
      ".he-cbs {",
      "  display: inline-block; perspective: 500px; text-decoration: none;",
      "  font-size: 1.15rem; font-weight: 700;",
      "}",
      ".he-cbs-box {",
      "  position: relative; display: block; width: 110px; height: 40px;",
      "  transform-style: preserve-3d; transition: transform 0.4s ease;",
      "}",
      ".he-cbs-front, .he-cbs-side {",
      "  position: absolute; inset: 0; display: flex; align-items: center; justify-content: center;",
      "  border-radius: 6px;",
      "}",
      ".he-cbs-front { background: #f1f5f9; color: #1e293b; transform: translateZ(55px); }",
      ".he-cbs-side { background: #6366f1; color: #fff; transform: rotateY(90deg) translateZ(55px); }",
      ".he-cbs:hover .he-cbs-box { transform: rotateY(-90deg); }",
    ],
  },
  {
    key: "flip-v",
    cat: "threed",
    label: { ja: "縦フリップ（裏面）", en: "Vertical flip reveal" },
    html: '<a class="he-flv" href="#"><span class="he-flv-box"><span class="he-flv-front">Menu</span><span class="he-flv-back">Open!</span></span></a>',
    css: [
      ".he-flv {",
      "  display: inline-block; perspective: 500px; text-decoration: none;",
      "  font-size: 1.15rem; font-weight: 700;",
      "}",
      ".he-flv-box {",
      "  position: relative; display: block; width: 110px; height: 40px;",
      "  transform-style: preserve-3d; transition: transform 0.45s ease;",
      "}",
      ".he-flv-front, .he-flv-back {",
      "  position: absolute; inset: 0; display: flex; align-items: center; justify-content: center;",
      "  border-radius: 6px; backface-visibility: hidden;",
      "}",
      ".he-flv-front { background: #f1f5f9; color: #1e293b; }",
      ".he-flv-back { background: #ec4899; color: #fff; transform: rotateX(180deg); }",
      ".he-flv:hover .he-flv-box { transform: rotateX(180deg); }",
    ],
  },
  {
    key: "fold-down",
    cat: "threed",
    label: { ja: "折りたたみが降りる", en: "Panel folds down" },
    html: '<a class="he-fold" href="#" data-text="Menu">Menu</a>',
    css: [
      ".he-fold {",
      "  position: relative; display: inline-block; padding: 8px 20px; border-radius: 6px;",
      "  background: #f1f5f9; color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  perspective: 400px;",
      "}",
      ".he-fold::after {",
      "  content: attr(data-text); position: absolute; inset: 0; border-radius: 6px;",
      "  display: flex; align-items: center; justify-content: center;",
      "  background: #6366f1; color: #fff;",
      "  transform: rotateX(-90deg); transform-origin: top;",
      "  transition: transform 0.35s ease;",
      "}",
      ".he-fold:hover::after { transform: rotateX(0); }",
    ],
  },
  {
    key: "peel",
    cat: "threed",
    label: { ja: "角がめくれる", en: "Corner peels" },
    html: '<a class="he-peel" href="#">Menu</a>',
    css: [
      ".he-peel {",
      "  position: relative; display: inline-block; padding: 10px 22px; border-radius: 8px; overflow: hidden;",
      "  background: #f1f5f9; color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-peel::after {",
      '  content: ""; position: absolute; top: 0; right: 0; width: 0; height: 0;',
      "  background: linear-gradient(225deg, #6366f1 50%, transparent 50.5%);",
      "  transition: width 0.3s ease, height 0.3s ease;",
      "}",
      ".he-peel:hover::after { width: 26px; height: 26px; }",
    ],
  },
  {
    key: "tilt-3d",
    cat: "threed",
    label: { ja: "立体的に傾く", en: "3D tilt" },
    html: '<a class="he-tilt" href="#">Menu</a>',
    css: [
      ".he-tilt {",
      "  display: inline-block; padding: 10px 22px; border-radius: 8px;",
      "  background: #f1f5f9; color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.3s ease, box-shadow 0.3s ease;",
      "}",
      ".he-tilt:hover {",
      "  transform: perspective(500px) rotateX(10deg) rotateY(-10deg) translateY(-2px);",
      "  box-shadow: 8px 12px 20px rgba(30,41,59,0.25);",
      "}",
    ],
  },
  {
    key: "push-3d",
    cat: "threed",
    label: { ja: "押し込みボタン", en: "Push-down button" },
    html: '<a class="he-push" href="#">Menu</a>',
    css: [
      ".he-push {",
      "  display: inline-block; padding: 10px 22px; border-radius: 8px;",
      "  background: #6366f1; color: #fff; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  box-shadow: 0 4px 0 rgba(0,0,0,0.3);",
      "  transition: transform 0.15s ease, box-shadow 0.15s ease;",
      "}",
      ".he-push:hover { transform: translateY(3px); box-shadow: 0 1px 0 rgba(0,0,0,0.3); }",
    ],
  },
  {
    key: "door-open",
    cat: "threed",
    label: { ja: "ドアが開く", en: "Door swings open" },
    html: '<a class="he-door" href="#">Menu</a>',
    css: [
      ".he-door {",
      "  display: inline-block; padding: 10px 22px; border-radius: 8px;",
      "  background: #f1f5f9; color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transform: perspective(500px) rotateY(0); transform-origin: left;",
      "  transition: transform 0.35s ease, background 0.35s ease;",
      "}",
      ".he-door:hover { transform: perspective(500px) rotateY(-24deg); background: #e0e7ff; }",
    ],
  },
  {
    key: "spin-once",
    cat: "threed",
    label: { ja: "くるっと一回転", en: "Full Y-spin" },
    html: '<a class="he-spin" href="#">Menu</a>',
    css: [
      ".he-spin {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.6s ease, color 0.6s ease;",
      "}",
      ".he-spin:hover { transform: rotateY(360deg); color: #6366f1; }",
    ],
  },
  {
    key: "depth-pop",
    cat: "threed",
    label: { ja: "手前に浮き出す", en: "Pops toward you" },
    html: '<a class="he-depth" href="#">Menu</a>',
    css: [
      ".he-depth {",
      "  display: inline-block; padding: 8px 18px; border-radius: 8px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.3s ease, text-shadow 0.3s ease;",
      "}",
      ".he-depth:hover {",
      "  transform: perspective(500px) translateZ(28px);",
      "  text-shadow: 0 6px 10px rgba(30,41,59,0.3);",
      "}",
    ],
  },
  {
    key: "rise-up",
    cat: "threed",
    label: { ja: "奥から起き上がる", en: "Rises from depth" },
    html: '<a class="he-rise" href="#">Menu</a>',
    css: [
      ".he-rise {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transform: perspective(400px) rotateY(28deg) translateZ(-18px); opacity: 0.65;",
      "  transition: transform 0.35s ease, opacity 0.35s ease;",
      "}",
      ".he-rise:hover { transform: perspective(400px) rotateY(0) translateZ(0); opacity: 1; }",
    ],
  },
  {
    key: "fall-back",
    cat: "threed",
    label: { ja: "奥へ倒れる", en: "Falls backward" },
    html: '<a class="he-fall" href="#">Menu</a>',
    css: [
      ".he-fall {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transform-origin: bottom;",
      "  transition: transform 0.35s ease, opacity 0.35s ease;",
      "}",
      ".he-fall:hover { transform: perspective(500px) rotateX(38deg); opacity: 0.7; }",
    ],
  },
];
