// 変形系ホバーエフェクト（10種）

export const TRANSFORM_EFFECTS = [
  {
    key: "tf-spring",
    cat: "transform",
    label: { ja: "弾んで拡大", en: "Springy grow" },
    html: '<a class="he-tf-spring" href="#">Menu</a>',
    css: [
      ".he-tf-spring {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.35s cubic-bezier(0.34, 1.56, 0.64, 1), color 0.35s ease;",
      "}",
      ".he-tf-spring:hover { transform: scale(1.15); color: #6366f1; }",
    ],
  },
  {
    key: "tf-skew",
    cat: "transform",
    label: { ja: "斜めに変形", en: "Skews into parallelogram" },
    html: '<a class="he-tf-skew" href="#">Menu</a>',
    css: [
      ".he-tf-skew {",
      "  display: inline-block; padding: 8px 20px;",
      "  background: #f1f5f9; color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.25s ease, background 0.25s ease, color 0.25s ease;",
      "}",
      ".he-tf-skew:hover { transform: skewX(-12deg); background: #6366f1; color: #fff; }",
    ],
  },
  {
    key: "tf-rotate",
    cat: "transform",
    label: { ja: "ちょい傾き", en: "Slight tilt" },
    html: '<a class="he-tf-rotate" href="#">Menu</a>',
    css: [
      ".he-tf-rotate {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.25s ease, color 0.25s ease;",
      "}",
      ".he-tf-rotate:hover { transform: rotate(-4deg) scale(1.05); color: #6366f1; }",
    ],
  },
  {
    key: "tf-bounce",
    cat: "transform",
    label: { ja: "バウンド", en: "Bounce" },
    html: '<a class="he-tf-bounce" href="#">Menu</a>',
    css: [
      ".he-tf-bounce {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-tf-bounce:hover { animation: he-bounce 0.5s ease; color: #6366f1; }",
      "@keyframes he-bounce {",
      "  0%, 100% { transform: translateY(0); }",
      "  30% { transform: translateY(-10px); }",
      "  60% { transform: translateY(0); }",
      "  80% { transform: translateY(-4px); }",
      "}",
    ],
  },
  {
    key: "tf-jelly",
    cat: "transform",
    label: { ja: "ジェリー", en: "Jelly wobble" },
    html: '<a class="he-tf-jelly" href="#">Menu</a>',
    css: [
      ".he-tf-jelly {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-tf-jelly:hover { animation: he-jelly 0.6s ease; color: #6366f1; }",
      "@keyframes he-jelly {",
      "  0%, 100% { transform: scale(1, 1); }",
      "  25% { transform: scale(1.2, 0.85); }",
      "  50% { transform: scale(0.9, 1.1); }",
      "  75% { transform: scale(1.05, 0.95); }",
      "}",
    ],
  },
  {
    key: "tf-wide",
    cat: "transform",
    label: { ja: "横にのびる", en: "Stretches wide" },
    html: '<a class="he-tf-wide" href="#">Menu</a>',
    css: [
      ".he-tf-wide {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.3s ease, color 0.3s ease;",
      "}",
      ".he-tf-wide:hover { transform: scaleX(1.25); color: #6366f1; }",
    ],
  },
  {
    key: "tf-float",
    cat: "transform",
    label: { ja: "ふわふわ浮遊", en: "Gentle floating" },
    html: '<a class="he-tf-float" href="#">Menu</a>',
    css: [
      ".he-tf-float {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-tf-float:hover { animation: he-float 1.6s ease-in-out infinite; color: #6366f1; }",
      "@keyframes he-float {",
      "  0%, 100% { transform: translateY(0); }",
      "  50% { transform: translateY(-5px); }",
      "}",
    ],
  },
  {
    key: "tf-morph",
    cat: "transform",
    label: { ja: "形がモーフィング", en: "Shape morphs" },
    html: '<a class="he-tf-morph" href="#">Menu</a>',
    css: [
      ".he-tf-morph {",
      "  display: inline-block; padding: 8px 20px; border-radius: 6px;",
      "  background: #f1f5f9; color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: border-radius 0.35s ease, background 0.35s ease, color 0.35s ease, transform 0.35s ease;",
      "}",
      ".he-tf-morph:hover {",
      "  border-radius: 999px; background: #6366f1; color: #fff; transform: rotate(-2deg);",
      "}",
    ],
  },
  {
    key: "tf-pad",
    cat: "transform",
    label: { ja: "余白が広がる", en: "Padding expands" },
    html: '<a class="he-tf-pad" href="#">Menu</a>',
    css: [
      ".he-tf-pad {",
      "  display: inline-block; padding: 8px 16px; border-radius: 999px;",
      "  background: #f1f5f9; color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: padding 0.3s ease, background 0.3s ease, color 0.3s ease;",
      "}",
      ".he-tf-pad:hover { padding: 8px 30px; background: #6366f1; color: #fff; }",
    ],
  },
  {
    key: "tf-press",
    cat: "transform",
    label: { ja: "押されて凹む", en: "Pressed in" },
    html: '<a class="he-tf-press" href="#">Menu</a>',
    css: [
      ".he-tf-press {",
      "  display: inline-block; padding: 8px 20px; border-radius: 8px;",
      "  background: #6366f1; color: #fff; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  transition: transform 0.15s ease, box-shadow 0.15s ease, filter 0.15s ease;",
      "}",
      ".he-tf-press:hover {",
      "  transform: scale(0.94);",
      "  box-shadow: inset 0 3px 6px rgba(0,0,0,0.3);",
      "  filter: brightness(0.95);",
      "}",
    ],
  },
];
