// 下線系ホバーエフェクト（12種）
// 各エフェクトは self-contained（基本の見た目 + :hover）でそのままコピペできる
// アクセント色 #6366f1 / サブ色 #ec4899（rgbは 99,102,241 / 236,72,153）は main.js が置換する

export const UNDERLINE_EFFECTS = [
  {
    key: "ul-left",
    cat: "underline",
    label: { ja: "下線が左から", en: "Underline from left" },
    html: '<a class="he-ul-left" href="#">Menu</a>',
    css: [
      ".he-ul-left {",
      "  display: inline-block; padding-bottom: 4px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background: linear-gradient(#6366f1, #6366f1) no-repeat left bottom / 0 2px;",
      "  transition: background-size 0.3s ease;",
      "}",
      ".he-ul-left:hover { background-size: 100% 2px; }",
    ],
  },
  {
    key: "ul-right",
    cat: "underline",
    label: { ja: "下線が右から", en: "Underline from right" },
    html: '<a class="he-ul-right" href="#">Menu</a>',
    css: [
      ".he-ul-right {",
      "  display: inline-block; padding-bottom: 4px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background: linear-gradient(#6366f1, #6366f1) no-repeat right bottom / 0 2px;",
      "  transition: background-size 0.3s ease;",
      "}",
      ".he-ul-right:hover { background-size: 100% 2px; }",
    ],
  },
  {
    key: "ul-through",
    cat: "underline",
    label: { ja: "通り抜け下線", en: "Slide-through underline" },
    html: '<a class="he-ul-through" href="#">Menu</a>',
    css: [
      ".he-ul-through {",
      "  position: relative; display: inline-block; padding-bottom: 4px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-ul-through::after {",
      '  content: ""; position: absolute; left: 0; bottom: 0; width: 100%; height: 2px;',
      "  background: #6366f1; transform: scaleX(0); transform-origin: right;",
      "  transition: transform 0.3s ease;",
      "}",
      "/* 左から入って、外すと右へ抜ける */",
      ".he-ul-through:hover::after { transform: scaleX(1); transform-origin: left; }",
    ],
  },
  {
    key: "ul-half-marker",
    cat: "underline",
    label: { ja: "ハーフマーカー", en: "Half marker" },
    html: '<a class="he-ul-marker" href="#">Menu</a>',
    css: [
      ".he-ul-marker {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background: linear-gradient(rgba(99,102,241,0.35), rgba(99,102,241,0.35)) no-repeat left bottom / 100% 0;",
      "  transition: background-size 0.3s ease;",
      "}",
      ".he-ul-marker:hover { background-size: 100% 45%; }",
    ],
  },
  {
    key: "ul-double",
    cat: "underline",
    label: { ja: "二重下線（時間差）", en: "Double underline (staggered)" },
    html: '<a class="he-ul-double" href="#">Menu</a>',
    css: [
      ".he-ul-double {",
      "  position: relative; display: inline-block; padding-bottom: 8px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-ul-double::after, .he-ul-double::before {",
      '  content: ""; position: absolute; left: 0; width: 100%; height: 2px;',
      "  transform: scaleX(0); transform-origin: left; transition: transform 0.25s ease;",
      "}",
      ".he-ul-double::after { bottom: 4px; background: #6366f1; }",
      ".he-ul-double::before { bottom: 0; background: #ec4899; transition-delay: 0.12s; }",
      ".he-ul-double:hover::after, .he-ul-double:hover::before { transform: scaleX(1); }",
    ],
  },
  {
    key: "ul-dotted",
    cat: "underline",
    label: { ja: "点線→実線", en: "Dotted to solid" },
    html: '<a class="he-ul-dotted" href="#">Menu</a>',
    css: [
      ".he-ul-dotted {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700;",
      "  text-decoration: underline dotted #94a3b8 2px; text-underline-offset: 6px;",
      "  transition: text-decoration-color 0.3s ease, color 0.3s ease;",
      "}",
      ".he-ul-dotted:hover { text-decoration: underline solid #6366f1 2px; color: #6366f1; }",
    ],
  },
  {
    key: "ul-wavy",
    cat: "underline",
    label: { ja: "波下線が浮かぶ", en: "Wavy underline reveal" },
    html: '<a class="he-ul-wavy" href="#">Menu</a>',
    css: [
      ".he-ul-wavy {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700;",
      "  text-decoration: underline wavy transparent 2px; text-underline-offset: 6px;",
      "  transition: text-decoration-color 0.35s ease;",
      "}",
      ".he-ul-wavy:hover { text-decoration-color: #6366f1; }",
    ],
  },
  {
    key: "ul-gradient",
    cat: "underline",
    label: { ja: "グラデーション下線", en: "Gradient underline" },
    html: '<a class="he-ul-grad" href="#">Menu</a>',
    css: [
      ".he-ul-grad {",
      "  display: inline-block; padding-bottom: 5px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "  background: linear-gradient(90deg, #6366f1, #ec4899) no-repeat left bottom / 0 3px;",
      "  transition: background-size 0.35s ease;",
      "}",
      ".he-ul-grad:hover { background-size: 100% 3px; }",
    ],
  },
  {
    key: "ul-swap",
    cat: "underline",
    label: { ja: "下線が入れ替わる", en: "Underline swap" },
    html: '<a class="he-ul-swap" href="#">Menu</a>',
    css: [
      ".he-ul-swap {",
      "  position: relative; display: inline-block; padding-bottom: 4px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-ul-swap::before, .he-ul-swap::after {",
      '  content: ""; position: absolute; left: 0; bottom: 0; width: 100%; height: 2px;',
      "  transition: transform 0.3s ease;",
      "}",
      "/* グレー下線が右へ抜け、アクセント下線が左から入る */",
      ".he-ul-swap::before { background: #cbd5e1; transform: scaleX(1); transform-origin: right; }",
      ".he-ul-swap::after { background: #6366f1; transform: scaleX(0); transform-origin: left; transition-delay: 0.15s; }",
      ".he-ul-swap:hover::before { transform: scaleX(0); }",
      ".he-ul-swap:hover::after { transform: scaleX(1); }",
    ],
  },
  {
    key: "ul-offset",
    cat: "underline",
    label: { ja: "下線が離れて浮く", en: "Underline drops away" },
    html: '<a class="he-ul-offset" href="#">Menu</a>',
    css: [
      ".he-ul-offset {",
      "  display: inline-block;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700;",
      "  text-decoration: underline #94a3b8 2px; text-underline-offset: 3px;",
      "  transition: text-underline-offset 0.3s ease, text-decoration-color 0.3s ease;",
      "}",
      ".he-ul-offset:hover { text-underline-offset: 9px; text-decoration-color: #6366f1; }",
    ],
  },
  {
    key: "ul-skew",
    cat: "underline",
    label: { ja: "斜めハイライト線", en: "Skewed highlight line" },
    html: '<a class="he-ul-skew" href="#">Menu</a>',
    css: [
      ".he-ul-skew {",
      "  position: relative; display: inline-block; z-index: 0;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-ul-skew::after {",
      '  content: ""; position: absolute; left: -4px; right: -4px; bottom: 1px; height: 8px; z-index: -1;',
      "  background: rgba(99,102,241,0.35); transform: skewX(-20deg) scaleX(0); transform-origin: left;",
      "  transition: transform 0.3s ease;",
      "}",
      ".he-ul-skew:hover::after { transform: skewX(-20deg) scaleX(1); }",
    ],
  },
  {
    key: "ul-frame",
    cat: "underline",
    label: { ja: "上下線で挟む", en: "Over + underline" },
    html: '<a class="he-ul-frame" href="#">Menu</a>',
    css: [
      ".he-ul-frame {",
      "  position: relative; display: inline-block; padding: 6px 2px;",
      "  color: #1e293b; font-size: 1.15rem; font-weight: 700; text-decoration: none;",
      "}",
      ".he-ul-frame::before, .he-ul-frame::after {",
      '  content: ""; position: absolute; left: 0; width: 100%; height: 2px;',
      "  background: #6366f1; transform: scaleX(0); transition: transform 0.3s ease;",
      "}",
      "/* 上線は左から・下線は右から伸びる */",
      ".he-ul-frame::before { top: 0; transform-origin: left; }",
      ".he-ul-frame::after { bottom: 0; transform-origin: right; }",
      ".he-ul-frame:hover::before, .he-ul-frame:hover::after { transform: scaleX(1); }",
    ],
  },
];
