// 問題データ（Q1/Q6/Q9/Q13/Q16 は記事版 /nodejs-practice-problems/ のサンプル5問と同期）
// vfs: 仮想ファイルシステムの初期状態（実行のたびにリセット）。argv/env: 実行コマンドのシミュレート
// filename: エディタが編集しているとみなすファイル名。moduleFormat: 'esm' で nextTick とマイクロタスクの順序が逆転する
const PROBLEMS = [
  {"id":1,"title":"fs：ファイルを読んだはずが Promise が表示される","questionHtml":"<code>notes.txt</code> の中身を表示してから <code>copy.txt</code> に複製するプログラムです。中身が表示されるはずが <code>Promise { &lt;pending&gt; }</code> のようになり、書き込みでもエラーになります。原因を直してください（記事版 問1）。","filename":"index.js","vfs":{"notes.txt":"今日の学習メモ：Node.jsのfsモジュールを練習中。"},"starter":"const fs = require('node:fs/promises');\n\nasync function main() {\n  const text = fs.readFile('notes.txt', 'utf8');\n  console.log(text); // 期待: ファイルの中身\n  await fs.writeFile('copy.txt', text); // ここでもエラーになる\n}\n\nmain();","answer":"const fs = require('node:fs/promises');\n\nasync function main() {\n  const text = await fs.readFile('notes.txt', 'utf8');\n  console.log(text); // ファイルの中身\n  await fs.writeFile('copy.txt', text);\n}\n\nmain();\n// fs/promises のAPIはすべてPromiseを返すので await が必須"},
  {"id":2,"title":"fs：読み込んだ内容を加工して別ファイルに書き出す","questionHtml":"<code>notes.txt</code> を読み込み、内容をすべて大文字（<code>toUpperCase</code>）にして <code>upper.txt</code> に書き出し、最後に <code>upper.txt</code> を読み直して表示してください。","filename":"index.js","vfs":{"notes.txt":"hello node.js file system"},"starter":"const fs = require('node:fs/promises');\n\nasync function main() {\n  // ここに処理を書く\n}\n\nmain();","answer":"const fs = require('node:fs/promises');\n\nasync function main() {\n  const text = await fs.readFile('notes.txt', 'utf8');\n  await fs.writeFile('upper.txt', text.toUpperCase());\n  const result = await fs.readFile('upper.txt', 'utf8');\n  console.log(result); // HELLO NODE.JS FILE SYSTEM\n}\n\nmain();"},
  {"id":3,"title":"fs：ログファイルに追記する","questionHtml":"<code>log.txt</code> の既存の内容を消さずに、末尾へ「[2] 処理完了」という行を追記してください（<code>appendFile</code>・改行 <code>\\n</code> 付き）。追記後にファイル全体を読み直して表示します。","filename":"index.js","vfs":{"log.txt":"[1] アプリ起動\n"},"starter":"const fs = require('node:fs/promises');\n\nasync function main() {\n  // ここに処理を書く\n}\n\nmain();","answer":"const fs = require('node:fs/promises');\n\nasync function main() {\n  await fs.appendFile('log.txt', '[2] 処理完了\\n');\n  const log = await fs.readFile('log.txt', 'utf8');\n  console.log(log);\n}\n\nmain();\n// writeFile だと上書きされて [1] の行が消えてしまう"},
  {"id":4,"title":"fs：フォルダの中の .txt だけを一覧する","questionHtml":"<code>data</code> フォルダの中身を <code>readdir</code> で取得し、拡張子が <code>.txt</code> のファイル名だけを1つずつ <code>console.log</code> してください（<code>path.extname</code> と組み合わせます）。","filename":"index.js","vfs":{"data/report.txt":"売上レポート","data/memo.md":"# メモ","data/backup.txt":"バックアップ","data/logo.png":"(バイナリのつもり)"},"starter":"const fs = require('node:fs/promises');\nconst path = require('node:path');\n\nasync function main() {\n  // ここに処理を書く\n}\n\nmain();","answer":"const fs = require('node:fs/promises');\nconst path = require('node:path');\n\nasync function main() {\n  const names = await fs.readdir('data');\n  for (const name of names) {\n    if (path.extname(name) === '.txt') {\n      console.log(name); // backup.txt / report.txt\n    }\n  }\n}\n\nmain();"},
  {"id":5,"title":"fs：存在しないファイルをエラー処理する","questionHtml":"このコードは <code>config.json</code> が無いためエラーで落ちます。<code>try/catch</code> を使い、エラーコードが <code>ENOENT</code>（ファイルが存在しない）のときは「設定ファイルなし：既定値を使います」と表示して <code>{}</code> を使うように直してください。","filename":"index.js","vfs":{"notes.txt":"config.json はまだ作っていない"},"starter":"const fs = require('node:fs/promises');\n\nasync function loadConfig() {\n  const text = await fs.readFile('config.json', 'utf8');\n  return JSON.parse(text);\n}\n\nasync function main() {\n  const config = await loadConfig();\n  console.log('設定:', config);\n}\n\nmain();","answer":"const fs = require('node:fs/promises');\n\nasync function loadConfig() {\n  try {\n    const text = await fs.readFile('config.json', 'utf8');\n    return JSON.parse(text);\n  } catch (err) {\n    if (err.code === 'ENOENT') {\n      console.log('設定ファイルなし：既定値を使います');\n      return {};\n    }\n    throw err; // ENOENT以外は握りつぶさず再throw\n  }\n}\n\nasync function main() {\n  const config = await loadConfig();\n  console.log('設定:', config);\n}\n\nmain();"},
  {"id":6,"title":"path：文字列連結のパスがWindowsで壊れる","questionHtml":"フォルダ名とファイル名からパスを組み立てて拡張子を取り出すプログラムです。文字列連結の <code>/</code> はWindowsで区切りが混在し、<code>split('.')[1]</code> は <code>report.v2.txt</code> のようなファイル名で壊れます。<code>node:path</code> で2つとも直してください（記事版 問2）。","filename":"index.js","vfs":{},"starter":"const dir = 'data/reports';\nconst file = 'report.v2.txt';\n\nconst fullPath = dir + '/' + file;\nconsole.log(fullPath);\n\nconst ext = file.split('.')[1];\nconsole.log(ext); // 期待: txt ／ 実際: v2","answer":"const path = require('node:path');\n\nconst dir = 'data/reports';\nconst file = 'report.v2.txt';\n\nconst fullPath = path.join(dir, file);\nconsole.log(fullPath); // OSに合った区切りで結合される\n\nconst ext = path.extname(file);\nconsole.log(ext); // .txt（「最後のドット以降」を返す仕様）"},
  {"id":7,"title":"path：フルパスを部品に分解する","questionHtml":"フルパス <code>/app/data/reports/2026-07.csv</code> から、①ファイル名（<code>2026-07.csv</code>）②親ディレクトリ（<code>/app/data/reports</code>）③拡張子を除いたファイル名（<code>2026-07</code>）の3つを取り出して表示してください。","filename":"index.js","vfs":{},"starter":"const path = require('node:path');\nconst fullPath = '/app/data/reports/2026-07.csv';\n\n// ここに処理を書く","answer":"const path = require('node:path');\nconst fullPath = '/app/data/reports/2026-07.csv';\n\nconsole.log(path.basename(fullPath));          // 2026-07.csv\nconsole.log(path.dirname(fullPath));           // /app/data/reports\nconsole.log(path.basename(fullPath, '.csv'));  // 2026-07\n// basename の第2引数に拡張子を渡すと、その部分を除いた名前が返る"},
  {"id":8,"title":"path：join と resolve の違いを予測する","questionHtml":"予測問題です。カレントディレクトリが <code>/app</code> のとき、次の2つの <code>console.log</code> は何を出力するでしょうか。先に紙に書いてから実行して確かめてください。","filename":"index.js","vfs":{},"starter":"const path = require('node:path');\n\nconsole.log(path.join('data', '../logs', 'app.log'));\nconsole.log(path.resolve('data', 'app.log'));","answer":"const path = require('node:path');\n\nconsole.log(path.join('data', '../logs', 'app.log'));\n// → logs/app.log（joinは相対のまま結合し、.. を正規化するだけ）\n\nconsole.log(path.resolve('data', 'app.log'));\n// → /app/data/app.log（resolveはカレントディレクトリ基準の絶対パスに解決する）"},
  {"id":9,"title":"モジュール：require is not defined と怒られる","questionHtml":"<code>package.json</code> に <code>\"type\": \"module\"</code> が設定されたプロジェクトです。<code>require</code> を使うと <code>ReferenceError: require is not defined in ES module scope</code> になります。ESMの構文（<code>import</code>）に書き換えて動かしてください（記事版 問3）。","filename":"index.js","moduleFormat":"esm","esmGuard":true,"vfs":{"package.json":"{\n  \"name\": \"practice\",\n  \"type\": \"module\"\n}"},"starter":"const path = require('node:path'); // ReferenceError!\n\nconsole.log(path.join('data', 'app.log'));","answer":"import path from 'node:path';\n\nconsole.log(path.join('data', 'app.log'));\n// \"type\": \"module\" のプロジェクトでは .js はESMとして読み込まれるため\n// require ではなく import を使う（このファイルだけCJSに戻すなら拡張子を .cjs にする）"},
  {"id":10,"title":"モジュール：自作モジュールを require で読み込む","questionHtml":"<code>tax.js</code> には税込価格を計算する関数が <code>module.exports</code> されています。これを <code>require('./tax.js')</code> で読み込み、<code>1200</code> 円の税込価格を表示してください。","filename":"index.js","vfs":{"tax.js":"// 10%の消費税を足して四捨五入する\nmodule.exports = function withTax(price) {\n  return Math.round(price * 1.1);\n};"},"starter":"// tax.js を読み込んで 1200 円の税込価格を表示する\n","answer":"const withTax = require('./tax.js');\n\nconsole.log(withTax(1200) + '円'); // 1320円\n// module.exports に代入したもの（今回は関数そのもの）が require の戻り値になる"},
  {"id":11,"title":"モジュール：JSONファイルを require で読み込む","questionHtml":"<code>users.json</code> を <code>require</code> で読み込むと、パース済みの配列がそのまま手に入ります。全ユーザーの名前をカンマ区切りで1行に表示してください。","filename":"index.js","vfs":{"users.json":"[\n  { \"name\": \"sato\", \"age\": 28 },\n  { \"name\": \"suzuki\", \"age\": 34 },\n  { \"name\": \"takahashi\", \"age\": 25 }\n]"},"starter":"// users.json を読み込んで名前一覧を表示する\n","answer":"const users = require('./users.json');\n\nconsole.log(users.map(u => u.name).join(', '));\n// → sato, suzuki, takahashi\n// require はJSONを自動でパースする（読み取り専用の設定ファイルに便利）"},
  {"id":12,"title":"モジュール：名前つきエクスポートを分割代入で受け取る","questionHtml":"<code>utils.js</code> には <code>slugify</code> と <code>truncate</code> の2関数がエクスポートされています。分割代入で <code>slugify</code> だけを取り出し、<code>'Hello Node World'</code> をスラッグ化して表示してください。","filename":"index.js","vfs":{"utils.js":"// 名前つきエクスポート（exports.xxx = ...）\nexports.slugify = (s) => s.toLowerCase().replace(/\\s+/g, '-');\nexports.truncate = (s, n) => s.length > n ? s.slice(0, n) + '…' : s;"},"starter":"// utils.js から slugify を取り出して使う\n","answer":"const { slugify } = require('./utils.js');\n\nconsole.log(slugify('Hello Node World')); // hello-node-world\n// exports.xxx で生やした関数は、require側で分割代入して受け取れる\n// （const { join } = require('node:path') と同じパターン）"},
  {"id":13,"title":"process：コマンドライン引数と環境変数が読めない","questionHtml":"<code>DEBUG=true node index.js Taro</code> と実行した想定です。名前の代わりにスクリプトのパスが表示され、デバッグ表示も出ません。<code>argv</code> の添字と、環境変数の型に注目して2つの原因を直してください（記事版 問4）。","filename":"index.js","argv":["Taro"],"env":{"DEBUG":"true"},"starter":"const name = process.argv[1];\nconsole.log(`Hello, ${name}!`); // 期待: Hello, Taro! ／ 実際: パスが出る\n\nif (process.env.DEBUG === true) {\n  console.log('debug mode'); // DEBUG=true を付けても表示されない\n}","answer":"const name = process.argv[2] ?? 'guest';\nconsole.log(`Hello, ${name}!`); // Hello, Taro!\n\nif (process.env.DEBUG === 'true') {\n  console.log('debug mode');\n}\n// argv[0]=node本体 / argv[1]=スクリプトパス / ユーザー引数は[2]から\n// 環境変数の値は常に文字列なので 'true' と比較する"},
  {"id":14,"title":"process：引数の合計が文字列連結になってしまう","questionHtml":"<code>node index.js 3 5 10</code> と実行して合計 <code>18</code> を出したいのに、<code>03510</code> と表示されます。原因を説明して直してください。","filename":"index.js","argv":["3","5","10"],"starter":"const args = process.argv.slice(2);\n\nlet total = 0;\nfor (const a of args) {\n  total = total + a;\n}\nconsole.log('合計: ' + total); // 期待: 18 ／ 実際: 03510","answer":"const args = process.argv.slice(2);\n\nlet total = 0;\nfor (const a of args) {\n  total = total + Number(a);\n}\nconsole.log('合計: ' + total); // 合計: 18\n// argv の中身はすべて文字列。0 + '3' は文字列連結の '03' になる\n// Number(a) か parseInt で数値に変換してから足す"},
  {"id":15,"title":"process：環境変数が無いときの既定値","questionHtml":"環境変数 <code>PORT</code> が設定されていないため「ポート: undefined」と表示されます。<code>PORT</code> が無いときは <code>3000</code> を使うように直してください（<code>??</code> を使います）。","filename":"index.js","env":{},"starter":"const port = process.env.PORT;\nconsole.log('ポート: ' + port); // ポート: undefined","answer":"const port = process.env.PORT ?? 3000;\nconsole.log('ポート: ' + port); // ポート: 3000\n// ?? は「null / undefined のときだけ」右側を使う\n// || だと PORT=0 のような値も既定値に置き換わってしまう点に注意"},
  {"id":16,"title":"イベントループ：6つのログの出力順を予測する（CJS）","questionHtml":"予測問題です。このコードを <strong>CommonJS（index.cjs）として実行</strong>したとき、A〜Fはどの順番で出力されるでしょうか。「必ずこの順になる」と言い切れないペアが1組あります。それも含めて予測してから実行してください（記事版 問5）。","filename":"index.cjs","vfs":{},"starter":"console.log('A');\n\nsetTimeout(() => console.log('B'), 0);\nsetImmediate(() => console.log('C'));\nPromise.resolve().then(() => console.log('D'));\nprocess.nextTick(() => console.log('E'));\n\nconsole.log('F');","answer":"// 答え: A → F → E → D → (B・C は順不同)\n//\n// 1. 同期コードの A・F が先\n// 2. CJSでは process.nextTick(E) がPromiseマイクロタスク(D)より常に先\n// 3. メインモジュール直下の setTimeout(0) と setImmediate の順序は\n//    Node.js公式が「non-deterministic（非決定的）」と明記\n//    （この仮想環境では C→B の順に固定されるが、実機では入れ替わり得る）\nconsole.log('A');\n\nsetTimeout(() => console.log('B'), 0);\nsetImmediate(() => console.log('C'));\nPromise.resolve().then(() => console.log('D'));\nprocess.nextTick(() => console.log('E'));\n\nconsole.log('F');"},
  {"id":17,"title":"イベントループ：同じコードをESMで実行すると順序が変わる","questionHtml":"Q16とまったく同じコードを、今度は <strong>ESM（index.mjs）として実行</strong>します。DとEの順序はどうなるでしょうか。予測してから実行し、Q16との違いを確認してください。","filename":"index.mjs","moduleFormat":"esm","vfs":{},"starter":"console.log('A');\n\nsetTimeout(() => console.log('B'), 0);\nsetImmediate(() => console.log('C'));\nPromise.resolve().then(() => console.log('D'));\nprocess.nextTick(() => console.log('E'));\n\nconsole.log('F');","answer":"// 答え: A → F → D → E → (B・C)　※Q16とDとEが逆転する\n//\n// ESMモジュールは「既にマイクロタスクキューの一部として」処理されるため、\n// queueMicrotask / Promise のコールバック(D)が process.nextTick(E) より先に実行される\n// （Node.js公式ドキュメント process の章に明記）\n// 「nextTickが常に最優先」はCJS限定の知識。モジュール形式で答えが変わる\nconsole.log('A');\n\nsetTimeout(() => console.log('B'), 0);\nsetImmediate(() => console.log('C'));\nPromise.resolve().then(() => console.log('D'));\nprocess.nextTick(() => console.log('E'));\n\nconsole.log('F');"},
  {"id":18,"title":"イベントループ：I/Oの後なら setImmediate が必ず勝つ","questionHtml":"予測問題です。ファイル読み込み（I/O）の<strong>完了後</strong>に <code>setTimeout(0)</code> と <code>setImmediate</code> を仕込みました。TとIはどちらが先に出力されるでしょうか。Q16の「順不同」との違いに注目してください。","filename":"index.js","vfs":{"data.txt":"I/Oのきっかけ用ファイル"},"starter":"const fs = require('node:fs/promises');\n\nfs.readFile('data.txt', 'utf8').then(() => {\n  setTimeout(() => console.log('T (setTimeout)'), 0);\n  setImmediate(() => console.log('I (setImmediate)'));\n});","answer":"// 答え: I (setImmediate) → T (setTimeout)\n//\n// I/Oコールバックの中でスケジュールした場合、イベントループは\n// 直後の check フェーズで setImmediate を実行するため、必ず I が先になる\n// （メインモジュール直下では順不同だったのと対照的）\n// Node.js公式は「推論しやすいため、あらゆる場面で setImmediate() を推奨」\nconst fs = require('node:fs/promises');\n\nfs.readFile('data.txt', 'utf8').then(() => {\n  setTimeout(() => console.log('T (setTimeout)'), 0);\n  setImmediate(() => console.log('I (setImmediate)'));\n});"},
  {"id":19,"title":"Buffer：日本語の「長さ」が3倍になる理由","questionHtml":"予測問題です。文字列 <code>'こんにちは'</code> について、①<code>length</code> ②<code>Buffer.byteLength()</code> ③<code>Buffer.from().length</code> はそれぞれいくつになるでしょうか。予測してから実行してください。","filename":"index.js","vfs":{},"starter":"const text = 'こんにちは';\n\nconsole.log(text.length);\nconsole.log(Buffer.byteLength(text));\nconsole.log(Buffer.from(text).length);","answer":"const text = 'こんにちは';\n\nconsole.log(text.length);             // 5（文字数）\nconsole.log(Buffer.byteLength(text)); // 15（UTF-8のバイト数）\nconsole.log(Buffer.from(text).length); // 15（Bufferの length はバイト数）\n// 日本語はUTF-8で1文字3バイト。ファイルサイズや通信量の計算では\n// 「文字数」ではなく「バイト数」で考える——これがBufferの世界"},
  {"id":20,"title":"総仕上げ：Streamでファイルをチャンク受信する","questionHtml":"256バイトの <code>big.txt</code> を <code>createReadStream</code>（<code>highWaterMark: 64</code>）で読み込みます。<code>data</code> イベントで受信回数と合計バイト数を集計し、<code>end</code> イベントで「チャンク数: N / 合計: Mバイト」と表示してください。","filename":"index.js","vfs":{"big.txt":"Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js Node.js "},"starter":"const fs = require('node:fs');\n\nconst stream = fs.createReadStream('big.txt', { highWaterMark: 64 });\n\n// ここに data / end のイベント処理を書く","answer":"const fs = require('node:fs');\n\nconst stream = fs.createReadStream('big.txt', { highWaterMark: 64 });\n\nlet chunks = 0;\nlet bytes = 0;\n\nstream.on('data', (chunk) => {\n  chunks = chunks + 1;\n  bytes = bytes + chunk.length;\n  console.log('受信: ' + chunk.length + 'バイト');\n});\n\nstream.on('end', () => {\n  console.log('チャンク数: ' + chunks + ' / 合計: ' + bytes + 'バイト');\n});\n// → 64バイト×4回、チャンク数: 4 / 合計: 256バイト\n// 全部読み終わるのを待たず、少しずつ処理できるのがStreamの強み\n// （巨大ファイルでもメモリを食い尽くさない）"}
];

const LEVELS = [
  { key: 'all', label: 'すべて (20問)', range: [1, 20] },
  { key: 'fs', label: 'fs 1-5', range: [1, 5] },
  { key: 'pathmod', label: 'path・モジュール 6-12', range: [6, 12] },
  { key: 'process', label: 'process 13-15', range: [13, 15] },
  { key: 'loop', label: 'イベントループ・応用 16-20', range: [16, 20] }
];
