// 英語版：カテゴリ名と、ショットごとの名前・使いどころ・伝わること・AIで生成するときのコツ（id ごと）
export const CATEGORY_EN = {
  establish: "Establishing",
  size: "Shot Size",
  relation: "Relationships & Dialogue",
  angle: "Angle & Viewpoint",
  move: "Camera Movement",
  effect: "Effects & Transitions",
};

export const META_EN = {
  es01: {
    name: "Aerial extreme wide",
    use: "Opening a video, or whenever the location changes",
    intent: "Tells viewers where the story takes place in an instant. A tiny figure against a vast space makes it feel like the start of a story.",
    tips: "Place the person small, on a rule-of-thirds line. Avoid words that make the subject bigger, such as \"close\".",
  },
  es02: {
    name: "Static wide shot",
    use: "Starting a scene and showing the character's situation",
    intent: "With a still camera, the person and their surroundings are shown together. The calm frame makes the next, closer cut feel like a real change.",
    tips: "Describe the background (street, room, season) in one sentence. Add \"static camera\" so no movement creeps in.",
  },
  es03: {
    name: "City at night from above",
    use: "Opening an urban story, or switching to a night scene",
    intent: "City lights seen from up high set the stage and the time of day at once. With no people in frame, the next cut to a person feels like a contrast.",
    tips: "Write \"city skyline at night\" and where you are looking from (from a rooftop, etc.). Leave people out.",
  },
  es04: {
    name: "Building exterior",
    use: "Showing where the story happens (a shop, office, school or home)",
    intent: "Showing the building from outside tells viewers the next cut happens inside it. A small figure heading in sets up the move indoors.",
    tips: "Be specific about the building (a small corner cafe with a striped awning, etc.). Skip sign text, since AI often garbles letters.",
  },
  es05: {
    name: "One person in a crowd",
    use: "Loneliness, a lead character in the city, standing apart from everyone else",
    intent: "One person stands still while a crowd moves around them, drawing the eye to the lead. The more the crowd moves, the more the stillness says.",
    tips: "Separate \"crowd moving around\" from \"one person standing still\" clearly. Clothing in a different color makes them easy to spot.",
  },
  sz01: {
    name: "Full shot",
    use: "Showing clothing, posture, or a whole-body action",
    intent: "Head to toe in frame shows exactly how the character looks and moves. Use this size for walking, dancing and other full-body motion.",
    tips: "\"full body, head to toe\" keeps the feet from being cropped. Keep it to one action.",
  },
  sz02: {
    name: "Medium shot",
    use: "Talking, explaining, reacting",
    intent: "From the chest up, you see both the face and the hands. It is the default size for dialogue, so start from here for any cut with lines.",
    tips: "This size keeps mouths from warping when characters speak. State where they look (at the camera or off-screen).",
  },
  sz03: {
    name: "Close-up (face)",
    use: "Emotional peaks, resolve, surprise",
    intent: "Filling the frame with the face shows feelings that go unsaid. If the cuts around it are medium shots, moving in here really lands.",
    tips: "Describe a single change in expression (smiles slowly, etc.). Stacking several emotions tends to break the face.",
  },
  sz04: {
    name: "Extreme close-up (eyes or object)",
    use: "Tension, a moment of realization, product texture",
    intent: "Filling the frame with just the eyes or part of an object pins attention to one point. A short insert builds tension.",
    tips: "For objects, name the material (metal, fabric, etc.) and how light hits it to bring out the texture.",
  },
  sz05: {
    name: "Knee-up (medium long shot)",
    use: "Walking and talking, scenes with gestures",
    intent: "Framing from the knees up shows both the face and the body language. It sits between a full shot and a medium shot.",
    tips: "Write \"knee-up shot\". Adding a hand gesture (gesturing with her hands, etc.) gives this size its purpose.",
  },
  sz06: {
    name: "Close-up of hands",
    use: "Working, operating something, handing something over",
    intent: "Showing the hands instead of the face makes the action itself concrete. With no expression to read, the gesture carries the meaning.",
    tips: "Write \"close-up of hands\" and one thing they do (pouring coffee, etc.). Fingers often warp, so keep the motion simple.",
  },
  rl01: {
    name: "Over-the-shoulder",
    use: "Conversations and face-to-face exchanges",
    intent: "One person's shoulder in the foreground shows two people facing each other. Cutting back and forth keeps the conversation flowing.",
    tips: "Blur the foreground person (blurred foreground) so the focus lands on the person behind.",
  },
  rl02: {
    name: "Two shot",
    use: "Showing a relationship, walking together, facing each other",
    intent: "With two people in one frame, distance and direction show their relationship. Closer reads as intimate, farther apart as distant.",
    tips: "Spell out positions (left / right) and which way each faces. Describe each person the same way in every cut to keep them consistent.",
  },
  rl03: {
    name: "Reverse over-the-shoulder",
    use: "The listener's face and reaction",
    intent: "After an over-the-shoulder shot of the speaker, shoot the listener from the opposite side. Alternating the two makes the dialogue feel natural.",
    tips: "Write \"reverse over-the-shoulder shot\" and keep the same room and clothing as the previous cut. Swap left and right.",
  },
  rl04: {
    name: "Walking side by side",
    use: "A relationship moving forward, talking on the move",
    intent: "Shooting two people from the side shows them heading the same way. Moving the camera with them keeps the conversation unbroken.",
    tips: "Write \"walking side by side, filmed from the side\" and that the camera moves with them (tracking). The gap between them sets how close they feel.",
  },
  rl05: {
    name: "Back to back",
    use: "Drifting apart, conflict, a parting",
    intent: "Two people stand back to back, looking opposite ways. Sharing the frame without meeting each other's eyes shows the emotional gap.",
    tips: "Write \"standing back to back, looking in opposite directions\". Keep expressions muted and let posture do the work.",
  },
  rl06: {
    name: "Group shot",
    use: "Friends, teams, family scenes",
    intent: "Three or more people in one frame convey the mood of the group. Whoever sits at the center becomes the focus of the moment.",
    tips: "Give the number of people (four friends, etc.) and how they are arranged. Faces break more with more people, so stay around four.",
  },
  ag01: {
    name: "High angle",
    use: "Weakness, loneliness, being overwhelmed",
    intent: "Looking down makes a person look small and vulnerable. Use it when someone is low, or swallowed by a bigger situation.",
    tips: "Include \"high angle looking down\". The floor fills more of the frame, so a word about its texture tightens the image.",
  },
  ag02: {
    name: "Low angle",
    use: "Strength, confidence, a heroic feel",
    intent: "Looking up makes a person look big and powerful. Good for the first step after a decision, or an entrance.",
    tips: "Include \"low angle looking up\" with sky or ceiling. Pairing it with backlight (backlit) makes it even stronger.",
  },
  ag03: {
    name: "Top-down (bird's-eye)",
    use: "Desks, food, layouts, a sense of the uncanny",
    intent: "From directly above, the arrangement of objects and people reads like a diagram. It is not an everyday view, so it sticks in the memory.",
    tips: "Include \"top-down view, directly above\". For food or hands at work, nothing explains it better than a straight-down shot.",
  },
  ag04: {
    name: "POV (first-person)",
    use: "Putting viewers in the character's shoes, game or travel viewpoints",
    intent: "Showing exactly what the character sees turns the viewer into the participant. Hands in frame make it clear whose view it is.",
    tips: "Write \"first-person POV, hands visible in frame\". Describing what the hands do (reaching out, etc.) sells the viewpoint.",
  },
  ag05: {
    name: "Dutch angle (tilted frame)",
    use: "Anxiety, confusion, rising tension",
    intent: "Tilting the frame makes viewers feel uneasy. It gets tiring if overused, so save it for the moment emotions waver.",
    tips: "Write \"Dutch angle, tilted frame\". Keep the tilt around 15 degrees and pair it with an expression (anxious, etc.).",
  },
  ag06: {
    name: "Through the foreground (peeking)",
    use: "Spying, watching from afar, adding depth",
    intent: "Leaves or a window frame in front reveal the person through a gap. It feels like someone is secretly watching, and the frame gains depth.",
    tips: "Write \"shot through leaves in the foreground\" and blur that foreground (blurred foreground).",
  },
  ag07: {
    name: "Mirror reflection",
    use: "Inner thoughts, hesitation, another side of oneself",
    intent: "Showing a reflection says the character is facing themselves. With both the person and the reflection in frame, it plays like an inner dialogue.",
    tips: "Write \"reflection in a mirror\" and keep the mirror frame in shot. Reflections often go wrong, so keep the background simple.",
  },
  mv01: {
    name: "Slow push-in (dolly in)",
    use: "Rising emotion, a realization, right before a key line",
    intent: "Slowly moving closer draws attention into the character's inner world. Placed right before a line, it gives the words weight.",
    tips: "Write \"slow dolly-in\" and where it starts (medium) and ends (close-up). Keep the speed slow by default.",
  },
  mv02: {
    name: "Slow pull-out (dolly out)",
    use: "Lingering feelings, loneliness, the end of a story",
    intent: "Moving away widens the space and shrinks the person. It conveys an ending, or the feeling of being left behind.",
    tips: "Write \"slow dolly-out revealing the surroundings\" and what should be visible at the end (the whole room, etc.).",
  },
  mv03: {
    name: "Pan (left to right)",
    use: "Showing a wide view, moving the eye from one person to another",
    intent: "Sweeping the camera sideways shows a space too wide for one frame, or links two things that are far apart.",
    tips: "Give the direction: \"slow pan from left to right\". Fast pans smear and break, so keep it slow.",
  },
  mv04: {
    name: "Tracking shot",
    use: "Running, hurrying, chasing",
    intent: "The camera moves at the same speed as the subject, keeping them in the same spot on screen. The streaming background adds speed and urgency.",
    tips: "Write \"tracking shot following the subject\" and the motion (running, etc.). Motion blur in the background sells the speed.",
  },
  mv05: {
    name: "Tilt (up or down)",
    use: "Showing height, revealing a person from feet to face",
    intent: "Tilting the camera vertically reveals a tall building or a full figure piece by piece. Tilting up from the feet makes for a memorable entrance.",
    tips: "Write \"slow tilt up from ... to ...\" with where the move starts and ends.",
  },
  mv06: {
    name: "Orbit",
    use: "Key moments, resolve, a reunion",
    intent: "The camera circles the subject, keeping them centered while the background turns. At the story's peak, it marks the moment as special.",
    tips: "Write \"the camera orbits around the subject\" and the speed (slowly). Something moving in the background makes the orbit readable.",
  },
  mv07: {
    name: "Handheld",
    use: "Immediacy, a documentary feel, panic",
    intent: "A slightly shaky handheld frame feels raw, as if you are there. Contrasted with steady shots, it also builds tension.",
    tips: "Write \"handheld camera, slight shake\". Too much shake is hard to watch, so keep it slight.",
  },
  mv08: {
    name: "Drone fly-forward",
    use: "The start of a journey, epic scenery, travel",
    intent: "Flying forward over the landscape conveys the scale of where you are headed. Good for a trip or the start of a new chapter.",
    tips: "Write \"drone shot flying forward over ...\" with the scenery ahead. Leave people out, or keep them tiny.",
  },
  ef01: {
    name: "Backlit silhouette",
    use: "Hiding identity, lingering moods, symbolic moments",
    intent: "A person against a bright background shows only a shadow and hides the face. Good when you want viewers to imagine, or for a striking ending.",
    tips: "Write \"silhouette against a bright window, backlit\". Facial detail doesn't matter, so describe the posture or pose instead.",
  },
  ef02: {
    name: "Rack focus",
    use: "Moving the eye from foreground to background",
    intent: "Shifting focus from an object in front to a person behind guides the viewer's attention. One cut shows how the object and the person are linked.",
    tips: "Write \"rack focus from ... to ...\". Video AI struggles with the shift, so generate the starting frame (foreground sharp) and describe the move in the prompt.",
  },
  ef03: {
    name: "Insert shot",
    use: "A letter, phone or photo that matters to the story",
    intent: "Cutting to an object alone mid-scene tells viewers it matters. It adds meaning to the shots of people around it.",
    tips: "Write \"insert shot of ... on a desk\" and the object's state (handwritten, slightly crumpled, etc.). Don't specify the text itself.",
  },
  ef04: {
    name: "Empty shot",
    use: "Lingering moods, scene changes, the passing of time",
    intent: "A few seconds of scenery with no one in it gives viewers a breath. It also works for scene changes or to show time has passed.",
    tips: "State \"empty shot, no people\". One moving element (waves, clouds) keeps the frame from feeling frozen.",
  },
  ef05: {
    name: "Slow motion",
    use: "Decisive moments, emotional peaks",
    intent: "Slowing the motion stretches a single moment. It works best on short actions, like turning around or reaching out.",
    tips: "Write \"slow motion\" and one action to slow down (turning around, etc.). Hair or fabric in motion makes the slowness visible.",
  },
  ef06: {
    name: "Rain on the window",
    use: "Mirroring feelings in the weather, bridging scenes",
    intent: "Expresses a character's feelings through weather and scenery. It leaves more room than showing a face directly.",
    tips: "Write \"raindrops on a window\" and what lies beyond (blurred city lights). No people needed.",
  },
};
