// 追加のショット（2026-10-06 第2弾）。項目の意味は index.js と同じ
// frame は写真が読めないときの代わりに描く SVG の指定

export default [
  {
    id: "es03", cat: "establish", name: "夜景の俯瞰（街の全景）",
    use: "都会の話の始まり・夜の場面への切り替え",
    intent: "高い所から街の明かりを見せて、これから始まる話の舞台と時間帯を一度に伝える。人物を映さないので、次のカットで人物に寄ったときの対比が出る。",
    tips: "city skyline at night と、どの高さから見ているか（from a rooftop など）を書く。人物は入れない。",
    vocab: { shot: "ews", angle: "high", move: "static", light: "night" },
    desc: "A high wide view of a city skyline at night, filled with countless lights",
    dur: 3, frame: { subject: "landscape", size: "ews", horizon: 40 },
  },
  {
    id: "es04", cat: "establish", name: "建物の外観",
    use: "舞台になる場所（店・会社・学校・家）を示す",
    intent: "物語の舞台になる建物を外から見せ、次のカットが「この中の話」だと分からせる。人物を小さく入れると、これから中に入る流れが作れる。",
    tips: "建物の種類と特徴（a small corner cafe with a striped awning など）を具体的に書く。看板の文字は崩れやすいので文字の指定はしない。",
    vocab: { shot: "ws", angle: "eye", move: "static", light: "day" },
    desc: "An exterior shot of a small corner cafe on a quiet street in the afternoon, a woman about to walk in",
    dur: 3, frame: { subject: "landscape", size: "ws", horizon: 70 },
  },
  {
    id: "es05", cat: "establish", name: "群衆の中の1人",
    use: "孤独・都会の中の主人公・その他大勢との対比",
    intent: "動いている大勢の中で1人だけ立ち止まらせ、見る人の目を主人公に集める。周りが動くほど、止まっている人物の気持ちが際立つ。",
    tips: "crowd moving around と one person standing still をはっきり分けて書く。人物の服の色を周りと変えると見つけやすい。",
    vocab: { shot: "ws", angle: "high", move: "static", light: "day" },
    desc: "A busy pedestrian crossing seen from above, one man standing still among the moving crowd",
    dur: 3, frame: { subject: "landscape", size: "ws", horizon: 20 },
  },
  {
    id: "sz05", cat: "size", name: "膝上（ミディアムロング）",
    use: "歩きながら話す・身振り手振りのある場面",
    intent: "膝から上を映して、表情と体の動きの両方を見せる。全身より人物に近く、バストアップより動きが伝わる中間のサイズ。",
    tips: "knee-up shot と書く。手の動き（gesturing with her hands など）を入れると、このサイズを選んだ意味が出る。",
    vocab: { shot: "ms", angle: "eye", move: "static", light: "day" },
    desc: "A knee-up shot of a woman walking and talking in a sunny park, gesturing with her hands",
    dur: 4, frame: { subject: "person", size: "ms" },
  },
  {
    id: "sz06", cat: "size", name: "手元のアップ",
    use: "作業・操作・物を渡す瞬間",
    intent: "顔ではなく手を映して、何をしているかを具体的に見せる。表情を見せないぶん、動作そのものに意味を持たせられる。",
    tips: "close-up of hands と、手が何をしているか（pouring coffee など）を1つだけ書く。指の本数が崩れやすいので、手の動きは単純にする。",
    vocab: { shot: "cu", angle: "high", move: "static", light: "day" },
    desc: "A close-up of a man's hands pouring coffee into a cup on a wooden table",
    dur: 3, frame: { subject: "object" },
  },
  {
    id: "rl03", cat: "relation", name: "切り返し（反対側の肩越し）",
    use: "会話の受け手の表情・リアクション",
    intent: "肩越しで話している人を撮ったら、次は反対側から聞いている人を撮る。2つを交互につなぐと、会話のやり取りが自然に見える。",
    tips: "reverse over-the-shoulder shot と書き、前のカットと同じ部屋・同じ服装を指定する。左右の位置を前のカットと逆にする。",
    vocab: { shot: "ms", angle: "ots", move: "static", light: "day" },
    desc: "A reverse over-the-shoulder shot in a bright meeting room, a man's shoulder in the foreground and a woman listening",
    dur: 4, frame: { subject: "ots" },
  },
  {
    id: "rl04", cat: "relation", name: "並んで歩く（横から）",
    use: "2人の関係が進む・移動しながらの会話",
    intent: "2人を横から並べて撮り、同じ方向へ進んでいることを見せる。カメラも一緒に横へ動くと、会話の流れが途切れない。",
    tips: "walking side by side, filmed from the side と、カメラが一緒に動くこと（tracking）を書く。2人の距離で親しさが変わる。",
    vocab: { shot: "fs", angle: "eye", move: "track", light: "golden" },
    desc: "A man and a woman walking side by side along a riverside path, filmed from the side as the camera tracks with them",
    dur: 4, frame: { subject: "two" },
  },
  {
    id: "rl05", cat: "relation", name: "背中合わせ",
    use: "すれ違い・対立・別れ",
    intent: "2人を背中合わせに立たせ、逆の方向を見させる。同じ画面にいるのに目が合わないことで、気持ちのすれ違いを見せる。",
    tips: "standing back to back, looking in opposite directions と書く。表情は少なめにして、姿勢で伝える。",
    vocab: { shot: "fs", angle: "eye", move: "static", light: "day" },
    desc: "A man and a woman standing back to back on a bridge on a cloudy day, looking in opposite directions",
    dur: 3, frame: { subject: "two" },
  },
  {
    id: "rl06", cat: "relation", name: "グループショット",
    use: "仲間・チーム・家族の場面",
    intent: "3人以上を1つの画面に入れて、集団の雰囲気を伝える。誰を中心に置くかで、その場の主役が決まる。",
    tips: "人数（four friends など）と並び方を書く。人数が多いほど顔が崩れやすいので、4人程度までにする。",
    vocab: { shot: "ws", angle: "eye", move: "static", light: "day" },
    desc: "A group of four friends laughing together around an outdoor cafe table",
    dur: 3, frame: { subject: "two" },
  },
  {
    id: "ag05", cat: "angle", name: "傾けた画（ダッチアングル）",
    use: "不安・混乱・緊張が高まる場面",
    intent: "画面を斜めに傾けて、見る人に落ち着かなさを感じさせる。多用すると疲れるので、気持ちが揺れる一瞬だけに使う。",
    tips: "Dutch angle, tilted frame と書く。傾きは15度前後にとどめ、表情（anxious など）を合わせて指定する。",
    vocab: { shot: "ms", angle: "", move: "static", light: "night" },
    desc: "A Dutch angle shot of a man looking anxious in a dim hallway, the frame tilted",
    dur: 2, frame: { subject: "person", size: "ms" },
  },
  {
    id: "ag06", cat: "angle", name: "前景越し（のぞき見）",
    use: "盗み見・遠くから見守る・奥行きを出す",
    intent: "手前に葉や窓枠などを入れて、その隙間から人物を見せる。誰かがこっそり見ているような距離感と、画面の奥行きが出る。",
    tips: "shot through leaves in the foreground と、手前の物をぼかすこと（blurred foreground）を書く。",
    vocab: { shot: "ms", angle: "eye", move: "static", light: "day" },
    desc: "A shot through leaves in the blurred foreground, a woman reading a book on a bench in the background",
    dur: 3, frame: { subject: "person", size: "fs" },
  },
  {
    id: "ag07", cat: "angle", name: "鏡越し",
    use: "内面・迷い・もう一人の自分",
    intent: "鏡に映った姿を見せて、人物が自分と向き合っていることを表す。本人と鏡像を両方入れると、心の中の対話のように見える。",
    tips: "reflection in a mirror と、鏡の枠を画面に入れることを書く。文字や反転の矛盾が出やすいので、背景はシンプルにする。",
    vocab: { shot: "ms", angle: "eye", move: "static", light: "studio" },
    desc: "A man looking at his reflection in a bathroom mirror, the mirror frame visible",
    dur: 3, frame: { subject: "person", size: "ms" },
  },
  {
    id: "mv04", cat: "move", name: "追いかける（トラッキング）",
    use: "走る・急ぐ・追う場面",
    intent: "動く人物と同じ速さでカメラも動き、人物を画面の同じ位置に保つ。背景が流れることで、スピードと切迫感が出る。",
    tips: "tracking shot following the subject と、人物の動き（running など）を書く。背景のブレ（motion blur）を入れると速さが出る。",
    vocab: { shot: "fs", angle: "eye", move: "track", light: "day" },
    desc: "The camera tracks alongside a man running down a city sidewalk, the background blurred with motion",
    dur: 3, frame: { subject: "person", size: "fs" },
  },
  {
    id: "mv05", cat: "move", name: "上下に振る（ティルト）",
    use: "高さを見せる・人物を足元から顔へ見せる",
    intent: "カメラを縦に振って、高い建物や人物の全身を順に見せる。足元から顔へ上げると、人物の登場を印象づけられる。",
    tips: "slow tilt up from ... to ... と、どこからどこまで振るかを書く。",
    vocab: { shot: "fs", angle: "low", move: "tilt", light: "day" },
    desc: "A slow tilt up from a woman's shoes to her face as she stands in front of a tall office building",
    dur: 4, frame: { subject: "person", size: "fs" },
  },
  {
    id: "mv06", cat: "move", name: "周りを回る（オービット）",
    use: "見せ場・決意・再会の瞬間",
    intent: "人物の周りをカメラが回り込み、背景を動かしながら人物を中心に据え続ける。物語の山場で使うと特別な瞬間だと伝わる。",
    tips: "the camera orbits around the subject と、回る速さ（slowly）を書く。背景に動きのある物を入れると回っているのが分かる。",
    vocab: { shot: "ms", angle: "eye", move: "orbit", light: "golden" },
    desc: "The camera slowly orbits around a man standing on a rooftop at sunset",
    dur: 4, frame: { subject: "person", size: "ms" },
  },
  {
    id: "mv07", cat: "move", name: "手持ち（ハンディ）",
    use: "臨場感・ドキュメンタリー風・焦り",
    intent: "わざと少し揺れる手持ちの画にして、その場にいるような生々しさを出す。きれいに整えた画との対比で緊張感も作れる。",
    tips: "handheld camera, slight shake と書く。揺れを強くしすぎると見づらいので slight にとどめる。",
    vocab: { shot: "ms", angle: "eye", move: "hand", light: "night" },
    desc: "Handheld footage following a woman through a busy night market",
    dur: 3, frame: { subject: "person", size: "ms" },
  },
  {
    id: "mv08", cat: "move", name: "空撮で進む（ドローン）",
    use: "旅の始まり・壮大な風景・移動",
    intent: "上空を前へ進みながら景色を見せ、これから向かう場所の広さを伝える。旅や新しい章の始まりに向く。",
    tips: "drone shot flying forward over ... と、進む方向の景色を書く。人物は入れないか、ごく小さくする。",
    vocab: { shot: "ews", angle: "high", move: "drone", light: "day" },
    desc: "A drone shot flying forward over a coastline with a winding road along the sea",
    dur: 4, frame: { subject: "landscape", size: "ews", horizon: 34 },
  },
  {
    id: "ef01", cat: "effect", name: "逆光のシルエット",
    use: "正体を隠す・余韻・象徴的な場面",
    intent: "明るい背景の前に人物を置いて影だけを見せ、表情を隠す。見る人の想像に任せたい場面や、印象的な締めに使える。",
    tips: "silhouette against a bright window, backlit と書く。顔の細部は出なくてよいので、姿勢やポーズを指定する。",
    vocab: { shot: "fs", angle: "eye", move: "static", light: "back" },
    desc: "A silhouette of a man standing against a bright window, backlit",
    dur: 3, frame: { subject: "person", size: "fs" },
  },
  {
    id: "ef02", cat: "effect", name: "ピント送り",
    use: "視線や注意を手前から奥へ移す",
    intent: "手前の物から奥の人物へピントを移し、見る人の注意を誘導する。物と人物の関係（誰の物か）を1カットで見せられる。",
    tips: "rack focus from ... to ... と書く。生成AIでは動きが出にくいので、起点（手前にピント）の画を作り、動きはプロンプトで指定する。",
    vocab: { shot: "ms", angle: "eye", move: "static", light: "day" },
    desc: "A rack focus shot: a coffee cup sharp in the foreground, a woman softly blurred in the background",
    dur: 3, frame: { subject: "object" },
  },
  {
    id: "ef03", cat: "effect", name: "インサート（物のアップ）",
    use: "手紙・スマホ・写真など物語の鍵になる物",
    intent: "話の流れの途中に物だけのアップを挟み、それが大事な物だと伝える。前後の人物のカットに意味を足せる。",
    tips: "insert shot of ... on a desk と、物の状態（handwritten, slightly crumpled など）を書く。文字の内容は指定しない。",
    vocab: { shot: "ecu", angle: "high", move: "static", light: "day" },
    desc: "An insert shot of a handwritten letter and an old photograph on a wooden desk",
    dur: 2, frame: { subject: "object" },
  },
  {
    id: "ef04", cat: "effect", name: "人のいない風景（空ショット）",
    use: "余韻・場面転換・時間の経過",
    intent: "人物のいない風景を数秒入れて、気持ちを落ち着かせる間を作る。場面の切り替えや、時間が経ったことの表現にも使える。",
    tips: "empty shot, no people と明記する。動きのある要素（waves, clouds）を1つ入れると止まった画にならない。",
    vocab: { shot: "ws", angle: "eye", move: "static", light: "golden" },
    desc: "An empty shot of a quiet beach at dusk with gentle waves and no people",
    dur: 3, frame: { subject: "landscape", size: "ews", horizon: 50 },
  },
  {
    id: "ef05", cat: "effect", name: "スローモーション",
    use: "決定的な瞬間・感情が高まる瞬間",
    intent: "動きをゆっくり見せて、その一瞬を引き延ばす。振り返る・手を伸ばすなど、短い動作に使うと効果が大きい。",
    tips: "slow motion と、ゆっくり見せる動作を1つ（turning around など）書く。髪や布など揺れる物を入れると遅さが伝わる。",
    vocab: { shot: "ms", angle: "eye", move: "static", light: "golden" },
    desc: "Slow motion of a woman turning around, her hair blowing in the wind",
    dur: 3, frame: { subject: "person", size: "ms" },
  },
  {
    id: "ef06", cat: "effect", name: "窓の外の雨（情景）",
    use: "心情を天気に重ねる・場面のつなぎ",
    intent: "人物の気持ちを、天気や景色に置き換えて見せる。直接表情を映すより、余白のある伝え方になる。",
    tips: "raindrops on a window と、窓の向こうの景色（blurred city lights）を書く。人物は入れなくてよい。",
    vocab: { shot: "cu", angle: "eye", move: "static", light: "night" },
    desc: "Raindrops running down a window at night with blurred city lights behind",
    dur: 3, frame: { subject: "landscape", size: "ews", horizon: 50 },
  },
];
