// 問題データ（Q1-10は記事版 id1339 と同期・Q11-20はアプリ限定ドリル）
// stageHtml: プレビューiframeに描画するHTML。answerはiframe内で実行される
// ※ alert() はアプリ内では console 欄に [alert] として表示される
const PROBLEMS = [
  {"id":1,"title":"fetchでAPIからデータ取得（Promise）","questionHtml":"ボタンをクリックすると、JSONPlaceholderのAPIからデータを取得し、タイトルをアラート表示してください（<code>fetch</code>＋<code>.then</code>）。","stageHtml":"<button id=\"btn1\">データ取得（then）</button>","answer":"document.getElementById('btn1').addEventListener('click', () => {\n  fetch('https://jsonplaceholder.typicode.com/todos/1')\n    .then(response => response.json())\n    .then(data => {\n      alert('タイトル: ' + data.title);\n    })\n    .catch(error => {\n      alert('エラーが発生しました');\n    });\n});"},
  {"id":2,"title":"async/awaitでAPI取得","questionHtml":"Q1と同じ処理を、<code>async/await</code> を使用して書き換えてください（<code>try-catch</code> でエラー処理）。","stageHtml":"<button id=\"btn2\">データ取得（async/await）</button>","answer":"document.getElementById('btn2').addEventListener('click', async () => {\n  try {\n    const response = await fetch('https://jsonplaceholder.typicode.com/todos/1');\n    const data = await response.json();\n    alert('タイトル: ' + data.title);\n  } catch (error) {\n    alert('エラーが発生しました');\n  }\n});"},
  {"id":3,"title":"ネットワークエラーをハンドリング","questionHtml":"存在しないURLにリクエストを送り、<code>response.ok</code> をチェックしてエラーをキャッチ・表示してください。","stageHtml":"<button id=\"btn3\">エラーテスト</button>","answer":"document.getElementById('btn3').addEventListener('click', () => {\n  fetch('https://jsonplaceholder.typicode.com/invalid-url')\n    .then(response => {\n      if (!response.ok) {\n        throw new Error('レスポンスエラー');\n      }\n      return response.json();\n    })\n    .then(data => console.log(data))\n    .catch(error => {\n      alert('エラー: ' + error.message);\n    });\n});"},
  {"id":4,"title":"複数のAPIを順番に取得","questionHtml":"2つのAPIから<strong>順番に</strong>データを取得し、それぞれのタイトルを表示してください（awaitを直列に並べます）。","stageHtml":"<button id=\"btn4\">2件取得（順番）</button>","answer":"document.getElementById('btn4').addEventListener('click', async () => {\n  try {\n    const response1 = await fetch('https://jsonplaceholder.typicode.com/todos/1');\n    const data1 = await response1.json();\n    const response2 = await fetch('https://jsonplaceholder.typicode.com/todos/2');\n    const data2 = await response2.json();\n    alert(`1: ${data1.title}\\n2: ${data2.title}`);\n  } catch (error) {\n    alert('取得失敗');\n  }\n});"},
  {"id":5,"title":"Promise.allで同時に取得","questionHtml":"複数のAPIを<strong>並列で</strong>実行し、すべての結果を表示してください（<code>Promise.all</code>）。","stageHtml":"<button id=\"btn5\">2件取得（同時）</button>","answer":"document.getElementById('btn5').addEventListener('click', async () => {\n  try {\n    const [response1, response2] = await Promise.all([\n      fetch('https://jsonplaceholder.typicode.com/todos/1'),\n      fetch('https://jsonplaceholder.typicode.com/todos/2')\n    ]);\n    const data1 = await response1.json();\n    const data2 = await response2.json();\n    alert(`1: ${data1.title}\\n2: ${data2.title}`);\n  } catch (error) {\n    alert('取得エラー');\n  }\n});"},
  {"id":6,"title":"setTimeoutで遅延表示","questionHtml":"ボタンをクリックしてから3秒後に、<code>#msg6</code> へ「こんにちは！」と表示してください（待っている間は案内文を表示）。","stageHtml":"<button id=\"btn6\">3秒後に表示</button>\n<p id=\"msg6\"></p>","answer":"document.getElementById('btn6').addEventListener('click', () => {\n  document.getElementById('msg6').textContent = '3秒待ってください...';\n  setTimeout(() => {\n    document.getElementById('msg6').textContent = 'こんにちは！';\n  }, 3000);\n});"},
  {"id":7,"title":"ローディング表示 → API取得後に表示","questionHtml":"ボタンをクリックすると「読み込み中...」と表示し、取得完了後に <code>#result7</code> へタイトルを表示してください。","stageHtml":"<button id=\"btn7\">データを取得</button>\n<p id=\"result7\"></p>","answer":"document.getElementById('btn7').addEventListener('click', async () => {\n  const result = document.getElementById('result7');\n  result.textContent = '読み込み中...';\n  try {\n    const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');\n    const data = await res.json();\n    result.textContent = '取得したタイトル：' + data.title;\n  } catch (e) {\n    result.textContent = 'エラーが発生しました';\n  }\n});"},
  {"id":8,"title":"ボタン連打を防ぐ（多重実行対策）","questionHtml":"通信中はボタンを <code>disabled</code> にして連打を防ぎ、完了後に再度有効化してください（2秒の疑似送信処理を使います）。","stageHtml":"<button id=\"btn8\">送信する</button>\n<p id=\"status8\"></p>","answer":"const btn8 = document.getElementById('btn8');\nconst status8 = document.getElementById('status8');\nbtn8.addEventListener('click', async () => {\n  btn8.disabled = true;\n  status8.textContent = '送信中...';\n  await new Promise(resolve => setTimeout(resolve, 2000)); // 疑似送信処理\n  status8.textContent = '送信完了！';\n  btn8.disabled = false;\n});"},
  {"id":9,"title":"データをPOST送信して結果を表示","questionHtml":"名前を入力して送信ボタンを押すと、APIに <code>POST</code> し「送信完了」メッセージを <code>#status9</code> に表示してください。","stageHtml":"<input type=\"text\" id=\"nameInput9\" placeholder=\"名前を入力\" />\n<button id=\"btn9\">送信</button>\n<p id=\"status9\"></p>","answer":"document.getElementById('btn9').addEventListener('click', async () => {\n  const name = document.getElementById('nameInput9').value;\n  const status = document.getElementById('status9');\n  status.textContent = '送信中...';\n  try {\n    await fetch('https://jsonplaceholder.typicode.com/posts', {\n      method: 'POST',\n      body: JSON.stringify({ name }),\n      headers: { 'Content-Type': 'application/json' }\n    });\n    status.textContent = `送信完了！こんにちは、${name}さん！`;\n  } catch (e) {\n    status.textContent = '送信に失敗しました';\n  }\n});"},
  {"id":10,"title":"ユーザーID入力でAPIから情報を取得","questionHtml":"ユーザーID（1〜10）を入力してそのユーザーの名前を取得し、<code>#userInfo10</code> に表示してください（未入力チェック・エラー処理付き）。","stageHtml":"<input type=\"number\" id=\"userIdInput10\" placeholder=\"ユーザーID (1~10)\" />\n<button id=\"btn10\">ユーザー取得</button>\n<p id=\"userInfo10\"></p>","answer":"document.getElementById('btn10').addEventListener('click', async () => {\n  const id = document.getElementById('userIdInput10').value;\n  const userInfo = document.getElementById('userInfo10');\n  if (!id) {\n    userInfo.textContent = 'IDを入力してください';\n    return;\n  }\n  userInfo.textContent = '取得中...';\n  try {\n    const res = await fetch(`https://jsonplaceholder.typicode.com/users/${id}`);\n    if (!res.ok) throw new Error('取得失敗');\n    const user = await res.json();\n    userInfo.textContent = `名前：${user.name}`;\n  } catch (e) {\n    userInfo.textContent = '取得できませんでした';\n  }\n});"},
  {"id":11,"title":"new Promiseで待機関数を作る","questionHtml":"<code>ms</code> ミリ秒待つ関数 <code>wait(ms)</code> を <code>new Promise</code> で自作し、2秒待ってからメッセージを表示してください。","stageHtml":"","answer":"function wait(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms));\n}\n\nconsole.log('待機開始...');\nawait wait(2000);\nconsole.log('2秒たちました！');"},
  {"id":12,"title":"Promiseチェーン","questionHtml":"<code>Promise.resolve(5)</code> から始めて、「2倍する → 10を足す」の順に <code>.then</code> でつなぎ、結果の20を表示してください。","stageHtml":"","answer":"Promise.resolve(5)\n  .then(n => n * 2)\n  .then(n => n + 10)\n  .then(n => console.log('結果:', n));"},
  {"id":13,"title":"rejectとcatch","questionHtml":"偶数なら <code>resolve</code>、奇数なら <code>reject</code> する関数 <code>checkEven(n)</code> を作り、4と7で呼び出して結果を表示してください。","stageHtml":"","answer":"function checkEven(n) {\n  return new Promise((resolve, reject) => {\n    if (n % 2 === 0) resolve(n + ' は偶数です');\n    else reject(new Error(n + ' は奇数です'));\n  });\n}\n\ncheckEven(4)\n  .then(msg => console.log('OK:', msg))\n  .catch(err => console.log('NG:', err.message));\n\ncheckEven(7)\n  .then(msg => console.log('OK:', msg))\n  .catch(err => console.log('NG:', err.message));"},
  {"id":14,"title":"Promise.raceでタイムアウト","questionHtml":"3秒で <code>reject</code> するタイムアウトPromiseと <code>fetch</code> を <code>Promise.race</code> で競わせ、先に終わった方の結果を表示してください。","stageHtml":"","answer":"function timeout(ms) {\n  return new Promise((_, reject) =>\n    setTimeout(() => reject(new Error('タイムアウト')), ms)\n  );\n}\n\ntry {\n  const res = await Promise.race([\n    fetch('https://jsonplaceholder.typicode.com/todos/1'),\n    timeout(3000)\n  ]);\n  const data = await res.json();\n  console.log('取得成功:', data.title);\n} catch (e) {\n  console.log('失敗:', e.message);\n}"},
  {"id":15,"title":"Promise.allSettledで結果を仕分け","questionHtml":"成功するリクエストと失敗するリクエストを <code>Promise.allSettled</code> でまとめて実行し、成功／失敗を仕分けて表示してください。","stageHtml":"","answer":"const results = await Promise.allSettled([\n  fetch('https://jsonplaceholder.typicode.com/todos/1').then(r => r.json()),\n  fetch('https://jsonplaceholder.typicode.com/invalid-url').then(r => {\n    if (!r.ok) throw new Error('HTTP ' + r.status);\n    return r.json();\n  })\n]);\n\nresults.forEach((r, i) => {\n  if (r.status === 'fulfilled') console.log((i + 1) + '件目 成功:', r.value.title);\n  else console.log((i + 1) + '件目 失敗:', r.reason.message);\n});"},
  {"id":16,"title":"async関数の戻り値はPromise","questionHtml":"値を <code>return</code> するだけの <code>async</code> 関数を作り、戻り値が <code>Promise</code> であることを確認してから <code>.then</code> で値を受け取ってください。","stageHtml":"","answer":"async function getMessage() {\n  return 'こんにちは';\n}\n\nconst p = getMessage();\nconsole.log(p instanceof Promise); // true\np.then(msg => console.log(msg));"},
  {"id":17,"title":"直列と並列の実行時間を比較","questionHtml":"500ms待つ処理を2つ、<strong>直列（awaitを2回）</strong>と<strong>並列（Promise.all）</strong>で実行し、かかった時間を比較してください（<code>performance.now()</code>）。","stageHtml":"","answer":"function wait(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms));\n}\n\nconst t1 = performance.now();\nawait wait(500);\nawait wait(500);\nconsole.log('直列:', Math.round(performance.now() - t1) + 'ms');\n\nconst t2 = performance.now();\nawait Promise.all([wait(500), wait(500)]);\nconsole.log('並列:', Math.round(performance.now() - t2) + 'ms');"},
  {"id":18,"title":"エラーの再スロー","questionHtml":"<code>fetch</code> の失敗を <code>try-catch</code> で捕まえ、メッセージを付け直して <code>throw</code> し、呼び出し側の <code>catch</code> で表示してください。","stageHtml":"","answer":"async function fetchUser(id) {\n  try {\n    const res = await fetch('https://jsonplaceholder.typicode.com/users/' + id);\n    if (!res.ok) throw new Error('HTTP ' + res.status);\n    return await res.json();\n  } catch (e) {\n    throw new Error('ユーザー取得に失敗しました（' + e.message + '）');\n  }\n}\n\ntry {\n  await fetchUser(9999);\n} catch (e) {\n  console.log(e.message);\n}"},
  {"id":19,"title":"クエリパラメータ付きfetch","questionHtml":"<code>?postId=1</code> のクエリパラメータ付きでコメント一覧を取得し、件数と最初の3件のメールアドレスを表示してください。","stageHtml":"","answer":"const res = await fetch('https://jsonplaceholder.typicode.com/comments?postId=1');\nconst comments = await res.json();\nconsole.log('postId=1 のコメント件数:', comments.length);\ncomments.slice(0, 3).forEach(c => console.log('-', c.email));"},
  {"id":20,"title":"総仕上げ：複数ユーザーを並列取得","questionHtml":"ユーザーID <code>[1, 2, 3]</code> を <code>map</code> でfetchの配列にし、<code>Promise.all</code> で並列取得して全員の名前を表示してください。","stageHtml":"","answer":"const ids = [1, 2, 3];\nconst users = await Promise.all(\n  ids.map(id =>\n    fetch('https://jsonplaceholder.typicode.com/users/' + id).then(r => r.json())\n  )\n);\nusers.forEach(u => console.log(u.id + ':', u.name));"}
];

const LEVELS = [
  { key: 'all', label: 'すべて (20問)', range: [1, 20] },
  { key: 'basic', label: 'fetch基礎 1-5', range: [1, 5] },
  { key: 'ui', label: 'UI連携 6-10', range: [6, 10] },
  { key: 'extra', label: 'アプリ限定 11-20', range: [11, 20] }
];
